### ISSUE TITLE
MiNT/XaAES 1-19-B43 Desktop load error ...

### ISSUE THREAD

**Issue by franklukas** [freemint/freemint#103]
I have a Atari Mega ST with PAK68/3 Speeder (68030+68882/50Mhz) and 64MB Fastram. I run Freemint 1-19-B43. I put a line "include u:/c/mint/desktop.cnf" in the xaaes.cnf file. When xaaes starts up it pops a error on the screen "pid   9 (desktop): ADDRESS | ERROR: User PC=135002E, | Address: 0 (basepage=1330000, | text=1330100, data=1350BC2, | bss=1352746)

When I Process/Lauch Program over the xaaes menu I can load desktop.prg (Teradesk) and it runs and works fine.

When I Process/Lauch Desk it came up a message "pid   4 (aesthred): XaAES: AES shell already running!" but it is not running

**Comment by mikrosk** [comment]
Hi Frank,

- do you have NVDI installed?
- are you using the 020+ archive? (I'd assume so)
- is memory protection enabled?
- does it work if the PAK is disabled (if there is such option)

We don't have many reports from such interesting hardware so it's possible something has been overlooked.

**Comment by franklukas** [comment]
- When I disable NVDI the Teradesk loading Error is the same
- I use the 020 archive
- memory protection is off
- desktop.cnf

setenv AVSERVER		"DESKTOP "
setenv FONTSELECT	"DESKTOP "
shell = u:\c\teradesk\desktop.prg
#setenv AVSERVER		"THING "
#setenv FONTSELECT	"THING "
#shell = u:\c\thing\thing.app
#setenv AVSERVER		"JINNEE "
#setenv FONTSELECT	"JINNEE "
#shell = u:\c\jinnee\jinnee.app

- I can not disable the PAK
- xaaes.log

include: 'u:/c/mint/desktop.cnf'
sysfile_exists: 'u:\c\MINT\1-19-B43\XAAES\moose_w.adi'
sysfile_exists: 'u:\c\MINT\1-19-B43\XAAES\moose.adi'
both moose_w.adi and moose.adi found (better choose one)
lang='de' (from AKP) code=1.
load adi modules
Loading AES Device Drivers:
load_adi: enter (0x4ABB254, 0x4ABB154, moose_w.adi)
load_adi: return 0
load_adi: enter (0x4AB9254, 0x4AB9154, moose.adi)
load_adi: return 0
adi_load: done
Creating XaAES kernel thread
AESSYS:Installed 'nAES' cookie in readable memory at 122E000
apid=-1,P_handle=0
k_init: videomode=0
nvdi version = 503
could not determine fvdi version
k_init:vdo=0 vm=0 video=0
Default screenmode
Screenmode is: 1
k_init: v_opnwk() mode=1
k_init: v_opnwk() handle=2
Physical work station opened: 2
Virtual work station opened: 3
lookup-support:0, planes:16
16 bit pixel E0FF is intel format
Video info: width(1024/768), planes :16, colours 256 pixel-format 1
loading palette:'u:\c\MINT\1-19-B43\XAAES\pal/nvdi.pal'
stdfont: id = 1, size = 10, cw=8, ch=16, dev=0
smlfont: id = 1, size = 8, cw=6, ch=6, dev=0
Display Device: Phys_handle=2, Virt_handle=3
 size=[1024,768], colours=256, bitplanes=16
Loading system resource file 'xaaes016.rsc'
xaaes_sysfile: check if 'u:\c\MINT\1-19-B43\XAAES\xaaes016.rsc' exists - return = 0
system resource = 4A9C004 (u:\c\MINT\1-19-B43\XAAES\xaaes016.rsc)
xaaes_sysfile: check if 'u:\c\MINT\1-19-B43\XAAES\xa_xtobj.rsc' exists - return = 0
xaaes_sysfile: check if 'u:\c\MINT\1-19-B43\XAAES\widgets\magicwdg.rsc' exists - return = 0
do_bkg_img:u:\c\MINT\1-19-B43\XAAES\1024768.16/xa_form.mfd not found
AESSYS:read_inf:u:\c\MINT\1-19-B43\XAAES\xaaes.inf
alert:6, KBD:7,pferr=0
No wheel support
Using moose adi
Loading AES modules...
loading accs ---------------------------
loading accessories from 'c:\'
load_accs: launch (c:\zcontrol.acc)
loading shell and autorun ---------------
autorun[1]: cmd=(4B64878) 'u:\c\mint\1-19-b43\sysroot\gem\toswin2\toswin2.app'
   args[1]:    =(4B607A8) ''
autorun[0]: cmd=(4B64918) 'u:\c\mint\1-19-cur\xaaes\xaaesnap\xaaesnap.prg'
   args[0]:    =(4B60778) ''
Launch shell 'u:\c\teradesk\desktop.prg' with args 'No args'
cpuinfo:CPU:68030 MMU:68030 FPU:68882 Clocking:49.3MHz BogoMIPS:12.33 Calibration:6169600 loops
MEMPROT:OFF, Stack: 444
version:FreeMiNT version 1.19 (gcc version 4.6.4 (MiNT 20170417) (GCC)) #1 Sat Oct 06 17:43:22 UTC 2018
buildinfo:CFLAGS:-m68030 -fgnu89-inline -Werror -mshort -g -O2 -fomit-frame-pointer CDEFS:-D__KERNEL__ -DLANG_ENGLISH -DVERBOSE_BOOT -DWITH_MMU_SUPPORT -DWITH_SINGLE_TASK_SUPPORT -DCRYPTO_CODE -DSOFT_UNITABLE -DBUILTIN_SHELL -DM68030
08:50:05: pid 11 (desktop): ADDRESS ERROR: User PC=15AA02E, Address: 0 (basepage=158A000, text=158A100, data=15AABC2, bss=15AC746)
XaSYS(5:AES:3): sigterm received
(ignored)
AESSYS(3:AES:3): sigterm received
(ignored)

- INIT=/bin/bash

c/mint/1-19-b43/xaaes/xaloader.prg

... it comes the same loading errror.

**Comment by franklukas** [comment]
jinnee are working. Except the editobjc.slb error at startup ...

But I want to use teradesk ...

**Comment by ctzio** [comment]
Does teradesk work in TOS? It could be something as simple as a corrupt 
executable.


Στις 24/10/2018 10:03 πμ, ο franklukas έγραψε:

**Comment by mikrosk** [comment]
Indeed. There is virtually zero reasons why Teradesk should refuse on the PAK working while Jinnee wouldn't.

I guess you made sure that you are not using ColdFire binary. :)

**Comment by mikrosk** [comment]
Looking more closely, this is really a crash in (and within) Teradesk, it is accessing a null pointer. But why that works when launched from "Launch Program" is hard to explain.

**Comment by franklukas** [comment]
Teradesk works fine with SingleTOS ...

Thing 1.29 is working too.

**Comment by mikrosk** [comment]
@franklukas Teradesk 4.07, right?

**Comment by ctzio** [comment]
Ok, this seems strange (from your logs)

 > c/mint/1-19-b43/xaaes/xaloader.prg

is after the attempt to load desktop..

Anyway, assuming i read that wrong, Teradesk can also crash due to bad 
configuration files. Can you remove .inf and .pal and try again?


Στις 24/10/2018 10:41 πμ, ο franklukas έγραψε:

**Comment by mikrosk** [comment]
Actually, isn't possible this is your problem:

> load_accs: launch (c:\zcontrol.acc)

Try to boot only clean C: (no ACCs, only NVDI.PRG in AUTO).

**Comment by franklukas** [comment]
Without any ACC and Autofolder program the error is the same. Except in the Autofolder the Nova Driver, xboot and P2INT for the Panther/2 ISA Adapter with a MACH32 and NE2000 Ethernet card. Without P2INT the Panther Adapter do not work! 

When I boot without the Panther/2 Adapter and no Auto and ACC programs under ST-High 640x400 the same error show up.

**Comment by franklukas** [comment]
I found the fault ...

XBOOT is the cause. Without XBOOT all is fine ...

**Comment by mikrosk** [comment]
That's odd. As CT2 (similar CPU/FPU + Fast RAM) has troubles with XBOOT too, maybe you can try to disable TT RAM bits on its .PRG? (i.e. keep only the fast load bit set)

I'm not too confident it will help but it's worth a shot anyway.

**Comment by franklukas** [comment]
Thanks ...

I can live without it !

**Comment by mikrosk** [comment]
Well, another happy FreeMiNT user then. :-)
