### ISSUE TITLE
USB keyboard driver - Keypad ) and ( now inaccessible

### ISSUE THREAD

**Issue by czietz** [freemint/freemint#104]
I see that the USB keyboard driver has been modified to emulate Shift+Arrow up/down when PageUp/PageDown is pressed: https://github.com/freemint/freemint/blob/e4e965fc4e996daff2f1c4a6d1b686057f67adab/sys/usb/src.km/udd/keyboard/usb_keyboard.c#L257
While this is generally a nice idea, it makes the keypad `)` and `(` keys inaccessible from a USB keyboard. Those were previously mapped on PageUp/PageDown. 

Given that there are not that many unmapped keys left on the PC keyboard and given their relative proximity to the keypad, the only idea I would have is mapping the round brackets to keys like PrintScreen and Pause. What do you think?

**Comment by Perdrix24** [comment]
Yes, I follow this section, I even have email notifications.

The current mapping of the Page Up and Page Down keys is in line with Eiffel and is logical. But yes, you can modify to use Print Screen/Pause for ( ) .

On this subject, CKBD seems to work well in loading keyboard tables, for example I loaded a French keyboard table and I have an AZERTY layout. Not sure if all the keys on a USB keyboard would match though. I loaded the German keyboard, and the ( ) keys can be obtained with Shift 8 and Shift 9 using a US keyboard.

In addition, CKBD has a mouse accelerator that can actually slow down the mouse, useful on lower resolution systems.

**Comment by czietz** [comment]
Please find a patch attached that maps `PrintScr `-> KP `(` and `Pause` -> KP `)`.
[kbd.patch.txt](https://github.com/freemint/freemint/files/2818535/kbd.patch.txt)

**Comment by DavidGZ** [comment]
Committed.

Thanks for the patch!
