### ISSUE TITLE
USB.PRG (TOS driver): Cookie jar not resized if already full

### ISSUE THREAD

**Issue by czietz** [freemint/freemint#105]
I just finished debugging an issue reported by a Lightning VME user, where USB.PRG would seemingly install without error, but all subsequently run programs would complain about a missing _USB cookie.

The reason was a full cookie jar that prevented the installation of the _USB cookie by USB.PRG. Imho, the program should at least issue an error message in such as case, telling the user to run programs such as JARxxx.PRG to create a bigger jar.

**Comment by czietz** [comment]
I was thinking of something like in the attached patch.

[setcookie.patch.txt](https://github.com/freemint/freemint/files/2800319/setcookie.patch.txt)

**Comment by DavidGZ** [comment]
Thanks for reporting this problem and for the patch, I'll apply it in the coming days.

**Comment by DavidGZ** [comment]
Patch applied. Thanks again!

**Comment by Perdrix24** [comment]
Good!
