### ISSUE TITLE
TCP/IP on 68000

### ISSUE THREAD

**Issue by mikrosk** [freemint/freemint#108]
There seems to be an issue with 68000 kernel: http://www.atari-forum.com/viewtopic.php?f=15&t=33189&p=343103#p343508. @DavidGZ looked into it in the past but it's still there, as per: http://atari-forum.com/viewtopic.php?f=28&t=36549&p=371493#p371448

As the user reports, it used to work back in February 2016.

**Comment by DavidGZ** [comment]
I stumbled with this problem but I didn't really look into it, I don't have a 68000 machine to investigate this further.

**Comment by mikrosk** [comment]
According to latest development in that thread it's quite confusing. First it seemed to be caused by an IDE interface attached (or its driver), then it started to work out of the blue. Maybe just a configuration issue.

**Comment by DavidGZ** [comment]
This means that my assumption about being the same problem that I hit the last year was false.

**Comment by mikrosk** [comment]
Anyhow, it works for him, so issue solved. ;-) If/when somebody reports something close to your observation, he can report it.
