### ISSUE TITLE
distclean inadvertently removes rtl8139.c

### ISSUE THREAD

**Issue by mfro0** [freemint/freemint#111]
`make distclean` removes `rtl8139.c` (a registered source) because it was added to the `SGENFILES` variable (by mistake?).
`SGENFILES` should only contain the list of generated files that are supposed to be wiped on a clean.

Fixed by removing rtl8139.c from that list with 7bbdc647

(posted this because I *wanted* to own repdigit - "Schnapszahl" - #111)

**Comment by mikrosk** [comment]
No idea what I was thinking. Fixed, therefore closing. Thanks!
