### ISSUE TITLE
find latest libcmini release

### ISSUE THREAD

**Issue by mfro0** [freemint/freemint#112]
@mikrosk : With #110, I have seen that the latest libcmini release appears to be hardcoded in the scripts for the travis builds.

I *think* this could be automated using the github REST API. If you always want the download link to the latest release, the following should do it:

`curl -s https://api.github.com/repos/mfro0/libcmini/releases/latest | grep browser_download_url | awk '{print $2}'`

This should return the download link to the latest release tarball.

If you have `jq` ("JSON query") installed, you can replace the (potentially fragile) shell trickery with:

`curl -s https://api.github.com/repos/mfro0/libcmini/releases/latest | jq -r '.assets[].browser_download_url'`

Didn't dare to touch any of the scripts myself because I'm afraid I would break them ;)

**Comment by mikrosk** [comment]
Thanks for the neat trick, Markus. I have added it to the scripts: https://github.com/freemint/travis-scripts/commit/ac22eb1170f18fbce63919a87b375c7338d21169
