### ISSUE TITLE
Devconnect() returns error with memory protection enabled on CT60

### ISSUE THREAD

**Issue by mikrosk** [freemint/freemint#113]
While trying to keep my code as system friendly as possible I have discovered that Devconnect() behaves in a really odd way: https://github.com/atari800/atari800/blob/master/src/falcon/sound.c#L237

Same setup, hardware, everything - the only difference is MP enabled or not. Tested on CT60 + latest FreeMiNT but IIRC, it behaves the same on aranym-mmu + set_mmu + EmuTOS + FreeMiNT.

**Comment by th-otto** [comment]
If i understand the code in mint correctly, devconnect is not handled in any way by the kernel (the xbios vector table isn't even large enough for it). So all it does it save some registers, restores them again  and then jump to the xbios function. I can't see any difference there for MP. Maybe the CT60 bios just tests whether MMU is in use?

PS.: yes, registers are restored *before* calling the old xbios function. Don't ask me why.

**Comment by mikrosk** [comment]
Are you sure about that EmuTOS statement? The same code works nice on Aranym and I doubt it's Aranym+EmuTOS which provides the function.

**Comment by mikrosk** [comment]
I can reply myself: https://github.com/emutos/emutos/blob/master/bios/dmasound.c#L583 -- so yes, EmuTOS does provide it, too.

**Comment by th-otto** [comment]
Oops. Should check the sources first. Had something in mind that this was still missing.

And no, Aranym does not hack the XBIOS. It only provides a natfeat interface for MgSn compatible sound interface, but that's something different.

**Comment by mikrosk** [comment]
So my memory has failed me - it works perfectly on MP+030, MP+Aranym+EmuTOS, the only case where it does _not_ work is CT60. I looked into the [sources](https://github.com/mikrosk/ct60tos/tree/master/flash.tos/src/ct60tos), can't see anything done for Devconnect at all, so it remains mystery.

**Comment by th-otto** [comment]
Difficult to tell. I thought that ct60tos was a complete replacement, but when i look at the sources, it more looks like extending/patching the existing TOS. What return code do you get from the call to Devconnect()?

**Comment by mikrosk** [comment]
Good idea - for some reason I have never checked it! It's... 0x15C0000. It nearly looks like the upper word is trashed / not set somewhere.

**Comment by mikrosk** [comment]
Btw, this is quite interesting. Every documentation I have states, that `Devconnect` is supposed to return 0 if succesfull and yet its implementation looks like:
```
    6504:       302f 0004       movew %sp@(4),%d0
    6508:       6b00 0018       bmiw 0x6522
    650c:       b07c 0003       cmpw #3,%d0
    6510:       6e00 0010       bgtw 0x6522
    6514:       e540            aslw #2,%d0
    6516:       41f9 00e4 ae0a  lea 0xe4ae0a,%a0
    651c:       2070 0000       moveal %a0@(0000000000000000,%d0:w),%a0
    6520:       4ed0            jmp %a0@
    6522:       4280            clrl %d0
    6524:       4e75            rts
```
Also present in the leaked sources:

```
devconnect:
        move.w  devc_src(sp),d0
        bmi     .error
        cmp.w   #3,d0
        bgt     .error
        asl.w   #2,d0
        lea     devoperation,a0
        move.l  (a0,d0),a0
        jmp     (a0)

.error:
        clr.l   d0              ; Returns complete as per L.T.
        rts 
```
Actually, Falcon030 Developer Doc states it returns "0 - No error", what would match the code we see. In any way, that upper 16-bit must be smudged by FreeMiNT somehow.

**Comment by mikrosk** [comment]
Anyways, not a FreeMiNT bug for sure.

**Comment by th-otto** [comment]
You are right. If i did not miss anything, the function (for dmaplay at least) ends with:

[00e066b2] 302f 0004                 move.w    4(a7),d0
[00e066b6] e140                      asl.w     #8,d0
[00e066b8] eb40                      asl.w     #5,d0
[00e066ba] c47c 0fff                 and.w     #$0FFF,d2
[00e066be] 8440                      or.w      d0,d2
[00e066c0] 33c2 00ff 8932            move.w    d2,$00FF8932
[00e066c6] 4e75                      rts       

and the upper half of d0 is not touched anywhere.
