### ISSUE TITLE
Floppy drive formatting allowed while a file in the floppy disk is opened by a process

### ISSUE THREAD

**Issue by DavidGZ** [freemint/freemint#119]
If I open a file in the floppy drive, for example a text file with QED and while the file is still opened I try to format the floppy disk, the device is not locked and the formatting is allowed. It seems that the file descriptor isn't added to the the list of opened file for the process.
This can be seen in /kern/PID/fd/. Open QED, check its PID with "ps", see which files descriptors are in /kern/PID/fd/, then open new text file with QED and refresh contents in directory. Shouldn't be the new file descriptor added?

**Comment by mikrosk** [comment]
Maybe I'm totally wrong here but are you sure Qed keeps the file open? I would imagine it opens it, do whatever read/write operation is requested and close it until you change its content again.

**Comment by DavidGZ** [comment]
Oops....you're right. Sorry for the "false alarm".
