### ISSUE TITLE
tosdelay.c causes crash when serial port is used

### ISSUE THREAD

**Issue by czietz** [freemint/freemint#121]
Today, I was finally able to pinpoint a strange crash reported by a Lightning USB user. It turned out that the root cause is within the FreeMiNT USB stack! Or, more precisely, the TOS part of it.

The delay calibration routine in tosdelay.c ends up unconditionally enabling the MFP's Timer D interrupt: https://github.com/freemint/freemint/blob/748cbcbd1b39b09b96b16bb58fda206fb744cc26/sys/usb/src.km/tosdelay.c#L91 However, the timer D interrupt is not used by TOS and, therefore, no interrupt handler is installed. Timer D is disabled after the calibration: https://github.com/freemint/freemint/blob/748cbcbd1b39b09b96b16bb58fda206fb744cc26/sys/usb/src.km/tos-common/delayasm.S#L75 ... so this does not cause an immediate problem.

But later on when a program starts timer D ‒ without the intention of using the corresponding interrupt, i.e., without installing a handler of its own ‒, the enabled interrupt will trigger and it'll crash the system. Recall that timer D is used as baudrate generator for the serial port, so _any_ program using the serial port can cause this crash!

The quick fix would be to _disable_ the timer D interrupt in tosdelay.c instead of enabling it. This will prevent the crash. However, it would interfere, if a program actually enabling timer D interrupt was run before the USB programs. Thus, it would be better to save the state of the interrupt (disabled or enabled) and restore it. Unfortunately, as far as I know, there is no XBIOS function to query the state of a MFP interrupt, so this needs to be done by direct HW register access.

**Comment by czietz** [comment]
Two more notes:
1. EmuTOS, where the code was taken from, does precisely what I wrote above: _disabling_ the interrupts: https://github.com/emutos/emutos/blob/840026fad8da12e7d03843e5f1fe70945b3af839/bios/delay.c#L104
(However, EmuTOS of course can be sure that nothing was run that would have enabled the timer D interrupt.) 
2. As it is done right now, run_calibration will interfere with programs that already set up the MFP serial port, anyway, because it does not restore the timer D settings. Thus, programs that configure the serial port must be run after the USB programs in any case, and we could get away with unconditionally disabling the interrupt, as well.

**Comment by DavidGZ** [comment]
Thanks for the detailed report. I'll look at it during the next days.

**Comment by Perdrix24** [comment]
Perhaps it has to do with what I haven't done yet:

https://github.com/freemint/freemint/blob/748cbcbd1b39b09b96b16bb58fda206fb744cc26/sys/usb/src.km/tosdelay.c#L98

**Comment by DavidGZ** [comment]
> Perhaps it has to do with what I haven't done yet:

Yes, it is.

Another option would be to use the code that uses the kernel to calculate the loop counts which doesn't use the timers at all. Probably not that accurate but it's good enough. Claude if you like the idea I can try to integrate the code in the TOS drivers.

**Comment by czietz** [comment]
Even after saving and restoring the serial settings, the timer D interrupt must not be enabled. Or rather: it must only be enabled if it was enabled before running the delay calibration. It is disabled by default (under Atari TOS and EmuTOS) and no handler is provided. Therefore, enabling the interrupt under these circumstances will lead to the crash mentioned above.

**Comment by Perdrix24** [comment]
> Another option would be to use the code that uses the kernel to calculate the loop counts which doesn't use the timers at all. Probably not that accurate but it's good enough. Claude if you like the idea I can try to integrate the code in the TOS drivers.

Yes, it sounds like a good solution. And as Christian pointed out, the current system likely can't be fixed to work around this issue.

**Comment by DavidGZ** [comment]
>Yes, it sounds like a good solution. And as Christian pointed out, the current system likely can't be fixed to work around this issue.

If I understood Christian correctly it's possible to fix this but we must save and restore the state of the timer D and the serial port. In any case I'm going to see how easy is to integrate the delay calculation code from the kernel.

**Comment by Perdrix24** [comment]
> If I understood Christian correctly it's possible to fix this but we must save and restore the state of the timer D and the serial port. In any case I'm going to see how easy is to integrate the delay calculation code from the kernel.

Hold on a little, I'll try to save the state of the timer D with help from a friend :)

**Comment by Perdrix24** [comment]
I have a solution to test. How can I reproduce the crash? Running sting.prg before usb.prg, with serial.cpx?

**Comment by czietz** [comment]
My test setup consisted of USB.PRG and STORAGE.PRG -- which both use tosdelay.c --, XCONTROL.ACC and SERIAL.CPX. STinG was not needed.

**Comment by DavidGZ** [comment]
Fixed with commit 9f6329ff04d0861ad49da1421c31b15c7ec2b486
