### ISSUE TITLE
Error with gcc 9.1: taking address of packed member of 'struct usb_config' may result in an unaligned pointer value 

### ISSUE THREAD

**Issue by th-otto** [freemint/freemint#123]
Since gcc 9.1 i get compile errors (actually warnings, but turned into errors by -Werrors):

asix.c: In function 'asix_eth_probe':
asix.c:816:10: error: taking address of packed member of 'struct usb_config' may result in an unaligned pointer value [-Werror=address-of-packed-member]
  816 |  iface = &dev->config.if_desc[ifnum];
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~

(just an example, there are more of this kind)

struct usb_config is defined in https://github.com/freemint/freemint/blob/64c7c0b4613c11c12396602083e6048f3ea1a851/sys/usb/src.km/usb.h#L164-L169

That code is also compiled for plain 68k, so gcc is actually right about that. I don't  know much about USB, but i guess the layout of the structures is defined by the USB standard? Is there some way to define them in such a way that we don't access odd addresses?

**Comment by DavidGZ** [comment]
Yes, you guessed well, the descriptors structures are defined by the USB standard, but that structure (usb_config) is something internal to us, so I think the packed attribute could be removed, but I'm not 100% sure because I don't know why it was added in the first place. Let me look into it.

One question, a char struct member in an odd address wouldn't trigger that warning, right?

**Comment by th-otto** [comment]
I don'.t think so. But that message above was only the first one, i've have craete a file with all of them now by running "make -k" and ignoring the errors.

[errs.txt](https://github.com/freemint/freemint/files/3316701/errs.txt)

**Comment by vinriviere** [comment]
> but that structure (usb_config) is something internal to us, so I think the packed attribute could be removed,

`__attribute__ ((packed))` is a poison which should never be used. Basically, it assumes that any field in the structure may be aligned on odd address. Thus **all** access to structure data is performed using move.b on 68000 (never with move.w or move.l). This of course causes bad performance, and maybe even unexpected behaviour if used directly on hardware registers.

**Comment by th-otto** [comment]
I agree, but most of the time (when the structure members must be a certain offsets), the only alternative is to define all members in terms of char arrays, and then you also have to access them byte for byte, even on machines where that would not be needed.

**Comment by DavidGZ** [comment]
Thanks for the file! I see that there are 2 troublesome structures,  usb_config we've already discussed about and the structure hc_or inside the structure ehci
https://github.com/freemint/freemint/blob/64c7c0b4613c11c12396602083e6048f3ea1a851/sys/usb/src.km/ucd/ehci/ehci.h#L60-L97
https://github.com/freemint/freemint/blob/64c7c0b4613c11c12396602083e6048f3ea1a851/sys/usb/src.km/ucd/ehci/ehci.h#L180-L185

At first glance I don't see anything problematic in the second case, hc_or structure is used to access  the registers in an ehci chip, all members are longs, I'll need to look deeper.

**Comment by DavidGZ** [comment]
For the usb_config structure we can remove the packed attribute safely, I've seen in the u-boot sources that it's a legacy from the times when the configuration descriptor fields were members of that structure, now they still are but through the structure usb_config_descriptor that has its own packed attribute. I have tested the compilation after removing that attribute and the warnings are gone.

After this change new compiled USB drivers and the usbtool accessory will be incompatible with the old compiled versions of them, we must upgrade the USB API version to avoid conflicts while trying to load mixed versions of them.

**Comment by DavidGZ** [comment]
I really don't know how to silent the warnings for the hc_or structure, I think inside the structure everything is in order. hc_or address in memory is relative to the hc_cr structure that is another structure for the ehci chip registers, the hc_cr structure address is given to us by the PCI-BIOS as a resource of the PCI card, this hardware address is supposed to be even aligned. As far as I can see everything is correct.

**Comment by th-otto** [comment]
Do you mean struct ehci_hcor in ehci.h? That looks like all members are unsigned long, so wouldn't it be safe to just remove the packed attribute, without causing an actual change of the structure?

**Comment by th-otto** [comment]
BTW, in your recent commits i saw that you moved some files around. After a "git pull", i now have lots of "untracked files" in sys/usb/src.km/udd. How did that happen?

**Comment by DavidGZ** [comment]
>Do you mean struct ehci_hcor in ehci.h? That looks like all members are unsigned long, so wouldn't it be safe to just remove the packed attribute, without causing an actual change of the structure?

Yes, that structure. I've thought about removing the package attribute too, I agree in this case it would be safe, also because that structure is not supposed to change anymore.

**Comment by DavidGZ** [comment]
>BTW, in your recent commits i saw that you moved some files around. After a "git pull", i now have lots of "untracked files" in sys/usb/src.km/udd. How did that happen?

We have added a new mouse driver which uses some common code that could be used by new HID device drivers, so we have move all the HID drivers to its own "hid" directory.

**Comment by th-otto** [comment]
ok, a few test show that we still have to watch out for layout changes:
in the following example, offsetof(struct container, y) is 2:
```
struct normal_struct {
	unsigned long a;
	unsigned long b;
};

struct container {
	char x;
	struct normal_struct y;
};
```

but in this example, offsetof(struct container, y) is 1:

```
struct packed_struct {
	unsigned long a;
	unsigned long b;
} __attribute__((packed));

struct container {
	char x;
	struct packed_struct y;
};
```

So even if the packed struct itself is perfectly aligned, when embedded in another struct, the packed attribute strikes. I guess this is the reason why GCC currently complains. So you do not only have to look how the structure is defined, but also where elsewhere it is used :(

**Comment by DavidGZ** [comment]
As far as I could see ehci_hcor is only embedded in another structure as a pointer (see ehci structure) so it shouldn't be a problem. I'll check that this is actually true.

**Comment by DavidGZ** [comment]
I confirm that is only embedded in the ehci structure as a pointer, and removing the packed attribute in ehci_hcor silents the warnings. I don't understand why the structure ehci_hcor triggers the warnings and ehci_hccr doesn't, I'd leave the package attribute in the ehci_hccr structure although it looks inconsistent with the removal in the ehci_hcor structure. In ehci_hccr there is an 8 char array that I'm not sure how the compiler will handle it without the package attribute. 

https://github.com/freemint/freemint/blob/97702c8654d7cd9ac78c530ea0f0760fedec7df7/sys/usb/src.km/ucd/ehci/ehci.h#L48-L58

**Comment by th-otto** [comment]
You can easily check how the compiler creates the structure by using something similar i posted above:
```
#include <stddef.h>

struct packed_struct {
        unsigned long a;
        unsigned long b;
} __attribute__((packed));

struct container {
        char x;
        struct packed_struct y;
};

int a = offsetof(struct container, y);
```
Then doing m68k-atari-mint-gcc -S -o - foo.c
will output:
```
#NO_APP
        .text
        .globl  _a
        .data
        .even
_a:
        .long   1
```

The value after the .long is what matters.

Or you can just use the [compiler explorer](http://brownbot.mooo.com/z/3rUlOi)

**Comment by DavidGZ** [comment]
Thanks a lot for the tip, I'll check it for my own curiosity, but although I could confirm that the compiler handles this structure in the way we want, what about future compilers versions? Could this change?
As long as there is no warnings I'm for leaving the packed attribute in ehci_hccr.

**Comment by th-otto** [comment]
The layout is unlikely to change. On systems with shared libraries, that would produce incompatible code. You can also verify that on the compiler explorer page, there are several compiler versions available.

**Comment by DavidGZ** [comment]
At the end I have "backported" this commit from the u-boot sources. This has silenced the warning.
https://github.com/u-boot/u-boot/commit/69716c1900274a89bd5cbd1b0bb276ceaaa04f61#diff-7bb2c47593cbdd1a7c034ca18987335c

**Comment by th-otto** [comment]
Very good. The only remaining warnings are now:

```
../hidparse.c: In function 'hid_print_usage_type':
../hidparse.c:410:10: error: array subscript 116 is above array bounds of 'const char[30][64]' [-Werror=array-bounds]
  410 |   return usage_type_str[type - 24];
      |          ^~~~~~~~~~~~~~
../hidparse.c:380:12: note: while referencing 'usage_type_str'
  380 | const char usage_type_str[][64] = {
      |            ^~~~~~~~~~~~~~
../hidparse.c: In function 'hid_print_usage':
../hidparse.c:453:12: error: array subscript 34 is above array bounds of 'const char[30][64]' [-Werror=array-bounds]
  453 |     return usage_type_str[type - 39 - 55]; /* may be off by a few */
      |            ^~~~~~~~~~~~~~
../hidparse.c:380:12: note: while referencing 'usage_type_str'
  380 | const char usage_type_str[][64] = {
      |            ^~~~~~~~~~~~~~
```

Could you have a look at them, too? They look rather suspicious.

And occasionally, i get link errors with unresolved external to strlen etc. when building usbtool.acc.

**Comment by DavidGZ** [comment]
OK, I'll take a look at them as soon as I finish with what I'm doing now

**Comment by DavidGZ** [comment]
> Very good. The only remaining warnings are now:
> 
> ```
> ../hidparse.c: In function 'hid_print_usage_type':
> ../hidparse.c:410:10: error: array subscript 116 is above array bounds of 'const char[30][64]' [-Werror=array-bounds]
>   410 |   return usage_type_str[type - 24];
>       |          ^~~~~~~~~~~~~~
> ../hidparse.c:380:12: note: while referencing 'usage_type_str'
>   380 | const char usage_type_str[][64] = {
>       |            ^~~~~~~~~~~~~~
> ../hidparse.c: In function 'hid_print_usage':
> ../hidparse.c:453:12: error: array subscript 34 is above array bounds of 'const char[30][64]' [-Werror=array-bounds]
>   453 |     return usage_type_str[type - 39 - 55]; /* may be off by a few */
>       |            ^~~~~~~~~~~~~~
> ../hidparse.c:380:12: note: while referencing 'usage_type_str'
>   380 | const char usage_type_str[][64] = {
>       |            ^~~~~~~~~~~~~~
> ```
> 

Thorsten, those warnings are gone now.

> 
> And occasionally, i get link errors with unresolved external to strlen etc. when building usbtool.acc.

I don't get these errors with gcc 9.1. What exactly means occasionally? Is there any way I can replicate them?

**Comment by th-otto** [comment]
I first though it was only when using parallel makes, but i think this just always happens.

However, i currently cannot test it. I pulled your recent changes to the Makefiles, and now some native binaries (like genmagic) are compiled with -mshort ... needless to say that the native compiler does not understand that flag.

**Comment by DavidGZ** [comment]
Thorsten, can we close this issue?

**Comment by th-otto** [comment]
Yes ;)
