### ISSUE TITLE
hidparse.h should not contain #pragma pack(1)

### ISSUE THREAD

**Issue by czietz** [freemint/freemint#125]
hidparse.h accidentally contains...
https://github.com/freemint/freemint/blob/5a5a960859f3a9d0a33f280e0c69a31770b16f0c/sys/usb/src.km/udd/hid/hid-common/hidparse.h#L26
... because it was reused from an architecture without strict alignment requirements.

This #pragma pack(1) causes all structure to be packed, which can be problematic on the 68000. The compiler knows this and generally generates suitable but slow code, i.e., it accesses ints and longs byte by byte. This finding was discovered by accident by a Lightning user, however. That user was running an older kernel which still contained this bug: https://github.com/freemint/freemint/issues/99. Therefore, he saw a crash because of the misaligned structure members as soon as memset was called.

**Comment by DavidGZ** [comment]
Thanks a lot for the report!

It's fixed now with commit d11071ba21a6c6bb0f3f39c221fca8f915022646
