### ISSUE TITLE
XaAES forces the current directory for programs to be the path of the program executable.

### ISSUE THREAD

**Issue by th-otto** [freemint/freemint#126]
Just encountered something what i would call bug: in https://github.com/freemint/freemint/blob/0e1d454c4bc902dc82b1715118f3c97960dbdab7/xaaes/src.km/xa_appl.c#L432-L440 XaAES seems to set the current directory to the path of the executable in the appl_init() call. That totally nullifies any attempt of the desktop to use eg. the path of the topmost directory window instead, which even works in SingleTOS. Does anybody know why this is enforced? Specifically, i can't see any reason why this is only done when proc->domain == 0

**Comment by th-otto** [comment]
It was introduced by 9fd8af691bb3fb86505c3d55bf1da089082eb661

**Comment by DavidGZ** [comment]
> It was introduced by [9fd8af6](https://github.com/freemint/freemint/commit/9fd8af691bb3fb86505c3d55bf1da089082eb661)

What a mess :-)

In Helmut's branch the change was done here:
https://github.com/freemint/freemint/commit/edf3c76a652467a3a5569fbdd1117c8b70f00d58#diff-b773cd2202d5199c18a738a20dcb8b3e

There is a good explanation of the commit, may be in the context of the change you can figure out why it was done

**Comment by th-otto** [comment]
The commit in Helmut's branch is about single-task mode. I still can't see any reason to change the apps directory. Simple example where the bug manifests: an app is started via extended shel_write modes, setting the defdir member of SHELW to some directory. That causes create_process() in MiNT to set the directory. But then appl_init() sets it back.

**Comment by mikrosk** [comment]
I may be wrong but maybe the idea was that if domain == 0 ("In this domain all system calls behave exactly as under normal TOS"), it would imply the single task mode?

**Comment by th-otto** [comment]
But what does single-task mode has to do with the startup directory? And it does not behave like TOS in this case, there you have the option in the desktop to set the current directory to that of the window. This is important if you have registered an application for certain file extensions, and start it by double-clicking on such a file.

**Comment by mikrosk** [comment]
Good question. @zabruder is perhaps the only one who knows the answer.

**Comment by zabruder** [comment]
Am 28.07.2019, 10:37 Uhr, schrieb Miro Kropáček:

> Good question. @zabruder is perhaps the only one who knows the answer.

Maybe because most traditional TOS-Programs (DOM=0) have their cfg, rsc,  
etc. beneath their binary.

If the desktop expects a program to handle a file or directory from a  
window: why does it not send the full path of that file or directory to  
the program?

Don't really remember why I did it. Feel free to change it instead of  
complaining.

**Comment by th-otto** [comment]
Most programs have their rsc file in their directory yes, but that's also true for programs that call Pdomain(1).  Beside that, rsrc_load()/shel_find() will also look in the program path, regardless of the current working directory.

>why does it not send the full path of that file or directory to the program?

Whats that got to do with it? There was a reason why the desktop of 2.06 (and all desktops that i know of)  made that configurable. And in the concrete example which exposed the bug: it was the interpreter of GBE that was executed, trying to set the current directory to the path of the GFA file that was interpreted. But your change in appl_init() set it back to the directory of the interpreter, causing rsrc_load() in the program to fail.

>Feel free to change it instead of complaining.

You see, that's what i call a regression.Strangely nobody noticed it until now. Maybe there are not that many programs that are mint-aware but don't call Pdomain(1) (or maybe after the appl_init() call), which would prevent that behaviour.

**Comment by zabruder** [comment]
Am 30.07.2019, 02:59 Uhr, schrieb Thorsten Otto:

> Most programs have their rsc file in their directory yes, but that's  
> also true for programs that call Pdomain(1).  Beside that,  
> rsrc_load()/shel_find() will also look in the program path, regardless  
> of the current working directory.

Many programs do not use shel_find/rsc_load.

>> why does it not send the full path of that file or directory to the  
>> program?
>
> Whats that got to do with it? There was a reason why the desktop of 2.06

The program would find the file.

> (and all desktops that i know of)  made that configurable. And in the  
> concrete example which exposed the bug: it was the interpreter of GBE  
> that was executed, trying to set the current directory to the path of  
> the GFA file that was interpreted. But your change in appl_init() set it  
> back to the directory of the interpreter, causing rsrc_load() in the  
> program to fail.

Does GBE not know where the GFA-file is (see above)?

>> Feel free to change it instead of complaining.
>
> You see, that's what i call a regression.Strangely nobody noticed it  
> until now. Maybe there are not that many programs that are mint-aware  
> but don't call Pdomain(1) (or maybe after the appl_init() call), which  
> would prevent that behaviour.

Again: Just change it!

**Comment by th-otto** [comment]
>Many programs do not use shel_find/rsc_load.

To load the resource? Are you serious? I don't know much programs that load a resource file without rsrc_load().

>The program would find the file.

Please think about it again. It's not about finding the file that was passed as argument. Its about finding other files.

>Does GBE not know where the GFA-file is (see above)?

Apparently you did not understand the problem.

**Comment by zabruder** [comment]
Am 30.07.2019, 07:18 Uhr, schrieb Thorsten Otto:

>> Many programs do not use shel_find/rsc_load.
>
> To load the resource? Are you serious? I don't know much programs that  
> load a resource file without rsrc_load().

For example thing, pure-c (I think), maybe more.

>> The program would find the file.
>
> Please think about it again. It's not about finding the file that was  
> passed as argument. Its about finding other files.

That could be passed by the desktop to the interpreter which sets the  
directory.

>> Does GBE not know where the GFA-file is (see above)?
>
> Apparently you did not understand the problem.

If you do then just fix the bug.

It's many years ago, don't expect me to recall the details.

**Comment by th-otto** [comment]
On Dienstag, 30. Juli 2019 08:36:25 CEST zabruder wrote:
> For example thing

Uses a custom routine to load it, but shel_find() to locate it.

>pure-c (I think)

Does not have a separate resource file.

>That could be passed by the desktop to the interpreter which sets the 
>directory.

You still don't get it. The correct working directory was already set when the 
program started (by using the defdir element of the extended shel_write mode 
in this case). But this is nullified by the code in appl_init().

**Comment by th-otto** [comment]
I've that now with https://github.com/freemint/freemint/commit/9d97fb0b2ca110f83d0087b71a215909759758a5
