### ISSUE TITLE
ozk-enhancements

### ISSUE THREAD

**Issue by th-otto** [freemint/freemint#129]
Just took a look at the ozk-enhancement branch. That branch was once created by Alan with unfinished work from Odd Skancke.

- https://github.com/freemint/freemint/commit/4d9db66ef4ffd5873a189723d51c2fa1bea7705e: Fix-up commit generated by crap-clone. 
  just deletes a copy of a file

- https://github.com/freemint/freemint/commit/3fa8b24c5fdf0d7396c3433fbdc85cea546ad9da: Fix -Werror generated problems
  Seems to be already applied to master branch. Also current master compiles without any warnings for both gcc 4.6.4 and newer gcc

- https://github.com/freemint/freemint/commit/57a3f4df11e846b5dda5feadf178e78e1d322b5a: No new features. Only cleanups to make everything compile under GCC 4.2 
Mostly fixes only whitespace errors, but also has some patches that look wrong to me (eg. in cops/wlib/size_window)

-  https://github.com/freemint/freemint/commit/04ea0564b3c6c636f03d257460f5d075f9657737: No new features. Only cleanups to make everything compile under GCC 4.4.2 
  Mostly whitespace fixes. Warnings already fixed by this other other commits

- https://github.com/freemint/freemint/commit/4732abac426da22fad2049e64c75793300a70ebb: New subfolder xam, intended to contain XaAesModules. 
  Moves some files to a new subfolder, intended to be compiled as separate modules (mostly resolution-change related code). Generally not a bad idea, but unfinished, and would break current build system. Also has to be redone with up-to-date sources.

- https://github.com/freemint/freemint/commit/ef13519bdaa3b0c4a4d0f8281227c974a2cdd29a: Moved XaAES API definition into own files.
  Already applied somewhere else

- https://github.com/freemint/freemint/commit/9e84744fb30ef166ec2850e609df6dfa4962a485: Added some comments. Far from complete, but its a start. 
  Doesn't apply anymore. The macro that was also introduced there seems to be nowhere used.

- https://github.com/freemint/freemint/commit/4a136126b8f6c9b9c9d4224eb296a60b01c11617: Added CONFIGVARS to some build directories. 
  Obsoleted by other changes to build system

- https://github.com/freemint/freemint/commit/30a117f004719d072a2c73eaf0ef726a5dd68b84: READ THE FILE new.txt found in doc/xaaes
  Moves/renames some files. Would break current build and scripts

- https://github.com/freemint/freemint/commit/ec724d8ea731b82973394dbd30ed87fe2e5904bd:
READ THE FILE new.txt found in doc/xaaes! 
  Dito.

- https://github.com/freemint/freemint/commit/a04afc7247bb5b23335ff278521292cb7b190012: Updated .cvsignore files. 
  Obsolete since migration to git

- https://github.com/freemint/freemint/commit/4ea3144272d538f886a0455d2318e35a61bc0e74: Removed file accidentally added to versioncontrol. 
  Dito.

- https://github.com/freemint/freemint/commit/223b3d6a98f7e3a7f6ae227979c708ed4fef4a9e: Updated .cvsignore
  Dito

- https://github.com/freemint/freemint/commit/ccd3ca62e60dda0f0739d6eddcf87e3d702e6fe5: Updated .cvsignore 
  Dito.

- https://github.com/freemint/freemint/commit/4aa4e62c14d1a834ddf6c3581bf19d859d76e096: Remove 4th parameter passed to get_string() - fixes the complete build 
  Already applied somewhere else

- https://github.com/freemint/freemint/commit/e824d86bc0b68361df2fc234da51e40354dcb11a:  Merge freemint-enhancements into ozk-enhancements to reduce diffs to isolated changes.
  Already applied somewhere else

- https://github.com/freemint/freemint/commit/8a79e9e7d5bab7b50d49b553496d15e2004fb53b: change -lgcc16 to -lgcc 
  Obsolete

- https://github.com/freemint/freemint/commit/8dd630879909d762478cd7a970d0267a903bcd61: Disable inline for function as gcc 4.4.3 bleets about inability to. 
  Obsolete

So unless i missed something, i would consider that whole branch obsolete. Except for a lot of whitespace fixes that are scattered around, these should eventually be done by a single, separate commit.

**Comment by mikrosk** [comment]
I guess the same applies to `freemint-enhancements`. I basically kept it for historical reasons but I have no strict opinion about its removal. What others think?

**Comment by DavidGZ** [comment]
Same for me, no strong opinion, but I don't remember what kind of stuff was developed on that branch.

**Comment by mikrosk** [comment]
`freemint-enhancements`, `helmut-enhancements` and `ozk-enhancements` (along with `master`) are now renamed to `zzz-obsolete-*` and protected against pushing as part of the latest force-push. Kept for backward compatibility with github/commit message references.

**Comment by vinriviere** [comment]
@mikrosk Note that it is possible to create **folders** of branches. They are much used in the [GCC repository](https://github.com/gcc-mirror/gcc/branches) for example. It makes more sense than bogus branch names. I.e. you could name your branches `obsolete/freemint-enhancements`, etc.

**Comment by mikrosk** [comment]
Ah, true. But I also wanted to avoid a possible error of someone using the "wrong" master, for instance while using autocompletion when typing its name. But maybe it's not a serious issue (the branch would be still protected). I can rename them, if you like it better.

**Comment by vinriviere** [comment]
There is a confusion. I don't speak about any `master` branch. I just propose to use the name `obsolete/freemint-enhancements` instead of the name `zzz-obsolete-freemint-enhancements`, and so on. This will not change anything regarding to completion. Note that `obsolete` is really a branch folder, not to be confused with a _remote_ name.

**Comment by mikrosk** [comment]
No, no confusion. :) We have a `zzz-obsolete-master` branch, too. That is what I was referring to.

**Comment by vinriviere** [comment]
Ah, ok. BTW, I' not sure that `zzz-obsolete-master` avoids more confusion than `obsolete/master`.  And as the situation may happen again, it may be useful to append a timestamp to the `master` name.
