### ISSUE TITLE
Duplicate documentation files

### ISSUE THREAD

**Issue by th-otto** [freemint/freemint#131]
The doc files for the mfp (liesmich, readme & ports.txt) are copied to several directories in the snapshot builds (st/doc, ste/doc, megast/doc, megaste/doc). I think they should rather go only once to the toplevel doc directory.

**Comment by mikrosk** [comment]
The original idea of those machine folders was that you don't have to care about the others so you are free to delete all other machine directories. Everything else left is supposed to be common for all targets / machines. That goes also for the doc folder.

Lars has had a lot of suggestions how to improve the documentation we package in the snapshots and I really, really have to kick myself to read his emails and make it reality.

I let this open as a reminder for myself to at least write down his suggestion into this task so we can keep track of it.

**Comment by mikrosk** [comment]
> I let this open as a reminder for myself to at least write down his suggestion into this task so we can keep track of it.

I'm in touch with Lars again, so this reminder can be closed. ;)
