### ISSUE TITLE
issue between NVDI as graphiccard driver and XaAES

### ISSUE THREAD

**Issue by franklukas** [freemint/freemint#141]
issue between NVDI as graphiccard driver and XaAES.

NVDI Matgraph TC for Matrix TC1006 and TC1208
NVDI Matgraph CXX for Matrix C32 C110 Cards with Intel GPU
NVDI ET4000

The combination do not work. Alternative N.AES 2.0 with MiNT 1.15 works fine. 

See pictures of the destroyed screen ->   https://forum.atari-home.de/index.php/topic,15756.msg

Bootorder are -> INIT.TOS (Matrix Program), REDIRECT.PRG, NVDI.PRG, SLCT_DEV.PRG, MINT.PRG

**Comment by mikrosk** [comment]
I'm afraid this will require some investigation on your side due to the unusual setup. I'd start with testing the [official versions](https://github.com/freemint/freemint/releases) to somehow isolate the issue as far as possible.

**Comment by franklukas** [comment]
Freemint 1-15 has no XaAES because XaAES is the problem. The Snapshot from 1-19 works with N.AES and the Matrix TC1208 with NVDI as driver. N.AES and the MiNT Kernel 1-19 has a other fault that the keyboard can do no longer any input but that is a other problem. 

Freemint 1-16.1b with XaAES 0.992 there are coming 11 bombs at the message FAT/VFAT/FAT32 filesystem version 1.27. Without memory protection is booting to xaaes with the same fault than at the XaAES 1.6.4 from the 1-19 snapshot 

Freemint 1-17-0 with XaAES 0.999 same fault

Freemint 1-18-0 with XaAES 1.5.5 same fault

I ask Helmut back in these days and he tell something about open up a workstation are not work right with nvdi. The Nova Driver has not such problems with xaaes ...

**Comment by franklukas** [comment]
mint.cnf GEM=ROM and starting XaAES xaloader.prg from there works but that is not good I think ...

**Comment by franklukas** [comment]
Really big crap ...

NVDI are the driver for TSENG ET4000, Matrix CXX for C-32 C110ZV C110 C110Z CoCo MiCo, Matrix TC1006 TC1208 and TC1208E


XaAES need to be revice.

**Comment by franklukas** [comment]
Excuse me

I swap XaAES in my EasyMiNT (SpareMiNT) Setup for N.AES ...

**Comment by czietz** [comment]
I'd guess this is the same situation as referred to here for NVDI/ET4000:
https://github.com/freemint/freemint/blob/master/xaaes/src.km/example.cnf#L126-L132

However, I don't know the history of this comment. Maybe someone does? Imho, the best course of action would be to investigate _why_ XaAES cannot open the physical VDI workstation when NVDI is running with a graphics card. (TOS/EmuTOS can open it.)

**Comment by mikrosk** [comment]
Does this really apply only to ET4000 NVDI? I mean, I'm pretty sure that you @czietz have tried XaAES on your ATI Mach32 card (at least I assume you have one since you had fixed EmuTOS for it) so I'm at loss why ET4000 handling is different in this matter.

**Comment by czietz** [comment]
@mikrosk: Normally, with a Nova adapter (regardless of whether you put an ET4000 or a Mach32 in it) you would use _Nova_ VDI (and not _NVDI_). There's no issue with Nova VDI and XaAES.

However, if you're using a  "non-Nova" graphics card (therefore not supported by Nova VDI) you have to use NVDI. Frank is reporting an issue with XaAES when NVDI is being used as driver for such a third-party graphics card.

**Comment by czietz** [comment]
I debugged this issue -- which according to the comments in example.cnf was unresolved for at least 9 years. **And I found the cause.** I can confirm a working fix with NVDI/ET4000 (tested myself) as well as with NVDI/Matgraph Matrix (tested by Frank). 

What happens: When opening the physical workstation, NVDI tries to load some files from disk needed for the correct settings of the respective graphics card. NVDI loads these files from the _current drive_, expecting it to be the boot drive. However, this drive is always set to U: by `xaloader.prg`:
https://github.com/freemint/freemint/blob/f3ab8fb75bfbf77cbce992d6c4c5ee7e3014eba8/xaaes/src.km/xaloader/xaloader.c#L130

The attached (quick&dirty) patch is verified to be working. It temporarily sets the current drive back to the boot drive. I think it needs some polishing before committing it, but maybe someone else wants to volunteer to do that. I've already spent much time on actually debugging the issue and will probably not have further time for the next few days to work on the patch.

[xaaes_set_bootdrive.txt](https://github.com/freemint/freemint/files/4187578/xaaes_set_bootdrive.txt)

**Comment by mikrosk** [comment]
Great catch, as usual, Christian! I wonder what a proper fix should be here. I guess we want to keep current drive at u:\. I see there is already code checking for NVDI (even for this specific ET4000 hack) so maybe we can just remove the whole ET4000 thing and check for NVDI with more or less the same code you have provided?

**Comment by czietz** [comment]
Yes, I guess the whole `et4000_hack` code could be removed and the temporary drive change before opening the physical workstation could be restricted to cases where NVDI is detected.

**Comment by mikrosk** [comment]
@franklukas when the build for commit 6cd2ac6 finishes, feel free to try this out, just to be sure it still fixes your problem. :)
