### ISSUE TITLE
dhclient missing in bootable builds?

### ISSUE THREAD

**Issue by ragnar76** [freemint/freemint#149]
As the title says, is it missing or not packed by default?

**Comment by mikrosk** [comment]
Well, it's not missing as that we forgot to throw it in. I just try to make the archives as "essential" as possible, so there are only executables from freemint source tree (all of them, like `ifconfig`) + a few really essential tools (`ls`, `ping`, `cp`, ...).

`dhclient` is quite big and complex + it clearly belongs to a FreeMiNT based distribution, not its basic bootable archive.

**Comment by ragnar76** [comment]
> Well, it's not missing as that we forgot to throw it in. I just try to make the archives as "essential" as possible, so there are only executables from freemint source tree (all of them, like `ifconfig`) + a few really essential tools (`ls`, `ping`, `cp`, ...).
well, in ef5 `ping` is missing too ;)

> `dhclient` is quite big and complex + it clearly belongs to a FreeMiNT based distribution, not its basic bootable archive.
Makes sense to me and i'm fine with a static ip too but i'm lazy ;)

**Comment by mikrosk** [comment]
Well, there is VanillaMiNT and AFAIK, it does contain it. So just convince Joska to update the kernel. :)
