### ISSUE TITLE
Shouldn't be xaloader compiled for different CPUs?

### ISSUE THREAD

**Issue by mikrosk** [freemint/freemint#15]
Perhaps I'm missing something but how FireBee users run XaAES? There's a CF kernel/xaaes available, yes, but `xaloader` seems to be compiled for m68000.

**Comment by mfro0** [comment]
one of the reasons why I wrote #12 ...

**Comment by jflemaire** [comment]
I'm almost certain mine is a CF version. Seeing that my XALOADER.PRG is dated 2013 maybe it was the last one released by Joakim and I kept it because the official releases are 68000 only?

**Comment by mikrosk** [comment]
Yeah, I think that must be the case. I don't see `xaloader` compiled for the FB anywhere in Alan's scripts. Same goes for the usbloader as well, btw.

**Comment by vinriviere** [comment]
I provide a [FreeMiNT binary archive fully compiled for ColdFire](http://vincent.riviere.free.fr/soft/m68k-atari-mint/archives/mint/freemint/), including xaloader.prg (using a custom build script). This is a requirement to support EmuTOS for ColdFire, where 68000 binaries are not supported.

Please understand that my binary distribution is just a palliative for the lack of fully ColdFire binaries in official FreeMiNT archives. As soon as that will be officially supported, my distribution will disappear.

**Comment by mikrosk** [comment]
Fixed by the new autobuild system but yes, #12 is the way to go.
