### ISSUE TITLE
Mega STE scc.xdd fault ...

### ISSUE THREAD

**Issue by franklukas** [freemint/freemint#152]
Mega STE latest freemint 1-19-cur build.

With scc.xdd the kernel hang at boot at the message "SCC serial driver version 0.27". When I disable the scc.xdd the machine boots to the desktop.

**Comment by mikrosk** [comment]
Has this worked before? Any chance to try out an older build from https://bintray.com/freemint/freemint/snapshots-cpu ?

**Comment by franklukas** [comment]
The fault is longer exists I think. With a Atari TT the scc.xdd is work fine.

**Comment by franklukas** [comment]
The scc.xdd  from 1-19-249 has also the fault.

**Comment by mikrosk** [comment]
So it works on your TT but doesn't on MegaSTE? There hasn't been a change for a very long time... IIRC, the basic setup worked on my MegaSTE just a few weeks ago, I can retest if you like but I'm more inclined to believe that it is a hardware issue on your side.

**Comment by czietz** [comment]
I can confirm Frank's observation on my MegaSTE: scc.xdd hangs after `MSG_BOOT` and `MSG_GREET`.  There's a potential infinite loop here: https://github.com/freemint/freemint/blob/3e419e86cd67a8f85ec9512149446bb048ae472b/sys/xdd/scc/scc.c#L1103-L1108, if for some unknown reason the status bit isn't set by the SCC as expected.

I find it highly unlikely that Frank's and my MegaSTE would have the same hardware defect.

**Comment by czietz** [comment]
I wonder: Is it perhaps problematic that scc.xdd is built for 68020-60 **even in the 68000 build**: https://travis-ci.org/freemint/freemint/jobs/659786944#L2783

**Comment by mikrosk** [comment]
@czietz I was literally thinking the same but I thought "nah, too improbable" and didn't bother to look. So thanks again for bothering to do so. :)

@th-otto can you take a look what's wrong?

**Comment by czietz** [comment]
@mikrosk : As far as I can see, there's simply no build infrastructure (Makefiles etc.) for per-CPU-builds for some XDDs (e.g. scc, mfp, ...).

**Comment by mikrosk** [comment]
Yup, just realised that.

**Comment by czietz** [comment]
As for: Why didn't someone realize this before? I guess the amount of MegaSTEs is very low and the amount of FreeMiNT users on the MegaSTE even more so. Personally, I always have the habit of disabling all XDDs and XFSs that I do not absolutely need to get FreeMiNT + XaAES + Teradesk running on only 4 MB of RAM. I guess I never needed the scc.xdd...

@franklukas : As soon as the 8517fb9 snapshot has finished building, you should only need to replace the old scc.xdd with the one from the 8517fb9 snapshot (or newer) on your MegaSTE and everything should be fine.

**Comment by mikrosk** [comment]
I know why I didn't - I remembered that I had tested just mint.prg, not the complete zip archive. 

One of the objectives, why I have bothered with all that setup stuff, was to increase the number of FreeMiNT users, esp. on the not so "attractive" platforms (ST, plain TT/Falcon, ...) where MagiC was the only choice. So yes, it has been there since the initial revision but better if people start discovering bugs now than never. :)

**Comment by franklukas** [comment]
> Why didn't someone realize this before?

I have a Magnum STE with 6MB of Fastram so I have 10MB of Ram. A 4MB MSTE with MiNT/XaAES is a little bit ticky.

**Comment by mikrosk** [comment]
Actually, we were all victims of RTFM syndrome here. ;) https://github.com/freemint/freemint/blob/master/sys/xdd/scc/LIESMICH#L87

Curious why it hadn't been changed and listed as a bug instead.

**Comment by th-otto** [comment]
Oh, lol. But i'm curious why it should run only on 68020+
