### ISSUE TITLE
add  a "new" xaaes widget

### ISSUE THREAD

**Issue by ragnar76** [freemint/freemint#154]
hi there, 

i'm a huge fan of the gem widget from xaaes but what is really annoying is that the widget drops a shadow and xaaes also (you can see it in the screenshots below). So i've decided to rework the resource file a little bit (but not the b/w icons inside the file). 

What do you think? do you mind to add it to the official repository?
(you can find it here: https://lefson.de/gem_widget/gemflat.rsc)

This is the original one
![gem_widget_original](https://user-images.githubusercontent.com/1709576/76699299-93e6b580-66ac-11ea-82ee-5bd9d4d8f26a.png)

This is my work
![gem_widget_flat](https://user-images.githubusercontent.com/1709576/76699306-9ba65a00-66ac-11ea-9078-cc6707a2bf1a.png)

This is a composed image to see them side by side
![gem_widget_composed](https://user-images.githubusercontent.com/1709576/76699312-a95bdf80-66ac-11ea-9add-6b8c1d25ea14.png)

**Comment by mikrosk** [comment]
Look great to me, do you have also the appropriate hrd file to supply? At least all the other rsc widgets have it.

**Comment by ragnar76** [comment]
Not yet. I've used resource master to make this. How can i make it?

Miro Kropáček <notifications@github.com> schrieb am So., 15. März 2020,
15:45:

**Comment by mikrosk** [comment]
Good question. :D Maybe it is not as important as I though, @th-otto do you know something more about this? My understanding is that it contains additional information about each element, like name so you can easily navigate in the RSC file. Perhaps Interface generates it?

**Comment by th-otto** [comment]
Yes, interface generates  it, but ORCS can also generate it. And yes, it is only needed when changing the file, not at runtime. Only important thing is that the order of the widgets must be the same in all alternative resource files. If that is the case, you can "generate" it just by copying one of the other *.hrd files.

But don't worry, i can do that when checking in the file. Only question: should that be the new default widget set, and should we rename the previous default to something else?

**Comment by ragnar76** [comment]
i had some problems with interface (2.33 german), all icons were black (and it's not running on my firebee). However, i did not change the position or order, just remove the background and the "button" effect with a transparent background. so it should also work with gradients.

@th-otto i'm fine with just adding, no need to change the default widget

**Comment by th-otto** [comment]
Ok.

Just another question: i noticed that the monochrome icons have a different shape, and still the border. For example the sizer icon looks like
![mono](https://user-images.githubusercontent.com/12425871/76709530-d71e4400-66ff-11ea-9491-c8bcc16e6d8b.gif)
(mono version)

and

![color](https://user-images.githubusercontent.com/12425871/76709549-ebfad780-66ff-11ea-83e7-a6030b8a5fa0.gif)
(color gif)


Is that intended? If not, do you want to have a look at them again?

**Comment by ragnar76** [comment]
as i said: i havent touched the monochrome icons but i can, at least, remove the border too (good point to start using orcs;) ). dont ask me why there are different shapes. they are not made by me.

**Comment by th-otto** [comment]
If you used the original widgets as start, and did not change the monochrome icons, then it's no surprise that they look different ;) Remember that coloricons are actually a list of icons, you can have a separate one for each resolution. You can also have a separate version for the selected state (the adam.rsc makes use of it for example)

>good point to start using orcs;)

Feel free if to ask any questions should you have problems.

**Comment by ragnar76** [comment]
No problems so far. I've removed the border. in the attached archive you find the resource file and the hrd file (hope i made it correct)

[gemflat.tar.gz](https://github.com/freemint/freemint/files/4335074/gemflat.tar.gz)

**Comment by th-otto** [comment]
The hrd file was empty, but no problem. As mentioned, that can just be created by copying one of the other files. Also, the *.hrd files are not even part of the snapshots.

There are some minor quirks (eg. the selected version of the monochrome icon of the closer has an exclamation mark, but this is also the case for gemjwdg.rsc; i guess you originally started with this). So the files have been checked in now.

**Comment by ragnar76** [comment]
thanks a lot :)

yes, i did use gemjwdg.rsc as a blue print and in the meantime i've started to create a "pure" gem resource with gem icons only. again with gemjwdg.rsc to start from but somehow i've broken something :D . i was lazy and copied an icon (with shift and mouse move/klick). what was object number 2 is now number 11 and i think ths screws up xaaes. any chance to change the object number by hand?

![BROKEN](https://user-images.githubusercontent.com/1709576/76712929-4f473280-671d-11ea-859f-2eb9610d9bf9.JPG)

**Comment by th-otto** [comment]
Looks funny ;)

>any chance to change the object number by hand?

In orcs, right click on the root box, then choose "Sort". Sorting ascending, from top to right, then down (the default setting) should get you the correct order. If in doubt, compare it to the order of some other resource.
