### ISSUE TITLE
xaaes.km doesn't compile without mint.prg

### ISSUE THREAD

**Issue by mikrosk** [freemint/freemint#158]
If I have completely clean source tree and just enter ./xaaes/src.km and type `make 02060`, this is what I get in the end:
```
m68k-atari-mint-gcc -I.. -I../../../sys -D__KERNEL_MODULE__ -DMODULE_NAME=XaAES -DGENERATE_DIAGS=0 -DDEBUG_CONTROL=0 -DBOOTLOG=1 -m68020-60 -fgnu89-inline -Werror -mshort -g -O2 -fomit-frame-pointer -Wall -Wmissing-prototypes -Winline -Wshadow -Wpointer-arith -c ../xa_user_things.S -o xa_user_things.o
m68k-atari-mint-gcc -nostdlib -Wl,--entry -Wl,_init -o xaaes02060.km -I.. -I../../../sys -D__KERNEL_MODULE__ -DMODULE_NAME=XaAES -DGENERATE_DIAGS=0 -DDEBUG_CONTROL=0 -DBOOTLOG=1 -m68020-60   -fgnu89-inline -Werror -mshort -g -O2 -fomit-frame-pointer -Wall -Wmissing-prototypes -Winline -Wshadow -Wpointer-arith -s about.o adi.o adiload.o app_man.o cnf_xaaes.o c_keybd.o c_message.o c_mouse.o c_window.o xacookie.o debug.o desktop.o draw_obj.o form.o global.o handler.o init.o info.o k_init.o k_keybd.o k_main.o k_mouse.o k_shutdown.o matchpat.o menuwidg.o messages.o mscall.o mvdi.o nkcc.o obtree.o rectlist.o render_obj.o scrlobjc.o semaphores.o sys_proc.o taskman.o trnfm.o util.o widgets.o win_draw.o xa_appl.o xa_bubble.o xa_evnt.o xa_fnts.o xa_form.o xa_fsel.o xa_fslx.o xa_global.o xa_graf.o xa_lbox.o xa_menu.o xa_objc.o xa_pdlg.o xa_rsrc.o xa_rsc_lang.o xa_scrp.o xa_shel.o xa_vdi.o xa_wdlg.o xa_wind.o xcclib.o accstart.o nkcc-gc.o xa_user_things.o ../../../sys/libkern/.compile_020-60/strings.o -lgem -lgcc
m68k-atari-mint-gcc: error: ../../../sys/libkern/.compile_020-60/strings.o: No such file or directory
make[2]: *** [Makefile:49: xaaes02060.km] Error 1
make[2]: Leaving directory '/home/mikro/atari/projects/freemint/freemint.git/xaaes/src.km/.compile_02060'
make[1]: *** [Makefile:77: _stmp_02060] Error 2
make[1]: Leaving directory '/home/mikro/atari/projects/freemint/freemint.git/xaaes/src.km'
make: *** [Makefile:58: 02060] Error 2
```
I guess the libkern auto-detection doesn't work here?

**Comment by mikrosk** [comment]
Strangely it works with `make all`. So there must be some dependency problem, i.e. `make 02060` doesn't trigger something.

**Comment by th-otto** [comment]
Yes, there must be some dependency missing. Occassionaly, i still get some compilation errors when running parallel makes from the top level (after make clean). It works, when i run it again. It also works, when i don't use parallel makes.
That's difficult to track, since parallel makes depend on the timing, and i cannot always reproduce the error.

**Comment by th-otto** [comment]
Adding those dependencies would be a pain, and not the right thing. libkern (which is used by xaaes) is built while compiling the kernel. Adding a dependency there would mean to have to go back in the directory hierarchy, change to sys/libkern, and build the library again, which will badly conflict with the "normal" way of running make from the top level, and that library is maybe currently already building.

Conclusion: just don't do that. Run "make 020" from the top level instead.

**Comment by mikrosk** [comment]
First, you can't do `make 020` from top-level and second, this doesn't explain why libkern is build properly when running just `make` src.km.

**Comment by th-otto** [comment]
I think this is just a mismatch of the names. In the toplevel, the target is named "020", but the list in XAAESDEFS only knows about "02060"
