### ISSUE TITLE
XaAES terminates with NVDI in default/current resolution

### ISSUE THREAD

**Issue by mikrosk** [freemint/freemint#159]
From user point of view, this is basically an opposite of #22. You have NVDI, you boot XaAES and it fails to load:
```
~~~~~~~~~~~~ XaAES start up ~~~~~~~~~~~~~~~~
XaAES v1.6.4 Beta (m68020-060, Mar 29 2020 17:05) (MultiTasking AES for MiNT)
Part of freemint (https://freemint.github.io/).
stack is long-aligned:20DCC614
PRG: km=20D3E000, base=20D3E160, text=20D3E260 -> 20DB3C4C(481772), kentry:0.22,dos_version=40
home_path: 'U:\c\MINT\1-19-A69\XAAES\'
Loading config U:\c\MINT\1-19-A69\XAAES\xaaes.cnf
sysfile_exists: 'U:\c\MINT\1-19-A69\XAAES\moose_w.adi'
sysfile_exists: 'U:\c\MINT\1-19-A69\XAAES\moose.adi'
both moose_w.adi and moose.adi found (better choose one)
lang='en' (from config) code=0.
load adi modules
Loading AES Device Drivers:
load_adi: enter (0x20D3D254, 0x20D3D154, moose_w.adi)
load_adi: return 0
load_adi: enter (0x20D3B254, 0x20D3B154, moose.adi)
load_adi: return 0
adi_load: done
Creating XaAES kernel thread
AESSYS:Installed 'nAES' cookie in readable memory at 1140000
apid=-1,P_handle=0
k_init: videomode=0
nvdi version = 503
could not determine fvdi version
k_init:vdo=30000 vm=0 video=0
Default screenmode
Screenmode is: 1
k_init: v_opnwk() mode=1
k_init: v_opnwk() handle=1
Physical work station opened: 1
Virtual work station opened: 2
invalid screen-type:0
ERROR: k_init failed!
wait for AES help thread to terminate....(ferr=-1)
```
The offending code is this: https://github.com/freemint/freemint/blob/master/xaaes/src.km/k_init.c#L786 where we get, as we see in the log, 0. According to [vq_extnd description](https://freemint.github.io/tos.hyp/en/vdi_inquire.html#vq_extnd) this means "No screen". Since it works perfectly without NVDI (with disabled memory protection), I let it pass in my own build and voila:
```
invalid screen-type:0
lookup-support:1, planes:1
Video info: width(640/480), planes :1, colours 2 pixel-format 8
stdfont: id = 1, size = 10, cw=8, ch=16
smlfont: id = 1, size = 8, cw=6, ch=6
Display Device: Phys_handle=1, Virt_handle=2
 size=[640,480], colours=2, bitplanes=1
Loading system resource file 'xaaes.rsc' lang='en'(0) trans=1
xaaes_sysfile: check if 'U:\c\MINT\1-19-A69\XAAES\xaaes.rsc' exists - return = 0
system resource = 20D1C004 (U:\c\MINT\1-19-A69\XAAES\xaaes.rsc)
xaaes_sysfile: check if 'U:\c\MINT\1-19-A69\XAAES\xa_xtobj.rsc' exists - return = 0
xaaes_sysfile: check if 'U:\c\MINT\1-19-A69\XAAES\xaaeswdg.rsc' exists - return = 0
do_bkg_img:U:\c\MINT\1-19-A69\XAAES\640480.1/xa_form.mfd not found
AESSYS:read_inf:U:\c\MINT\1-19-A69\XAAES\xaaes.inf
alert:6, KBD:7,pferr=0
No wheel support
Using moose adi
Loading AES modules...
loading accs ---------------------------
loading accessories from 'C:\'
load_accs: launch (C:\xcontrol.acc)
load_accs: launch (C:\ct60temp.acc)
loading shell and autorun ---------------
autorun[0]: cmd=(20E0C038) 'u:\c\mint\1-19-a69\sys-root\opt\GEM\toswin2\toswin2.app'
   args[0]:    =(10E9F58) ''
Launch shell 'u:\c\mint\1-19-a69\sys-root\opt\GEM\teradesk\desktop.prg' with args 'No args'
```
Everything works as it should. Is this an NVDI bug? Should we hack around it?

**Comment by th-otto** [comment]
That change was done by https://github.com/freemint/freemint/commit/6ef21f59f7307c1bd6db4c37ebd4ce3786be7973 ; one of those commits from HK with totally unrelated changes. I also wonder why he checks for type 1 there, when the documentation says all drivers return either 4 or 0. I also wonder, if all know drivers return either 4 or 0, why to do that check at all. It's imho totally useless.

**Comment by paulwratt** [comment]
isnt the something in the mailing list about that, somewhere between 2009-2012 maybe?

**Comment by mikrosk** [comment]
It seems that there's more than meets the eye. I wanted to check this issue again and to my surprise, I wasn't able to reproduce it. After many trials I have found out that it heavily depends on the setup used:
- TOS 3.06/030 CPU: ok (`screen-type` = 4)
- TOS 4.04/030 CPU: ok (`screen-type` = 4)
- CT60TOS/060 CPU: not ok (`screen-type` = 0)
- CT60TOS/060 CPU/NVDI disabled: ok (`screen-type` = 4)
- CT60TOS/060 CPU/XBOOT in AUTO: ok (`screen-type` = 4) (!)

So it seems that NVDI doesn't like something in CT60TOS and this "something" is miraculously initialised if XBOOT is run before NVDI. Anyway, it still doesn't excuse this strange check so I'm going to remove it anyway.
