### ISSUE TITLE
USB keyboard polling issue

### ISSUE THREAD

**Issue by mikrosk** [freemint/freemint#165]
Accidentally I found this: http://jeff.rainbow-100.com/20200207.htm ... it's coming from the author of [GemPy](https://github.com/ArmstrongJ/gempy). Seems to be a pretty recent build so I'm wondering whether someone else has similar issues?

**Comment by th-otto** [comment]
Sounds a bit strange. Sure, polling a device isn't optimal, but AFAIK this is done as part of the timer interrupt, so no matter how long it takes for any redraw, the driver should not miss any key releases???

**Comment by DavidGZ** [comment]
I wanted to test this but the only USB keyboard that I have is cordless and I don't find the receiver anywhere :-/

**Comment by Perdrix24** [comment]
The keyboard polls at 40ms to save CPU time, instead of 20ms. One cycle out of two is ignored.

**Comment by Perdrix24** [comment]
I don't know much about MiNT, but I think the TOS version of the driver uses the timer interrupt, but not the MiNT version. It uses this code:
```
void
kbd_poll (PROC * proc, long dummy)
{
	wake (WAIT_Q, (long) &kbd_poll_thread);
}

void
kbd_poll_thread (void *dummy)
{
	p_setpriority(0,0,-20);

	while (kbd_data.pusb_dev)
	{
		kbd_int ();
		addroottimeout (20, kbd_poll, 0);
		sleep (WAIT_Q, (long) &kbd_poll_thread);
	}

	kthread_exit (0);
}
```

**Comment by mikrosk** [comment]
I tried to reproduce this issue with latest kernel and Lightning r268 drivers - no luck. It's true that the slower VDI, the worse user experience but all I could get was a missed keypress, certainly not an endless, frustrating loop.

I even tried Lightning's `BLITZ030.UCD` driver and original FreeMiNT drivers for the rest, no visible difference.

So I'm closing this as either an outdated setup and/or netusbee issue. @ArmstrongJ try to download latest kernel + usb drivers (and/or try under TOS).

**Comment by ArmstrongJ** [comment]
So as I said in that blog post, I'm only interested in using the keyboard under MiNT.  Under heavy load, the keyboard is unresponsive.  The missed keypress problem is so bad that I can't even be bothered with trying to use a USB keyboard.  The fact that it isn't done on a hardware timer sounds like a bad thing.  Force-changing the USB driver priorities can make things ever so slightly better, but a USB keyboard is still completely unfeasible.

The TOS drivers work noticeably better, but I don't really have anything interesting to do under TOS to tax the system (a TT030).  

The post also points out, I believe, that the USB drivers do not work with N.AES at all.  The system will lock up the first time a key is pressed.  The mouse wheel has the same effect.  If you load the drivers without any USB devices, using the Atari keyboard, the system still crashes.

I'm honestly not going to try another kernel build.  The system is in a "working" state where the kernel boots 4 out of 5 times (the failed time is always some absurd memory allocation error from one of the kernel modules, USB or XaAES).  I've tried three builds thus far, but that was months ago.  I don't want to risk toppling this house of cards that is my system.

**Comment by mikrosk** [comment]
Up to you, of course. I don't observe any of the issues you have mentioned. It's also possible that your hardware is faulty, the memory bombing would certainly imply so. On my TT, FreeMiNT is rock solid. You can try https://www.chzsoft.de/site/hardware/diverse-kleinigkeiten-fur-den-atari-st/#ram-test-software-yaart for example.

**Comment by th-otto** [comment]
> The fact that it isn't done on a hardware timer sounds like a bad thing.

Essentially, it is done on a hardware timer. Definitely when using TOS, and indirectly also in MINT, because the kernel sleeps, and wakes up every 20ms. That "wakeup" is issued by the system timer.

**Comment by DavidGZ** [comment]
If I can borrow a USB keyboard from someone I'll test it with my NetUSBee. In atari-forum many people reported problems with the TT cartridge port, but if you say that TOS drivers work better we can rule out this explanation. @ArmstrongJ Did you try mass storage devices? if so did they work fine?

**Comment by ArmstrongJ** [comment]
@th-otto While the kernel might wake up, I certainly get plenty of missed keys and mouse position issues.  I feel like i/o heavy stuff might make it worse, but it's hard to tell.

@DavidGZ I haven't tried any mass storage devices.

I'm just trying to provide some information here.  USB keyboards not working isn't really a problem for me.  I'm using a Wizztronics DEKA2 instead, which allows me to use a non-Atari keyboard at least.  The USB mouse, which certainly does suffer from missed updates as well, is pretty usable regardless.  As long as networking and the mouse are fine, I'm okay with it.  Ideally this stack would work with N.AES (I strongly prefer it over XaAES), but I can't have everything.

**Comment by DavidGZ** [comment]
@ArmstrongJ I was asking about mass storage devices because this would help us to completely discard that you don't have the issues that many TT users have with their NetUSBee.
About N.AES, other user reported the same problem #143, I want to take a look at some point to see if I can fix it.
