### ISSUE TITLE
connecting filesystem type with device

### ISSUE THREAD

**Issue by paulwratt** [freemint/freemint#166]
`/kern/filesystems` only contain the filesystem handlers, not which drives they belong to.

SpareMiNT `/etc/fstab` is of a non-standard format, which also does not show which drive is connected to which driver. if you dont use a distro, you probably wont have even have `/etc`

The above is not the case for GentooMiNT (if anyone else is using that)

There is nothing in `/dev` reference drives or their devices

As  to "fixing" SpareMiNT, fstab format, fsck, and its tools, that wont happen anytime soon and it would break older installations quite easily

Since MiNT already know all the info a user want to know, it could provide either a `/dev` or `/kern` path that joins mounted device name with the filesystem format, something like:
```
$ ls -l /kern/drivers/*
/kern/drivers/ext2-xfs
-r--r--r--  2 root root 0 Apr 20 16:09 0
-r--r--r--  2 root root 0 Apr 20 16:09 1
-r--r--r--  2 root root 0 Apr 20 16:09 d
-r--r--r--  2 root root 0 Apr 20 16:09 f
/kern/drivers/external
-r--r--r--  2 root root 0 Apr 20 16:09 aes-km => xaaes/xaaes040.km
-r--r--r--  2 root root 0 Apr 20 16:09 ext2-xfs => ext2.xfs
-r--r--r--  2 root root 0 Apr 20 16:09 inet-xdd => inet.xdd
-r--r--r--  2 root root 0 Apr 20 16:09 nfeth-xdd => nfeth.xdd
-r--r--r--  2 root root 0 Apr 20 16:09 nfs-xfs => nfs.xfs
-r--r--r--  2 root root 0 Apr 20 16:09 usb-km => usb040.km
-r--r--r--  2 root root 0 Apr 20 16:09 xconout2-xdd => xconout2.xdd
/kern/drivers/hostfs-xfs
-r--r--r--  2 root root 0 Apr 20 16:09 h
-r--r--r--  2 root root 0 Apr 20 16:09 m
-r--r--r--  2 root root 0 Apr 20 16:09 y
/kern/drivers/internal
-r--r--r--  2 root root 0 Apr 20 16:09 hostfs-xfs
-r--r--r--  2 root root 0 Apr 20 16:09 vfat-xfs
/kern/drivers/modules
-r--r--r--  2 root root 0 Apr 20 16:09 aes-km => xaaes040.km
-r--r--r--  2 root root 0 Apr 20 16:09 usb-km => usb040.km
/kern/drivers/nfs-xfs
-r--r--r--  2 root root 0 Apr 20 16:09 0
-r--r--r--  2 root root 0 Apr 20 16:09 1
-r--r--r--  2 root root 0 Apr 20 16:09 2
/kern/drivers/vfat-xfs
-r--r--r--  2 root root 0 Apr 20 16:09 c
-r--r--r--  2 root root 0 Apr 20 16:09 e
/kern/drivers/xdd
-r--r--r--  2 root root 0 Apr 20 16:09 inet
-r--r--r--  2 root root 0 Apr 20 16:09 usb
-r--r--r--  2 root root 0 Apr 20 16:09 xconout2
/kern/drivers/xfs
-r--r--r--  2 root root 0 Apr 20 16:09 ext2
-r--r--r--  2 root root 0 Apr 20 16:09 hostfs
-r--r--r--  2 root root 0 Apr 20 16:09 nfs
-r--r--r--  2 root root 0 Apr 20 16:09 vfat
/kern/drivers/xif
-r--r--r--  2 root root 0 Apr 20 16:09 nfeth
$ cat /kern/drivers/xfs/ext2
d
f
$ cat /kern/drivers/xfs/vfat
c
e
$ cat /kern/drivers/ext2-xfs/0
drive=D:
path=u:/d
blocksize=1024
blocks=1024000
lunar=scsi:0:2
$ cat /kern/drivers/vfat-xfs/c
drive=C:
path=u:/c
blocksize=512
blocks=127924
lunar=scsi:0:1
```
or
```
$ cat /kern/mounts
path type refer
/ mintfs nodev 
/a stfloppyfs floppya
/b stfloppyfs floppyb
/bin slnfs /d/bin
/boot slnfs /c/
/c vfat scsi:0:1 
/d ext2 scsi:0:2 
/dev devfs nodev 
/e vfat scsi:0:3 
/etc slnfs /d/etc
/f ext2 scsi:0:4 
/kern kernfs nodev 
/h hostfs /home/pi/host_fs/ 
/home slnfs /h
/host aranymfs nodev
/lib slnfs /d/lib
/m hostfs /media/ 
/mnt slnfs /d/mnt
/opt slnfs /d/opt
/pipe pipefs nodev
/proc procfs nodev 
/ram ramfs nodev 
/root slnfs /d/root
/sbin slnfs /d/sbin
/shm shmfs nodev 
/tmp slnfs /h/temp
/usr slnfs /d/usr
/var slnfs /d/var
/y hostfs /
/mnt/nfs/rpi4/home nfs 192.168.1.116:/rpi4-home
/mnt/smb/win10/shared samba //win10box/shared
/mnt/loop/0 loop /mnt/smb/win10/shared/atari-40Gb.img
/mnt/loop/0p1 loop /mnt/loop/0
/mnt/atari-40Gb vfat /mnt/loop/0p1
/mnt/atari-m68k-devel nfs 192.168.1.117:/rpi2-m68k-devel
/mnt/repos nfs 192.168.1.115:/fileserver-repos
```
or both.

in the 1st example I would expect a partition on a 2nd IDE drive in a Falcon (for those that have them) to show up with `lunar=ide:1:x` where the 1st number is 0 based, and the second number is 1 based.

in that 2nd example theres a lot of mounts, but actually its the minimum  of what I would expect from a mounts file, enough to be able to write an mtab driver. at least to start with a list of mint mounted drives and their filesystem type and what they refer to would be nice.

FYI linux probably copies its `/etc/mtab` file from `/proc/mounts`
```
$ ls -l /etc/mtab
lrwxrwxrwx 1 root root 19 Feb 14 05:16 /etc/mtab -> ../proc/self/mounts
```

BTW:
why does `ls -l /proc` show a date of `December 31 1969`?
what is `/ram`, if its a fs how come there is no driver listed in `/kern/filesystems`

**Comment by mikrosk** [comment]
Sorry but this is not a bug report and I have a problem to figure out what exactly is the feature you're proposing. Plus you are mixing user space, mounting and kernel drivers all together. Stuff like this belongs to mailing list, if you think it is worth discussing.

**Comment by paulwratt** [comment]
you obviously did not even read it:

> why does ls -l /proc show a date of December 31 1969?
> what is /ram, if its a fs how come there is no driver listed in /kern/filesystems

**Comment by mikrosk** [comment]
>you obviously did not even read it:
>
>why does ls -l /proc show a date of December 31 1969?

And that is the reason why your bug report is named "connecting filesystem type with device", right. I'm sorry Paul but you often produce so much text with so little value inside that it is hard to take your emails and reports seriously.
