### ISSUE TITLE
Keyboard (scancode) buffer only allows 15 scancodes at a time (even though it's 16 in size)

### ISSUE THREAD

**Issue by czietz** [freemint/freemint#169]
While investigating an interesting effect in the USB mouse driver (which posts arrow key presses and releases to the OS to enable scrolling) I found what possibly is a bug in the keyboard handling:

https://github.com/freemint/freemint/blob/be61fce5c2bb524e52dca458c7f490df520413d5/sys/keyboard.c#L929-L945

The scancode buffer `scanb` is 16 entries in size, but the code will only allow it to contain at **maximum 15 unread** scancodes. Consider the attached test program:
[fm_keyb.zip](https://github.com/freemint/freemint/files/4564791/fm_keyb.zip)

It simulates pressing and releasing keys "1" to "8". Under TOS (or EmuTOS), as expected, "12345678" is read back. However, under MiNT, the "8" key appears to be stuck, yielding an endless stream of "8"s due to keyboard repeat. This is because the 16th and last scancode ("release 8") is not put into `scanb`, anymore.

W.l.o.g. consider what happens when `scanb_head = scanb_tail = 0`: The first scancode is put into `scanb[0]` and `scanb_tail` is 1, afterwards. At some point, the 15th scancode is put into `scanb[14]` and `scanb_tail` is 15. However, the 16th scancode is not put into `scanb[15]` because `tail = (scanb_tail + 1) & 0xf` is 0 and, therefore, `if (tail != scanb_head)` is false.

EDIT: Although, I must say, I currently have no idea how to improve the code. If this behavior of the scancode buffer is to be considered a "feature", then the USB mouse driver has to be restricted never to post more than 14 scancodes (seven pairs of key press and key release), otherwise the last key press will be stuck. (I already had a short discussion with @Perdrix24 about this.)

**Comment by czietz** [comment]
Ok, thinking about this some more: With a 16 entry circular buffer with only a head and a tail pointer (like in FreeMiNT's scancode buffer implementation) one simply could not tell whether there are 0 or 16 unread entries in the buffer. Thus, the code has to stop at 15.

Sorry for the noise! This imho makes it clear that the USB mouse driver must be modified instead.

**Comment by DavidGZ** [comment]
OK, thanks a lot for the investigation, I really appreciate it.
