### ISSUE TITLE
hyp_view.cfg included in FreeMiNT builds should have C:\GUIDES as default path

### ISSUE THREAD

**Issue by czietz** [freemint/freemint#175]
Since FreeMiNT binary snapshot builds include some HypView guides that get unpacked to C:\GUIDES, the included version of HypView should imho be configured to have that as the default path (and not C:\GEMSYS\GUIDES).

I haven't checked the build scripts, but it seems that this configuration file is included in the HypView builds: https://github.com/freemint/hypview/blob/master/release/hyp_view.cfg (having C:\GEMSYS\GUIDES as default path) and not this configuration file: https://github.com/freemint/hypview/blob/master/hyp_view.cfg (which would already have C:\GUIDES as default path).

**Comment by th-otto** [comment]
Should be fixed by https://github.com/freemint/hypview/commit/e640abe0c4dc51758da6d0907d3de32f7d044955 (hypview now has its own repo)

**Comment by czietz** [comment]
Confirmed to be fixed. Thanks!
