### ISSUE TITLE
LMC1992 (sound mixer) not correctly initialized

### ISSUE THREAD

**Issue by czietz** [freemint/freemint#179]
I'm afraid the issue described here https://sourceforge.net/p/emutos/mailman/message/37012632/ for EmuTOS and fixed with https://github.com/emutos/emutos/commit/7f64a9331e063b2c5d62ed5fb19b48de8a999782 also applies to FreeMiNT's audio driver. Actually, even more so, because FreeMiNT's Microwire write function does not even have a delay (like EmuTOS previously had): https://github.com/freemint/freemint/blob/e94c9525dbf624776d16710022aed156baf41563/sys/xdd/audio/dmasnd.h#L71-L75.

With the logic analyzer hooked to the LMC1992 sound mixer in my TT, I can see that in fact only the _last_ of the Microwire transfers in the audio driver is executed:
https://github.com/freemint/freemint/blob/e94c9525dbf624776d16710022aed156baf41563/sys/xdd/audio/lmc.c#L42

All others are silently dropped.

**Comment by th-otto** [comment]
Based on the emutos patch, i came up with the following patch for FreeMint. Could you please check that?

[audio.patch.txt](https://github.com/freemint/freemint/files/4840748/audio.patch.txt)

**Comment by czietz** [comment]
Your patch seems to be missing the definition of `MW_MASK`.

**Comment by th-otto** [comment]
Yes, sorry. Updated the attachment.

**Comment by czietz** [comment]
I cannot test on real HW currently (due to it being in storage). However, here are what I still noticed:

- Since the mask is now shifted left by 1 bit (to allow for the 'stop' bit), you must also shift the device address `MW_DEV`by 1 bit, e.g. by `((data | MW_DEV)<<1) | 1`.
- You use a mix of tabs and spaces for indentation.
- The `\`  at the end of `MWdata = `... is superfluous.

**Comment by th-otto** [comment]
Ah yes. Thought i've changed the definition of MW_DEV accordingly, but apparently something went wrong with the patch.

The other things are maybe because i copied some parts from emutos sources.

So i have to wait until you are able to test it (i think there is not much hurry about that).

**Comment by czietz** [comment]
I would have preferred had you modified the patch to fix the error w.r.t. the device address.

Anyway, I edited one line of your patch to be `MWdata = ((data | MW_DEV)<<1) | 1;` before testing. With that, I can confirm - by capturing data with a logic analyzer - that all five microwire commands are now sent to the mixer.

**Comment by czietz** [comment]
I consider this fixed by @th-otto with https://github.com/freemint/freemint/commit/b9754d7280187d6d25d1c091c37cd3811d537b2d.
