### ISSUE TITLE
ARAnyM GEM clipboard configuration

### ISSUE THREAD

**Issue by vinriviere** [freemint/freemint#184]
ARAnyM supports clipboard sharing with the host. This should be enabled by default.
This is defined in the file drive_c/mint/version/xaaes/xaaes.cnf. According to [ARAnyM configuration](https://github.com/aranym/aranym/wiki/gem_clipbrd), the clipboard variable should be defined like this:

```
clipboard = u:\host\clipbrd\
```
This way, copy/paste can be used inside i.e. QED and TosWin2 from and to the host clipboard. This is very convenient to share text between the host OS and ARAnyM.

**Comment by th-otto** [comment]
Yes, but this only works if you also install the driver for it. I think configuration settings like this should be left to "distributions" like AFROS.

**Comment by mikrosk** [comment]
Yes, it is always hard for me to decide how far to take user friendliness of the pre-configured builds. Driver is enabled, so maybe it makes sense to configure as well.

**Comment by vinriviere** [comment]
Indeed, as the aranym driver is enabled by default (built-in mintara.prg?) it is inconsistent to have the clipboard stuff half-configured. And I can't see any good reason to keep a wrong configuration.

**Comment by th-otto** [comment]
> built-in mintara.prg?
No, its a separate driver (aranym.xfs).

**Comment by vinriviere** [comment]
> No, its a separate driver (aranym.xfs).

I've been fooled by MiKRO's mchdir feature from 2013!! aranym.xfs is provided in the `aranym` subfolder. But as the folder matches the machine type, modules are also loaded from there. Conclusion: aranym.xfs is enabled in the official FreeMiNT setup. So I maintain my request: the clipboard variable should be set up accordingly.

**Comment by mikrosk** [comment]
Well, there you go. Download the latest aranym snapshot.

I think that feature doesn't work 100% reliably, though - I was able to get stuff from my Linux KDE to Atari (with some strange quirks) but not the other way around.
