### ISSUE TITLE
QED menu disappears at startup

### ISSUE THREAD

**Issue by vinriviere** [freemint/freemint#190]
Seen there:
https://www.youtube.com/watch?v=GOkDuLmgWFo&t=3220

When QED starts, XaAES displays an alert: Print dialogs unavailable with current VDI. After clicking OK, the menu bar switches back to TeraDesk.

Whatever reason causes this, this should not happen. The menu of the current application should not be lost like this. Specifically when running a basic program like QED.

**Comment by vinriviere** [comment]
@mikrosk and @th-otto have already proposed improvements on the MiNT Mailing List.

**Comment by mikrosk** [comment]
To be more precise, we should decide how to approach the solution - whether to have it available for each app as seen here: https://github.com/freemint/freemint/blob/master/xaaes/src.km/example.cnf#L605 (and change the `default` entry) and remove this: 
 https://github.com/freemint/freemint/blob/master/xaaes/src.km/example.cnf#L515 or just keep the latter and change its default value.

Confusingly now they are both taken into account.

**Comment by th-otto** [comment]
Both QED and XaAES have been fixed to avoid that alert.

Only question remains whether to keep the "next_active" setting in xaaes.
