### ISSUE TITLE
STZIP.TOS fails to extract

### ISSUE THREAD

**Issue by vinriviere** [freemint/freemint#191]
STZip is provided as self-extractible archive. It can be found [there](https://sites.google.com/site/stessential/archiver-tools/stzip).

Even if it extracts well on plain TOS, it fails to extract on FreeMiNT (hostfs, ramdisk, or floppy).

Message is:
`Extracting : STZIP\READMECannot create file`

**Comment by vinriviere** [comment]
After investigation: if fails due to wrong `Fcreate("STZIP\README", 0x20)` return value. The STZIP folder must not exist. On plain TOS, return value is -34. With current FreeMiNT, it is -33. This is why STZIP.TOS fails to extract on FreeMiNT.

Here is minimal testcase: [fcr.zip](https://github.com/freemint/freemint/files/4775646/fcr.zip)
Should display:
```
Fopen ret=-33
Fcreate ret=-34
```

With current FreeMiNT, it displays:
```
Fopen ret=-33
Fcreate ret=-33
```

**Comment by th-otto** [comment]
On Sonntag, 14. Juni 2020 01:16:37 CEST Vincent Rivière wrote:
> On plain TOS, return value is -34. With current FreeMiNT, it is -33.

This is a drawback of behaving more unix-like. There, you would also get 
ENOENT in this case. Changing this would probably break most unix tools. 
Another reason why extracting fails, is that there is no entry for the 
directory itself in the archive.

**Comment by vinriviere** [comment]
Whatever reasons are invoked: extracting works in plain TOS, so it should also work with FreeMiNT. Period. Unless the program does something wrong, and it is not the case here.

Have a look at [Pdomain()](https://freemint.github.io/tos.hyp/en/gemdos_process.html#Pdomain) documentation. It says:

> 0 **TOS-domain** (default value). In this domain all system calls behave exactly as under normal TOS.

So FreeMiNT should never be "more unix-like" with plain TOS programs, which don't call Pdomain(). FreeMiNT's Fcreate() can return whatever it wants in MiNT domain, but by default, in TOS domain, it should return the same value of TOS. So solution is just to test the current domain when determining the return value of Fcreate().

**Comment by th-otto** [comment]
Looking at the current domain be a solution. I'e added a patch now that fixes stzip, but please check if you encounter problems with other programs due to this.

BTW the documentation about Pdomain is a bit misleading. Of course, most new calls that are not implemented by TOS are still performed, so they don't behave like on TOS, either.

**Comment by vinriviere** [comment]
Many thanks, Thorsten.
Now STZIP.TOS extracts well with latest FreeMiNT snapshot 😃
Issue solved.

**Comment by vinriviere** [comment]
By the way: MiNTLib's error code for open() / creat() certainly has to be POSIX compliant. But regarding to the FreeMiNT kernel, I can't see any good reason to behave differently than TOS, whatever domain is currently selected.

**Comment by th-otto** [comment]
Yes, i've checked mintlib, too. I think it should even behave correctly when ENOTDIR is returned, however it would do some extra stat() calls to check whether it has to return ENOENT instead. Bu tthat is already the case when running programs using mintlib on plain TOS:

I've also tried to repack STZIP.TOS using unzipsfx, but hat miserable failed... some day someone should have a look at this.
