### ISSUE TITLE
Broken temp.zip pushed with usb4tos snapshots

### ISSUE THREAD

**Issue by czietz** [freemint/freemint#192]
[USB4TOS snapshot downloads](https://bintray.com/freemint/freemint/snapshots-usb4tos) include a file called `temp.zip` that is a) not needed and b) not a zip file or a broken zip file. Probably a minor issue with the build or deploy process.

**Comment by mikrosk** [comment]
Thanks for spotting that! It's a side effect of the unfortunate #189 - we were trying to download `qed`, `cops` etc packages even for _this_ target. I really must fix it properly in near future.
