### ISSUE TITLE
FreeMiNT 1.18 crashes on Hatari 2.2.1

### ISSUE THREAD

**Issue by daemonspudguy** [freemint/freemint#196]
Video of crash: [https://youtu.be/eRnUr6w_vwE](url)

**Comment by th-otto** [comment]
Funny. And you think that can help solve the issue?

Besides that, it does not crash, just read the messages:
```
No init program defined to be started.
```
Not to mention that this is version 1.18, which is not maintained separately.

**Comment by DavidGZ** [comment]
Hi,

as Thorsten said this is not a crash. The kernel is looking for its configuration file in u:\c\mint\1-18-0\mint.cnf and it didn't find it.
What kind of FreeMiNT installation did you use?

If you want to test FreeMiNT I'd recommend you to install a snapshot from here:
https://freemint.github.io/#snapshots

Also you could try VanillaMiNT:
https://atari.joska.no/VanillaMiNT/

**Comment by daemonspudguy** [comment]
![Screen Shot 2020-08-24 at 09 08 20](https://user-images.githubusercontent.com/24438557/91048284-70c01a80-e5e9-11ea-90e8-b4c129245381.png)
What am I missing? It's right there!

**Comment by skaftetryne** [comment]
On Mon, 2020-08-24 at 06:09 -0700, daemonspudguy wrote:
> 
> What am I missing? It's right there!

The error message doesn't say that the file does not exist, but that it
can't be read. Does Hatari have the necessary access rights to read
this file?

Jo Even

**Comment by daemonspudguy** [comment]
How exactly would I do that?

**Comment by mikrosk** [comment]
I think the problem here is that @daemonspudguy is trying to run it from Hatari via GEMDOS emulation. This doesn't work, FreeMiNT uses its own GEMDOS layer, i.e. Hatari's "fake" is ignored. You must create a harddisk image.

**Comment by th-otto** [comment]
Are you booting from an Hatari gemdos drive? IIRC that only works with kernels which have OLD_TOSFS enabled, but this is not the case for the snapshot versions.

Edit: gnarf. mikrosk was just 1min faster :grin:

**Comment by daemonspudguy** [comment]
Oh. I'm an idiot.

**Comment by vinriviere** [comment]
BTW, as people hit this issue again and again, we may consider to dynamically enable OLD_TOSFS when Hatari is detected. And get rid of MINTHAT.PRG.

**Comment by th-otto** [comment]
You can only detect Hatari by use of NatFeats, which is disabled in Hatari by default. And you would have to enable OLD_TOSFS on a per-drive-basis; i don't think that this is such easy.

**Comment by DavidGZ** [comment]
@daemonspudguy here you can find a disk image to test MiNT with Hatari:

https://subsole.org/st_mint

At the end of the page there are special instructions for Hatari. It's a basic distribution thought for the ST but it's a start.

**Comment by daemonspudguy** [comment]
@DavidGZ THANK YOU! THANK YOU! THANK YOU!

**Comment by daemonspudguy** [comment]
how can I install the snapshot onto an image?

**Comment by DavidGZ** [comment]
You should configure hatari to mount a directory in the host operating system as a gemdos drive, then copy the snapshot into the image. As far as I remember this should be done from TOS, if my memory doesn't fail accessing the host disk drive from FreeMiNT under hatari is not possible.

**Comment by th-otto** [comment]
you can also use mtools to access the image:

```
mdir -i st_mint-1.2.img@@1024 /auto
 Volume in drive : has no label
Directory for ::/auto

.            <DIR>     2020-01-29  20:01 
..           <DIR>     2020-01-29  20:01 
mint-4d2 prg      3097 2020-01-29  20:01  mint-4d2.prg
        3 files               3 097 bytes
                         24 109 056 bytes free
```

then use mcopy (with the same -i argument) to copy files to/from it.

Of course you can also add an entry to ~/.mtoolsrc, so you can just use a drive letter:

```
echo "drive q: file="st_mint-1.2.img" MTOOLS_SKIP_CHECK=1 MTOOLS_LOWER_CASE=1 MTOOLS_NO_VFAT=1 offset=1024"  >> ~/.mtoolsrc
mdir q:
```

**Comment by th-otto** [comment]
BTW, who created that disk image? I think it shouldn't be too hard to automatically recreate it together with the snapshots. Would make testing a snapshot using Hatari or Aranym much easier. All the utils are already in travis-scripts/coreutils, except mksh (do you know which patch was used for it?)

**Comment by DavidGZ** [comment]
> BTW, who created that disk image? I think it shouldn't be too hard to automatically recreate it together with the snapshots. 

@EmmanuelKasper,  "marcello" in atari-forum

>Would make testing a snapshot using Hatari or Aranym much easier. All the utils are already in travis-scripts/coreutils, except mksh (do you know which patch was used for it?)

No idea, @Emmanuel

**Comment by EmmanuelKasper** [comment]
FWIW I am building st-mint with this toolset https://github.com/EmmanuelKasper/mck

I have this smallish patch for running
https://github.com/EmmanuelKasper/mck/commit/6d087d5dd757fcfac41a4b77f2304c9aa015888c

If there is interest, I would be happy to move this project  under the FreeMint github org umbrella, and also possibly help create the disk image as an artifact of the snapshot build system.

**Comment by th-otto** [comment]
Thanks for the links. I didn't have a closer look at all the scripts yet, but in Freemint, all that construction of the bootable builds is one on travis side, after a new kernel has been compiled. 

The idea was to do something similar there, but it looks that you did quite some more work. Maybe, as an alternative, we could grab some already existing image, and just populate it with the current kernel/drivers etc. That way, you would always have an image with the recent snapshot.

**Comment by daemonspudguy** [comment]
This should probably be reopened.

**Comment by th-otto** [comment]
Why? I think we agree that is a setup problem, not a bug in freemint.

**Comment by daemonspudguy** [comment]
Good point.

**Comment by EmmanuelKasper** [comment]
I confirm that FreeMint is working with Hatari 2.2.1.
@daemonspudguy  can you rename this issue report to the original title ? ( Think I don't have the permissions)

We should open a different issue for tracking the disk images creation.
