### ISSUE TITLE
issue: mount_nfs: mount request to kernel failed / could not do nfs mount

### ISSUE THREAD

**Issue by mzryz** [freemint/freemint#199]
Dear fellow Minters.

Upon using the latest snapshot & up to date drivers, NFS in Mint seems not to work. I have never had it working so cannot tell you when it last worked.

PS - I do run NFS on my SGI Octane IRIX machine (ancient unix) and modern linux boxes, so my NFS knowledge is good. I feel this is possibly a Mint issue.

My syntax is: mount_nfs 192.168.0.121:/usr/people/user/nfs /u/nfs
console output:
mount_nfs: mount request to kernel failed
mount_nfs: could not do NFS mount

I have tried connecting to ancient unix like IRIX & modern linux, same issue.

**Comment by mikrosk** [comment]
Latz has made a great documentation for FreeMiNT, still stitting on my disk for proof-reading. He's commented on this:

```
mount_nfs -o rw 192.168.0.10:/home/share /nfs/remotemachine@{0}

This would mount folder /home/share on IP 192.168.0.10 into your FreeMiNT
directory u:/nfs/ with name "remotemachine". Now you can access this
directory like it would be located on your local harddisc.

If you have any problems to connect to PC/NAS, it's mostly caused by an
incorrect IP- or path entry. Please verify carefully the @{B}pathname case-
sensivity@{0} and that spaces, colon(s) and slashes are placed correctly!
Also check the access permission settings of the NFS server then.
```
Also, don't forget to enable `nfs.xfs`.

**Comment by mikrosk** [comment]
Btw, for this kind of questions, our mailing list is a more preferable option.

**Comment by skaftetryne** [comment]
On Sun, 2020-08-30 at 07:26 -0700, mzryz wrote:
> I have tried connecting to ancient unix like IRIX & modern linux,
> same issue.

The NFS server needs to support NFS version 2, which most "proper"
unix-variants haven't done in years. I had to manually enable it on my
Linux-boxes (Ubuntu 18.04 and 20.04). When that was done NFS worked
almost perfectly ("almost", because the Atari NFS client does not
handle it well when the server becomes unavailable) on my Ataris.

Jo Even

**Comment by mzryz** [comment]
Friends - relatives - countrymen! THANK YOU! & from Latz
The command you gave from Latz worked: 
mount_nfs -o rw 192.168.0.10:/home/share /nfs/remotemachine@{0}

This is beautiful! I am very happy. My Atari is finally fully networked!
