### ISSUE TITLE
Sort out the doc folder

### ISSUE THREAD

**Issue by mikrosk** [freemint/freemint#2]
[There](https://github.com/freemint/freemint/tree/master/doc) are many different things -- txts, hyps, htmls, man pages, ... some of the are copy of each other.

Ideally, we should put html stuff into https://freemint.github.io/freemint, simplify / unify the beginners guide, mint.cnf description etc and have it as simple as possible. 

`gh-pages` branch allows us to have a separate yet related documentation branch for github.io: http://stackoverflow.com/a/21657266/21009

Another option is /docs folder on `master`: https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch (that we could keep all together -- both the html result and source in UDO or whatever)

**Comment by paulwratt** [comment]
how much of this has been done, whats already been reviewed, or whats left to review?

**Comment by mikrosk** [comment]
Lars has finished xaaes.hyp, @th-otto helped to convert it back to UDO so XaAES doc is more or less done. I just need find some time to publish xaaes docs as html, to make it more visible to the public.

FreeMiNT (user) docs are being done again by Lars, I have seen a preliminary version, looks pretty good.
