### ISSUE TITLE
Mouse flickering with taskbar.prg

### ISSUE THREAD

**Issue by mzryz** [freemint/freemint#200]
Dear mint'ers,

I am not sure if this is Mint or just taskbar related, but when taskbar.prg is running my cursor is always flickering. On off at about 1 flicker per second. When exiting taskbar this goes away. 

I had previously had this problem when taskbar was showing 'seconds' in the time area, but now happens all the time.

**Comment by mzryz** [comment]
![IMG_20200831_184350](https://user-images.githubusercontent.com/23113373/91750069-5de5b100-ebba-11ea-8ce2-27e8a0b6e53d.jpg)

**Comment by mzryz** [comment]
![IMG_20200831_184930](https://user-images.githubusercontent.com/23113373/91750336-d8163580-ebba-11ea-98d3-c952c96fb714.jpg)

**Comment by mzryz** [comment]
The CPU usage seems very high. I quit task bar and the bars go green/teal. But the actual CPU percent is very low, so I don't know.

**Comment by mzryz** [comment]
Machine is TT030 with AtiM64 graphics. 1024x768x256.

**Comment by mzryz** [comment]
Update: Flickering goes away when selecting 'auto-hide' for taskbar. Flicking re-appears when using either auto-top/always on top.

**Comment by skaftetryne** [comment]
On Mon, 2020-08-31 at 12:20 -0700, mzryz wrote:
> Update: Flickering goes away when selecting 'auto-hide' for taskbar.
> Flicking re-appears when using either auto-top/always on top.

What happens if you switch off the Taskbar clock? Nothing I would think
(hope!). Also, does this happen without Nova VDI?

Have been using Taskbar since 1996, with all kinds of MiNT-versions,
graphics cards etc without having this issue.

Jo Even

**Comment by mzryz** [comment]
Turning the clock off doesn't seem to help, I can't test without Nova easily without re-configuring my mint. For now I can get by with having it on auto-hide, not a perfect solution but it will do for now.

**Comment by skaftetryne** [comment]
On Mon, 2020-08-31 at 12:20 -0700, mzryz wrote:
> Update: Flickering goes away when selecting 'auto-hide' for taskbar.
> Flicking re-appears when using either auto-top/always on top.

I'm using NovaVDI on my Falcon/AB/Nova (Mach64), and see no such
flickering. Take a look at STA_VDI.INF in your auto-folder. There is a
setting there for allowing the VDI mouse-calls to switch the
mousecursor on/off. Set this to OFF.

I'm also using Taskbar under MiNT/XaAES on a Milan and on a Falcon060
using Videl/NVDI. No flickering there either. I suspect an issue with
NovaVDI.

Jo Even

**Comment by mzryz** [comment]
> On Mon, 2020-08-31 at 12:20 -0700, mzryz wrote: Update: Flickering goes away when selecting 'auto-hide' for taskbar. Flicking re-appears when using either auto-top/always on top.
> I'm using NovaVDI on my Falcon/AB/Nova (Mach64), and see no such flickering. Take a look at STA_VDI.INF in your auto-folder. There is a setting there for allowing the VDI mouse-calls to switch the mousecursor on/off. Set this to OFF. I'm also using Taskbar under MiNT/XaAES on a Milan and on a Falcon060 using Videl/NVDI. No flickering there either. I suspect an issue with NovaVDI. Jo Even

Thank you! This can be closed as solved now. Editing the STA_VDI as suggested by Jo fixed the flicking cursor issue. Thank you.
