### ISSUE TITLE
FreeMint 1-19-e2521230 w/ LightningVME driver Hubpoll CPU usage

### ISSUE THREAD

**Issue by stevenptimms** [freemint/freemint#202]
Dear Freemint team,

I have been in contact with the developers of LightningVME about abnormally high CPU usage in FreeMint in conjunction with the LightningVME drivers. 
The problem as I see it: The CPU usage of the 'hubpoll' processes steadily increases after boot, going from 5-10%, up to 30% after a minute. I have extensively tested the driver with the developer and he suggested we open an issue here, as he feels it may not be down to the driver. He also sent me an updated driver for testing which made no difference.
Nothing plugged in to the USB:
![nothing_in](https://user-images.githubusercontent.com/59610307/94006069-2d4afe80-fd97-11ea-8dff-a047d12798be.jpg)
Just 1x Logitech USB2 4 port hub:
![justhub](https://user-images.githubusercontent.com/59610307/94006074-320fb280-fd97-11ea-971e-2fa1b66aa259.jpg)
Logitech hub & USB Asix LAN plugged in:
![allin_hub_and_asix](https://user-images.githubusercontent.com/59610307/94006081-34720c80-fd97-11ea-819a-f280d0f85eeb.jpg)

As you can imagine this really slows down the machine during usage. I am using very latest FreeMint snapshot and Lightning VME drivers. Machine is a TT with 64mb fastram and NOVA mach64. Res 1024x768 256c.

**Comment by stevenptimms** [comment]
![91750336-d8163580-ebba-11ea-98d3-c952c96fb714](https://user-images.githubusercontent.com/59610307/94005894-e65d0900-fd96-11ea-9087-e6e3480a35f9.jpg)

Hubpoll processes over 30% each!

**Comment by DavidGZ** [comment]
Hi, thanks for the report. Normally I take care of USB issues but currently I'm not active regarding ATARI stuff, I try to keep track of what's going on but I've no time for development or investigations at the moment. I'll take a look if nobody address this issue before I'm active again, it could take weeks or months, I don't really know.

**Comment by czietz** [comment]
Maybe someone more familiar than me with MiNT kernel internals could look at the USB hub code in https://github.com/freemint/freemint/blob/master/sys/usb/src.km/hub.c. Are there e.g. any possible issues (such as race conditions) when using _two_ USB hubs? As you can see, @stevenptimms has two hubs and, therefore, two `hubpoll` threads. How does FreeMiNT's USB stack make sure that only the correct thread is being woken up?

**Comment by th-otto** [comment]
I guess we have to wait until David has time to look after the issue. Although i think i'm quite familiar with the internals, the USB stuff has always been implemented by him, and i don't have any possibility to debug this.

**Comment by mzryz** [comment]
The problem is solved! Thankfully the team at thunderstorm.de, I think this includes czietz, have solved the problem! I have tested the new driver and the issue has now been resolved. Thank you to all involved, I will close the thread. Any other users with this issue should update to the latest Lightning VME drivers once they have been updated to include this fix. Kind regards.

**Comment by stevenptimms** [comment]
The problem is solved! Thankfully the team at thunderstorm.de, I think this includes czietz, have solved the problem! I have tested the new driver and the issue has now been resolved. Thank you to all involved, I will close the thread. Any other users with this issue should update to the latest Lightning VME drivers once they have been updated to include this fix. Kind regards.

**Comment by czietz** [comment]
Of course, I'll contribute my changes back upstream to FreeMiNT as soon as I find time.

**Comment by DavidGZ** [comment]
Thanks a lot for taking care of the issue
