### ISSUE TITLE
Can someone here confirm if they have X server working on current kernel?

### ISSUE THREAD

**Issue by stevenptimms** [freemint/freemint#204]
I am unable to get the X11 server working on the latest Freemint. I have tried fresh installs of EasyMint updated to latest kernel & all supporting software. When running X.app the X console does not show, just appears to hang as a frozen process. This locks the current terminal window, upon opening a new terminal and trying Xeyes or xfonsel etc, the terminal says it is displaying but nothing is on screen. Tested on separate installations on Falcon & TT.

People have reported to me that they have had no issues with 1.18 kernel, but I am not aware if anyone has recently tried with the newer kernels.

I know this may not be a priority for many users, but lately I have been learning more about Unix and like the idea of testing X11 on my Ataris and seeing if forwarding works between machines etc etc. Lots of stuff to play with since they are networked.

**Comment by stevenptimms** [comment]
I recently learned that the X server requires (or used to require) sockdev.xdd to work. This file doesn't seem to be included in freemint anymore, so I tried using the file provided in the EasyMint distro but this made no difference.

**Comment by th-otto** [comment]
Hm, was sockdev.xdd ever part of FreeMiNT? I can't find any traces of it.

**Comment by jflemaire** [comment]
On Thursday, 19 November 2020 09:13:03 CET Thorsten Otto wrote:
> Hm, was sockdev.xdd ever part of FreeMiNT? I can't find any traces of it.

sockdev.xdd is part of the MiNT-Net RPM: http://freemint.de/en/?net

Cheers,
JFL
-- 
Jean-François Lemaire

**Comment by th-otto** [comment]
Looking further, it seems that this xdd is not a separate module anymore. Its functionality is supposed to be provided by sys_socketdev.c, but there are some ifdefs regarding OLDSOCKDEVEMU, not sure whether activating thise would make the X-Server usable again (or whether the code compiles at all)

**Comment by stevenptimms** [comment]
@th-otto 

I think the sockdev was not the right solution - as I have recently tested N.AES on the same system and the X server begins to work. I am starting to think the issue is in XaAES now.

**Comment by mzryz** [comment]
Proof: X server working in N.AES where as on the same system it displays nothing on XaAES. Fresh installs of mont. Latest kernels. There is some kind of regression in XaAES... I hope someone can fix it.

![Uploading PXL_20201215_194424719.MP.jpg…]()

**Comment by mfro0** [comment]
on the mailing list, you said it locks up the machine, here you say it just doesn't display anything?

**Comment by stevenptimms** [comment]
I found if you wait about 5 minutes eventually the xconsole appears in 
my more recent testing, and of course, then seems to lock.

By the way I find this a little confusing. Everyone here is a Freemint 
dev and presumably has a full mint installation available to them. If 
you have any queries all you need to do is try yourself and see what 
happens. I've tied this on multiple machines and I am sure this issue 
isn't unique to me and my installs.

But yes thanks for showing interest.

Cheers.

**Comment by stevenptimms** [comment]
Closing issue as I think it was just a strange font issue & nobody else seems to have a problem.
