### ISSUE TITLE
MENU_ISTART() broken

### ISSUE THREAD

**Issue by GokMasE** [freemint/freemint#212]
The AES function MENU_ISTART() is either broken or possibly added only as a dummy function. No alignment adjustments is carried out when this function is called with MENU_ISTART(MIS_SETALIGN,.....). 

MENU_ISTART() was introduced with AES 3.30.

**Comment by th-otto** [comment]
It is a dummy function currently: https://github.com/freemint/freemint/blob/9d9dfd610fdd7bbaa08a5cb74e3fcd840374afb0/xaaes/src.km/xa_menu.c#L864-L872

**Comment by GokMasE** [comment]
As could be expected, support for MENU_ISTART() is missing also in XaAES-Ozk (See [#241](https://github.com/freemint/freemint/issues/241))

**Comment by GokMasE** [comment]
Uploaded a test binary for MENU_ISTART().  The program allows you to select which entry in the submenu that should be in level with the entry in main menu. Tested with N.AES which has a working implementation of the funtion and it does give the expected results.

Since XaAES only has a dummy function for MENU_ISTART() this program may only be of real interest for anyone seeking to add the missing functionality.

[submenu_test.zip](https://github.com/freemint/freemint/files/8128443/submenu_test.zip)

**Comment by Perdrix24** [comment]
Do you have the source for the submenu test program? I would like it.

**Comment by GokMasE** [comment]
Yes, I still have the src although it is worth pointing out that it was written in GFABASIC:
[submenu_test_src.zip](https://github.com/freemint/freemint/files/8191562/submenu_test_src.zip)

The program takes advantage of some of the functions that was added in GBE v3.7+ so I'd strongly recommend downloading the very latest binary from Lonny's page before anything else:
[UnOfficial Home of GFA-Basic](http://gfabasic.net/)

Hopefully there are no significant problems or errors in the test program - it has been used to test the menu_istart() functionality of N.AES and could hopefully be of some value for anyone seeking to bring XaAES up closer to full AES4.1 compliance. 

**Note: You should also be aware of that according to the Atari Compendium AES versions <4.1 supporting menu_attach() contain a bug which causes the AES to crash when altering or removing an attached submenu.**

**Comment by Perdrix24** [comment]
Thanks. I'm using the program to test support of sub-menus in EmuTOS. The developer had asked for the source, since sub-menus in Papyrus were working but not in this test program. However, the test program is working under TOS 4 and MagiC.

**Comment by GokMasE** [comment]
> Thanks. I'm using the program to test support of sub-menus in EmuTOS. The developer had asked for the source, since sub-menus in Papyrus were working but not in this test program. However, the test program is working under TOS 4 and MagiC.

Ok, interesting to hear there is such development going in EmuTOS, I am hoping someone will look at finishing the implementation in XaAES at some point. It would be incredibly unexpected but certainly very nice if this little program can be of any help to EmuTOS developers :)

**Comment by GokMasE** [comment]
@xdelatour : Since you did a mighty fine job on adding the g_swbutton() function (now pushed), would you be interested to look into the missing menu_istart() by any chance?

**Comment by xdelatour** [comment]
Unfortunately it seems very complicated. At the present time I found another program that uses these functions (prg, C source, screenshots of XaAES/TOS404/MagiC/N.AES)
[devgem3.zip](https://github.com/freemint/freemint/files/8886003/devgem3.zip)

**Comment by GokMasE** [comment]
Right, I wasn't aware of that it might matter if the submenu to be aligned vertically also has the scrolling bit set. I can see why that might add another lovel of complexity.

**Comment by GokMasE** [comment]
@xdelatour, this got interesting! By sharing the test program in your previous comment, it seems like you managed to put the spotlight on a somewhat exotic feature that at this time is not implemented into XaAES:

Setting `mn_scroll = >0` (parameter in the MENU structure) is intended to initiate a special mode that makes only part of the menu initiated by menu_popup scrollable. As seen in the snapshots you supplied in the archive, not all of the AES's supports this feature. 

I'll try and write a separate report for this issue.

**Comment by mikrosk** [comment]
Here's the binary: [xaaes.km.zip](https://github.com/freemint/freemint/files/8935563/xaaes.km.zip)

I tried to verify it with the test app but I didn't get it ;-)

**Comment by GokMasE** [comment]
First of all - the patch does seem to do what it sets out to do - it will successfully adjust the vertical alignment of submenus according to the parameters sent in `menu_istart(MIS_SETALIGN,tree, imenu, item)`. This now seems to be yielding proper results - nice!

**However, a regression compared to current snapshots also crept in there:**

I discovered that after this patch was added, if a menu (not submenu) initiated through `MENU_POPUP(menu, xpos, ypos, mdata)`, is configured with `MENU` struct item `mn_item` set to >1 then XaAES will add an unwanted, negative offset to ypos.

To the best of my understanding:

- the `mn_item` parameter is typically used to specify which menu entry (menu index) should be the 1st one to visibly appear in the menu _when the menu has been configured to allow scrolling_.

- The xpos and ypos parameters decides the location of the upper left corner of the menu.

Prior to the proposed patch, the menu was accurately placed on the specified xpos/ypos regardless of the `mn_item` parameter, whereas setting this parameter to >1 will now add a negative offset to the y-position.

**Comment by mikrosk** [comment]
This is a build made from the patch published in https://github.com/freemint/freemint/issues/259#issuecomment-1160776444: [xaaes.km.zip](https://github.com/freemint/freemint/files/8946282/xaaes.km.zip), @GokMasE please give it a try (I'm not sure if I manage to do some testing myself these days).

And thank you for the thorough checking you've done, of course!

**Comment by GokMasE** [comment]
From a quick test, it seems that the y-offset problem is still present in this binary. (Build from June 21, 523317 bytes)

**Comment by xdelatour** [comment]
> * The xpos and ypos parameters decides the location of the upper left corner of the menu.
> 
No, xpos and ypos is where to display the upper left corner of the starting menu item set with menu_istart.

The description of menu_popup() can be found in:
- ["NEW AES/MultiTOS Programmer's Manual"](https://docs.dev-docs.org/htm/search.php?find=aes%204) (page 19, 5.3.7)
- ["Supplemental AES Documentation (1/25/93)"](https://docs.dev-docs.org/htm/search.php?find=jan%2025%201993) (page 20, AES.8)

`me_xpos - the left edge of where the starting menu item will be displayed`
`me_ypos - the top edge of where the starting menu item will be displayed`

**Comment by GokMasE** [comment]
Indeed - you are right, I am wrong.

In the case of my test program there is no `menu_istart()` used, but it appears the `mn_item` in the `MENU` struct has the same impact - this had me puzzled, but I guess it makes sense. And results are corresponding well to the output of N.AES in this regard.

**Comment by mikrosk** [comment]
So what it the outcome here? Was even the first patch (https://github.com/freemint/freemint/issues/212#issuecomment-1157624555) good or should I apply the second one instead? (https://github.com/freemint/freemint/issues/259#issuecomment-1160776444)

**Comment by xdelatour** [comment]
The first is probably better, I should be able to confirm that this evening

**Comment by mikrosk** [comment]
The first patch has been applied, @GokMasE please verify the latest XaAES build.

@xdelatour as usual, thanks for your contribution!

**Comment by GokMasE** [comment]
> The first patch has been applied, @GokMasE please verify the latest XaAES build.

**Right, I can confirm that menu_istart() seems okay in the snapshot tested (7d850b71) - cool stuff!**

I can only join in the choir here, huge thanks to @xdelatour for the excellent work.
(Again, I am sorry for mixing/messing things up during testing this)
