### ISSUE TITLE
TOSWIN2 + ext2 Volume crash at open ...

### ISSUE THREAD

**Issue by franklukas** [freemint/freemint#214]
b6facec3 020-060 package / Atari ST with PAK68/3-020 + 68881 FPU + 64MB Fastram

TOSWIN2 starts up from the xaaes.cnf and crash when the desktop appear. When I start it manually all is fine.

Second mistake is when I open up the ext2 unix partition teradesk crash.

BUS ERROR: User PC=1111868, Address: 0 (basepage=1448E00, text=1448E00, data=1469A3A, bss=146B5CE

**Comment by th-otto** [comment]
Does the reference to the commit mean those crashes did not appear with previous versions? That would be surprising, since the changes are only related to debug printfs, which are not in the release versions.

**Comment by franklukas** [comment]
With 314 it is the same error and QED crash too

**Comment by franklukas** [comment]
When I open up u:/ Teradesk crash too ...

**Comment by mikrosk** [comment]
That looks very strange, can you test on some other (more typical) machine like a Falcon or TT?

**Comment by franklukas** [comment]
Without the MACH32 Nova driver all is fine. So I must ask Idek what can it be. With a another machine with a PAK68/3-030  CPU and Nova MACH64 driver all is fine. The problem can be with the Nova driver and a 020 CPU !?!

**Comment by franklukas** [comment]
All the problems have nothing to do with the nova driver. Teradesk was the problem. It has a problem with a MC68020 CPU that has Fastram and 32kB Level 2 Cache, I not know! Thing 1.29 crash too.

By use JINNEE 2.5 all the problems disappeared. All works fine now ...

**Comment by th-otto** [comment]
Thats still strange. Neither Teradesk nor Thing do anything that would for example require to invalidate the CPU caches.

**Comment by franklukas** [comment]
I use Teradesk with MiNT/XaAES + Nova on a Atari TT and a Atari ST with a PAK68/3-030 + Fastram and have no problems with that setup ...

**Comment by th-otto** [comment]
Yes, i know, and thats even more strange. Apparently only the 68020 with 32K cache gives problems. But i have no idea why.

**Comment by mfro0** [comment]
Hmmmh. For me, EmuTOS + MiNT + XaAES + Teradesk work fine in Hatari with '020 + Alternate RAM?

Without being able to reproduce the problem I don't see much chance to debug.

**Comment by mikrosk** [comment]
I don't know Frank. First you write:

> Without the MACH32 Nova driver all is fine.

and then:

> All the problems have nothing to do with the nova driver. Teradesk was the problem.

To me it looks like the NOVA driver is still the problem and you just switched desktops to make it disappear.

**Comment by franklukas** [comment]
Setup + SM124 = all is fine

Setup + Nova Graphiccard = Teradesk crash when I open up u:/

When I use Jinnee all is fine, so there is a problem with Teradesk and the Nova Driver. Nova Driver 000 or 020-030 version make no difference.  Single TOS + Teradesk all is fine too.

**Comment by franklukas** [comment]
All problems solved. It was my fault because the running order from the auto folder was wrong. I put nvdi.prg after sta_vdi.prg (nova driver) and all problems are gone ...

**Comment by mikrosk** [comment]
Glad to see it solved, although it's quite scary what a wrong VDI order can do.
