### ISSUE TITLE
G_SWBUTTON not (successfully) supported

### ISSUE THREAD

**Issue by GokMasE** [freemint/freemint#217]
The extended AES object type 34 (G_SWBUTTON) is not successfully implemented. I can't tell if the object is simply ignored by renderer (since unsupported) or if it is implemented but non-functional. XaAES will in any case not draw such an object, although both N.AES and MagiC can handle it.

**Comment by lpgb** [comment]
For a reference point this works on NAES. Attached is a small test binary with source.

[test.zip](https://github.com/freemint/freemint/files/7698833/test.zip)

**Comment by mikrosk** [comment]
Does it work on xaaes-ozk? I doubt it but worth a try.

**Comment by xdelatour** [comment]
Here is an attempt to add G_SWBUTTON. 
I use this patch for my own usage (I don't know how presentable it is). 
Perhaps someone would like to review it?

Changes:

- xa_aes.h:   new SWINFO structure
- xa_appl.c:  appl_get_info(13) returns AGI_G_SWBUTTON
- draw_obj.c: add support for G_SWBUTTON in draw_object_tree()
- form.c:     Form_Button() manages click and double-click
- render_objc.c: d_g_button() draws the button

- k_init.c:     new static function api_object_get_swinfo()
- ob_inlines.h: new static inline function object_get_swinfo()
- xa_types.h:   xa_module_api updated

No changes:

- xa_rsrc.c, xa_rsrc_lang.c (no G_SWBUTTON available when loading RSC)
- obtree.c (pdlg, fnts and other duplicated trees don't have G_SWBUTTON)

Bugs:

-  Because the RSC file contains G_BUTTON, ob_spec points to a string (text of the button).
  XaAES calls ob_fix_shortcuts() to add an underscore on G_BUTTON and G_STRING
  (ob_state is OR'ed with OS_WHITEBAK).
  To avoid this, the text of the G_BUTTON must be filled with spaces (or any non-alpha-numeric char)

[gwbutton.patch.txt](https://github.com/freemint/freemint/files/8720716/gwbutton.patch.txt)

**Comment by mikrosk** [comment]
@GokMasE are you able to build a snapshot by yourself to give it a try?

**Comment by GokMasE** [comment]
Sorry, afraid not.
If someone can provide an xaaes.km ready to try I'd however be more than happy to check it out of course.

**Comment by mikrosk** [comment]
@GokMasE please give it a try (I haven't checked anything yet, I'm just curious about your feedback). Applied against latest master: [xaaes.km.zip](https://github.com/freemint/freemint/files/8732344/xaaes.km.zip)

**Comment by GokMasE** [comment]
I tested the xaaes030.km binaries from both of you, and it looks like the g_swbutton() call is working identially in both.

For the test I used the binary supplied with Lp earlier, and it does seem to function as expected.

As described by xdelatour, there in an underscore added to indicate a keyboard shortcut. In this exact example, there are then two objects having an underscore under their respective "o" char, but the ALT+O shortcut triggers the OK-button.

This might be a stupid question, but can the G_SWBUTTON in this example be altered/configured to have a (functional) keyboard shortcut assigned?

![g_swbutn](https://user-images.githubusercontent.com/65512522/169406113-8918f551-31c3-419d-afd8-ec9b86861548.png)

**Comment by mikrosk** [comment]
As @lpgb made it in GFA, I'll let him to change it as I have literally never ever compiled a GFA source. ;-)

**Comment by lpgb** [comment]
I think he means the key combos are assigned by xaaes itself. The issue might be that both buttons are assigned the same letter. I'm not sure how xaaes handles conflicts like that.

**Comment by xdelatour** [comment]
Shortcuts are added by ob_fix_shortcuts() and checked by ob_find_shortcut().
Both are in obtree.c

ob_fix_shortcuts() is called only by rsrc_load() (and internally by form_center() - if the resource is not loaded from a file - and by create_new_pdlg()).

When ob_fix_shortcuts() is called by rsrc_load(), the button is still a G_BUTTON, so an underscore is added on the first letter, 'B' of 'Button'.
There is no conflict between B, O and C.
Later, the text is overwritten with 'opt 1' but the underscore stays on the first letter (because the shortcuts are not created again). 

If you put 'opt 1' in the RSC file (instead of 'Button'), the underscore is added on the second letter because O is already used by 'Ok' (default button seems to have priority on others buttons).

Despite that, shortcut can not work because ob_find_shortcut() looks for shortcuts only for G_BUTTON and G_STRING (and G_OBLINK but I don't know what it is).

For the moment, I can just disable shortcut on G_SWBUTTON.

**Comment by GokMasE** [comment]
**`ALT+<key>` shortcut ponderings:**

I agree that it would probably make sense to disable the shortcut indication of G_SWBUTTON to avoid confusion - at least for the time being. 


**Cycling order:**

One interesting side note is that if you use TAB to move the focus caret (red dotted rectangle) to the G_SWBUTTON() and then hit SPACE (or INSERT, if you haven't discovered "`spaceXinsert = true`") to select it, the cycling of the entries is actually carried out backwards ("Opt 1", "Opt 3", "Opt 2"). This does IMO feel a bit awkward, and it would be cool if it could be sorted.

_I started wondering if selecting the object through SPACE is maybe done through simulating a right button click?_

If you click the G_SWBUTTON() with the left mouse button the cycling order is the chronological one ("Opt 1", "Opt 2", "Opt 3"), whereas if you click using the right button, the order is indeed reversed.

**Comment by xdelatour** [comment]
Thanks all for your feedback!

Some updates:

- Shortcut is now removed on changes (underscore still drawed on the first form_do() but there is the same problem with G_POPUP for the same reason - G_POPUP is a G_BUTTON when loading the RSC-file and its ob_state is updated later)
- FBF_KEYBD is checked to distinguish between mouse event and keyboard event (tested with INSERT key, I don't know where to put spaceXinsert).

[gwbutton-20220522.patch.txt](https://github.com/freemint/freemint/files/8748960/gwbutton-20220522.patch.txt)

**Comment by GokMasE** [comment]
Ok, so if I understand this correctly, to prevent the underscore from being drawn in the first place, a more generic solution is needed - something that can kick in for any obj type that is changed after RSRC_LOAD() and before being updated is seen as a candidate for utilizing shortcuts. A dedicated function for object types being "transformed" maybe?
Perhaps this should be filed as a separate issue?

As for the cycling issue, if that has potentially been fixed I would be happy to try it out in case someone can provide a test binary.

The setting "spaceXinsert" is something you can add to app-options in XAAES.CNF

**Sidenote:** From what I gather, back when keyboard navigation scheme was changed to include some listbox stuff too, the SPACE key was suddenly used as the default key to address those - neatly ignoring the fact that SPACE had been already been established as the shortcut key to select the object currently in focus (marked by the red rectangle). So in essence, an easily accessed key for a function likely used more often, was changed to a more awkwardly positioned key - leaving SPACE to handle the more exotic listboxes. Only guess I have is it may be something to do with the file selector, since that one (I think) is using the listbox stuff. I would certainly prefer the default setting being the other way around, but since it can be configured I guess I can live with it.

**Comment by mikrosk** [comment]
@GokMasE here's the updated build for testing. When you find time, please give it a try. :)

[xaaes.km.zip](https://github.com/freemint/freemint/files/8785816/xaaes.km.zip)

**Comment by GokMasE** [comment]
Thanks for sharing the binary, I have tested it for a while this evening:

1. I can confirm that the cycling is not carried out in the correct order when triggering the G_SWBUTTON() to cycle by making it the focused object and hitting SPACE (or INSERT, depending on cnf setting). This change makes it feel a lot better in this regard.

However, this seems to have induced a related change too -  it seems like right clicking the G_SWBUTTON() now results in the cycling going the "normal" way too, rather than reverse order. I admit I found it clever of XaAES to allow for the backwards kind of cycling when using right mouse button - much like how the scrolling arrows of the window slider reacts.

**Would it be possible to keep the reverse order for right mouse button, while still having the SPACE/INSERT triggering cycling the cycling in "normal" order?**

2. I can also confirm that the underscore indicating an ALT+key shortcut is there initially, but removed first time the G_SWBUTTON() is selected/cycled.

**Comment by xdelatour** [comment]
> However, this seems to have induced a related change too - it seems like right clicking the G_SWBUTTON() now results in the cycling going the "normal" way too, rather than reverse order.

This behaviour seems to be unrelated to my patch, a right-click on OK or Cancel closes the dialog, even with older releases of XaAES (tested with MiNT 1.18.0/XaAES ). Left and right clicks seems to have the same effect. I still don't know why.

> EDIT: Lp just told me that N.AES uses double click to trigger reverse order

Yes, this is the right behaviour on both N.AES and MagiC.

**Comment by GokMasE** [comment]
I somehow never go to even test the doubleclick - indeed, double click works like on N.AES / MagiC already! That is all good then.

As for the right button action - you are right, this behaviour was not changed - I mixed that up with the focus + SPACE/INSERT thingy. Sorry about that, I guess I blame it on the late hour.. 

That said, the idea itself is not necessarily bad - since right button isn't used at all in N.AES for G_SWBUTTON() I suppose it could be called an extended feature if we decide to let XaAES utilize it. 

If so, having that linked to backwards cycling, the right click would have a defined and unique purpose.


Well, just a thought.

**Comment by xdelatour** [comment]
> If so, having that linked to backwards cycling, the right click would have a defined and unique purpose.

Just replace
`if (dc)`
with
`if (dc || (md->state & MBS_RIGHT))`

Regarding keyboard navigation, [only a left click is simulated](https://github.com/freemint/freemint/blob/master/xaaes/src.km/form.c#L911) when INSERT, RETURN, UNDO or a shortcut is pressed. 

From what I understand, others keys are ignored and have no effect (TAB, SHIFT, ... having been handled previously by Form_Cursor).

**Comment by mikrosk** [comment]
> Just replace (in form.c)
if (dc)
with
if (dc || (md->state & MBS_RIGHT))

@GokMasE  [xaaes.km.zip](https://github.com/freemint/freemint/files/8791857/xaaes.km.zip)

**Comment by GokMasE** [comment]
Cheers @mikrosk and @xdelatour, much appreciated.

Right mouse button now indeed inverts the cycling order of the G_SWBUTTON (same result as when double clicking it).

Personally I have to say I quite like the way it works now. Does anyone feel differently?

**Comment by mikrosk** [comment]
I've cleaned up the code a bit. Should be pushed now.
