### ISSUE TITLE
Wrong usage of __LITTLE_ENDIAN

### ISSUE THREAD

**Issue by th-otto** [freemint/freemint#222]
At 
https://github.com/freemint/freemint/blob/3a6dcdd6a49e9889bde33b9b15c00730a9d80cad/sys/usb/src.km/usb.h#L298 there is a check for __LITTLE_ENDIAN. That usage is wrong, since this value is always defined when including <endian.h>:

https://github.com/freemint/mintlib/blob/824e57a7632c227de6807622b2782e018732b3f2/include/endian.h#L33

It should rather read

```
#if __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__
```
@DavidGZ , could you look into that if time permits?

Update: those macros are at least used in the ethernat and netusbee drivers.

**Comment by czietz** [comment]
Fortunately, `__LITTLE_ENDIAN` is not defined (albeit only by chance) when compiling the EtherNAT and NetUSBee drivers. Making this change (for debugging, only, of course):
```
#ifdef __LITTLE_ENDIAN
# define swap_16(x) (x)
# define swap_32(x) (x)
#warning little endian
#else
# define swap_16(x) __swap_16(x)
# define swap_32(x) __swap_32(x)
#warning big endian
#endif
```
... returns "big endian" when compiling both drivers.

Still, Thorsten is right: This is an error and should be fixed. Otherwise, as soon as someone includes _endian.h_ the drivers will be wrong.

**Comment by DavidGZ** [comment]
Hi @th-otto , thanks for detecting this.

I guess the cleanest solution would be to remove completely that code and use in the drivers the macros defined in mint/endian.h

https://github.com/freemint/freemint/blob/3a6dcdd6a49e9889bde33b9b15c00730a9d80cad/sys/mint/endian.h

Although it seems a straightforward change I should test the drivers, unfortunately I can't do it now. So in the meantime I will add your proposed fix.

**Comment by DavidGZ** [comment]
Fix with 5d6e8d952df0000de2b91df3b5708ec1f7d44298

**Comment by th-otto** [comment]
> I guess the cleanest solution would be to remove completely that code and use in the drivers the macros defined in mint/endian.h

Yes, for MiNT that makes sense. But Christian pointed out, that originally these files are from U-Boot (https://github.com/u-boot/u-boot/blob/a4262e5506bf967c4ad07f86442c1f461af22283/include/usb.h#L304). So either that problem should be reported there too (they don't seem to track issues in the github repo), are you have to be careful should you ever update those files with newer versions.

**Comment by DavidGZ** [comment]
I think there aren't problems in U-Boot sources, I guess the macro __LITTLE_ENDIAN would be only defined for little endian platforms there.

When we first imported the USB files from U-boot we imported most of the byte order headers files too, later we removed them in favour of the byte order files already present in MiNT sources, so I think the potential problem you found out was generated when I made that clean up. 

As you said if we decide to import a new version of that file we should be aware of this issue.

**Comment by th-otto** [comment]
> I think there aren't problems in U-Boot sources, I guess the macro __LITTLE_ENDIAN would be only defined for little endian platforms there.

They would suffer from the same problem. MintLib is based on (a quite old) version of glibc, and the <endian.h> on my linux box still looks quite similar, and also unconditionally defines __LITTLE_ENDIAN. Also for U-Boot this might be even more important, i guess most of the machines where it is used are indeed little-endian. But of course that's not our problem ;)
