### ISSUE TITLE
Purpose of minthat.prg

### ISSUE THREAD

**Issue by czietz** [freemint/freemint#225]
Because of [this forum thread](https://www.atari-forum.com/viewtopic.php?f=126&t=40663) I was wondering what purpose _minthat.prg_ (included in snapshot builds) still serves. Yes, it is built with `OLDTOSFS` enabled:
https://github.com/freemint/freemint/blob/b91b7c5d856bb7d8e5205d97ab185fe25de6283e/sys/KERNELDEFS#L122
... but it does not work with Hatari's GEMDOS drive emulation, either:
![grab0001](https://user-images.githubusercontent.com/9830685/124001655-252e8800-d9d5-11eb-9ffa-69f00319695a.png)
(Tested by manually renaming _minthat.prg_ to _mint000.prg_ so that it gets loaded.)

And when using an ACSI/IDE/SCSI HD image, one can use the regular FreeMiNT kernels under Hatari. Which is the use case  that _minthat.prg_  serves?

**Comment by DavidGZ** [comment]
This thread have some background about this issue:

https://mikro.naprvyraz.sk/mint/201502/msg00114.html

**Comment by czietz** [comment]
Maybe I missed the crucial detail in that mailing list thread, but the purpose of _minthat.prg_ is still not clear to me.

**Comment by mikrosk** [comment]
I think the moral story of that thread was that the OLDFS was supposed to work and for some reason it doesn't anymore.

**Comment by czietz** [comment]
Well, I seem to have identified and fixed the issue. This is _minthat.prg_ with OLDTOSFS running from a GEMDOS emulated drive C: in Hatari:

![grab0001](https://user-images.githubusercontent.com/9830685/124156212-a2bacc80-da97-11eb-9e0e-2428953942b1.png)

Expect a patch / pull request as soon as I have some time for it.

**Comment by czietz** [comment]
Confirmed to be working now with the snapshot build of https://github.com/freemint/freemint/commit/b44c975ecbc4a36cc2d90251622e24650c2852d4.
