### ISSUE TITLE
XaAES: form_error(-num) displays form_error(num)

### ISSUE THREAD

**Issue by xdelatour** [freemint/freemint#228]
For example, form_error(-33) displays "Bad argument" instead of "No such file or directory" (such as Geneva and N.AES do, according to theirs documentations - not tested).

In /xaaes/src.km/xa_form.c, lines 839 to 840 : 
`if ( num < 0 )
    num = -num;` 
Whereas to get MSDOS code from gemdos error code : 
`num = ~num - 30;`

**Comment by xdelatour** [comment]
Here is the patch to use the right MS-DOS code from the negative GEMDOS error code:
[xa_form.c.patch.txt](https://github.com/freemint/freemint/files/7963759/xa_form.c.patch.txt)

**Comment by th-otto** [comment]
Oops. Somehow missed that. Should be fixed now. Of course, allowing negative values is only an extension, originally that function is documented as only accepting positive (MSDOS) error codes, and if your application uses that, you will get correct error alerts.
