### ISSUE TITLE
ETH.PRG bombs out in desktop

### ISSUE THREAD

**Issue by mikrosk** [freemint/freemint#236]
I was just playing with USB4TOS drivers (+BLITZ.PRG from the Lightining) - I have noticed that ETH.PRG freezes the whole system after getting into desktop. I don't have any ASIX network card connected so it's no big deal for me to disable it but still, I think it shouldn't do it. :)

Latest snapshots + Lightning's BLITZ.PRG v303 + one USB stick inserted.

**Comment by Perdrix24** [comment]
I wonder if this driver is still useful. You can use a Asix USB-to-Ethernet adapter with a Sting driver, see https://github.com/czietz/usbsting. I once tried it and it works with NetUSBee.

**Comment by mikrosk** [comment]
@Perdrix24 actually this is an interesting question -- what exactly is ETH.PRG supposed to do? It isn't a Sting driver, is it? So what a network driver for TOS actually means?

Anyway, to make this report even worse, it doesn't work with the ASIX device at all, it crashes too. I've verified that the device works nicely with @czietz's usbsting.

**Comment by Perdrix24** [comment]
@mikrosk I don't know. @DavidGZ do you know what ETH.PRG is for?

**Comment by DavidGZ** [comment]
> @mikrosk I don't know. @DavidGZ do you know what ETH.PRG is for?

I have no idea. Going through the code and some threads in atari-forum, my guess is that it was a work in progress by Alan which was never finished before the driver by Christian and Roger was finally released.

**Comment by mikrosk** [comment]
Hmm, I guess this means we shouldn't by really distributing it. :-)

Before having the ASIX adaptor I thought that it has some use but it seems that I was wrong.

**Comment by atic-atac** [comment]
Right, ETH.PRG was work in-progress, which should be able to load the ASIX driver. But ETH.PRG was meant to be a wrapper for STiNG which was never completed.
