### ISSUE TITLE
AtariForge is down

### ISSUE THREAD

**Issue by vinriviere** [freemint/freemint#24]
Just a quick issue to say that AtariForge is currently down. So it also impacts our (new) MiNT Mailing List. Fortunately, we still have GitHub to communicate :+1:

**Comment by mikrosk** [comment]
Yeah, I noticed that too yesterday. It seems to be working now. Anyway, it had a positive impact on me, I finally kicked myself to switch to git clone in my https://github.com/mikrosk/m68k-atari-mint-build/commit/09df91369a0104e69e7170ca8359489f0f571386 :)
