### ISSUE TITLE
XaAES-current vs. XaAES-ozk

### ISSUE THREAD

**Issue by mikrosk** [freemint/freemint#241]
Just to write down observations made mostly by @skaftetryne and @gokmase. In the future we can link concrete github issues to them.

Features  missing in Ozk's (2010) XaAES build and present in current XaAES builds:
- "configurable" gradients (ozk's version contains only one hard gradient colour)
- translations
- integrated bubble gem
- custom palette for <= 256 colour resolutions
- switchable keyboard tables
- singletask mode (but has broken keyboard)
-  Control+Alt+Home to force a redraw of the screen
- Control+Alt+TAB to switch applications
- When closing the last open window of an application with a menu, the menu still has focus (perhaps configurable by `clwtna` in xaaes.cnf)
- 1 pix window frame
- xaloader doesn't load xaaes\<CPU\>.km
- realtime moving the vertical slider in list boxes (used in eg. file selector, system window/environment listing, task manager) will result in a nervously "jumping" movement of the content when moving slowly downwards.
- support for on the fly resolution change
- Support for function G_SWBUTTON() (see https://github.com/freemint/freemint/issues/241#issuecomment-1159740161)
- https://github.com/freemint/freemint/issues/300 is partly affecting xaaes-ozk as well (see https://github.com/freemint/freemint/issues/241#issuecomment-1494159911)

Identified bugs not present in Ozk's XaAES:
- broken keyboard navigation (https://github.com/freemint/freemint/issues/337#issuecomment-2116067795)
- broken toolbars (#230, #231)
-  IBOX is drawn with frame if specified
- https://github.com/freemint/freemint/issues/337
- https://github.com/freemint/freemint/issues/375

Possible way of development for Ozk's XaAES (easily applicable also for the current XaAES):
- external taskmanager
- external file selector
- remove system window
- "about" window simplified
- better hotkeys (defined API, cleaner design in comparison to current xaaes)
- better wallpaper (ditto)
- get rid of the "clients" submenu alltogether
- AES rendering code moved from the kernel module to a separate library, similar to how MagiC allows external modules to draw window frames but for all AES objects.
- create an API to make the XaAES listbox functions available to user processes? (if we want to recreate processes like File Selector and Taskmanager as standalone processes in the future, we would perhaps not want to do that without access to the native listbox support, using real sliders/widgets)

Possible high-level goals:
- AES. No more, no less. Implement the APIs, make sure they work.
- Performance and memory footprint that makes it attractive for real Atari machines sans accelerators and graphics cards.
- Constantly re-iterate that we're all friends and want the best for our Atari-machines and clones.

**LATEST BUILD COMPATIBLE WITH 1.19 KERNEL:** [xaaes-ozk-20240903.zip](https://github.com/user-attachments/files/16853729/xaaes-ozk-20240903.zip)

**Comment by skaftetryne** [comment]
On 11.02.2022 14:56, Miro Kropáček wrote:

>   * IBOX is drawn with frame if specified

The other way around - in "OZK" XaAES ibox is drawn with a frame if 
ob_spec defines one, while current XaAES does not.

Jo Even

**Comment by mikrosk** [comment]
Moved to xaaes-current bugs, thanks.

**Comment by lpgb** [comment]
Actually toolbars seem to work, but the borders are not drawn. Perhaps partially working. ;)

**Comment by skaftetryne** [comment]
On 11.02.2022 15:26, Lon Pursell wrote:
> Actually toolbars seem to work, but the borders are not drawn. Perhaps 
> partially working. ;)

XaAES toolbars are more feature-rich than standard toolbars, basically 
you can put an entire dialog in the toolbar and XaAES will in theory 
handle this for you. So free windowed dialogs. There is an example 
somewhere in the source-tree, but if you test this it only partially works.

This should either be fixed (but will the feature be used?) or removed 
(simplifies code).

Jo Even

**Comment by mikrosk** [comment]
@lpgb I was referring to #230 but good point, applies to #231 as well.

**Comment by GokMasE** [comment]
**Bug in MENU_ATTACH(me_remove,...)**

XaAES-ozk does have a bug that is not present in XaAES-current, regarding **menu_attach()** in mode 2 (me_remove).

In this mode, XaAES is supposed to remove an attached submenu, and according to TOS.HYP and Compendium, the last parameter (mdata, address to MENU structure) should then always be a NULL pointer. See here:

https://freemint.github.io/tos.hyp/en/menu.html#menu_attach
https://freemint.github.io/tos.hyp/en/aes_structures.html#MENU

However, XaAES-ozk will not remove the submenu unless the last parameter is set to <>0 which is clearly wrong.
Interestingly it seems that ANY value (including negative) except the documented NULL results in a removed submenu.
Sending the call according to docs (with mdata set to NULL) will still make the call return "1" (success), while in reality it did not de-attach the desired menu.

It would appear likely that it should be possible to fix this by just looking for mdata=NULL instead of mdata<>NULL.

**Comment by GokMasE** [comment]
**Quirky movement in vertical sliders of list boxes (downwards only!)**

In XaAES-Ozk, realtime moving the vertical slider in list boxes (used in eg. file selector, system window/environment listing, task manager) will result in a nervously "jumping" movement of the content when moving slowly downwards.

(This bug does not seem to be present in XaAES-current)

**Comment by GokMasE** [comment]
**Problems transfering the pointer to the text buffer in wind_get(handle, WF_NAME)**

It seems there are problems in XaAES-Ozk with wind_get(handle, WF_NAME,..) were the buffer passed in INTIN2/INTIN3 is not handled correctly on the XaAES side, resulting in BUS ERRORs. The problem can sometimes (but not always) be cured by a reboot, but it is always consistent within sessions.

Looking in the commit history it seems there has been a bugfix commited (83ef18ed368eff48501a527dc311021b0f2da468) in 2018  by @th-otto that did address errors in handling of the text buffer pointer within wind_get(handle, WF_NAME,..). Since the problem has not been possible to reproduce in XaAES-current, this might be a good candidate for "cherry picking".

**Comment by jflemaire** [comment]
On Thursday, 24 February 2022 12:11:44 CET Joakim wrote:

> It seems there are problems in XaAES-Ozk with wind_get(handle, WF_NAME,..)
> were the buffer passed in INTIN2/INTIN3 is not handled correctly on the
> XaAES side, resulting in BUS ERRORs. The problem can sometimes (but not
> always) be cured by a reboot, but it is always consistent within sessions.

How is it possible that a reboot does not cure the problem? I don't 
understand.

Cheers,
JFL
-- 
Jean-François Lemaire

**Comment by GokMasE** [comment]
> How is it possible that a reboot does not cure the problem? I don't understand. Cheers, JFL -- Jean-François Lemaire

Given the nature of the problem, it seems likely that XaAES-Ozk is doing something funky when merging the 2 WORDs (upper and lower word of the pointer to the text buffer) - into a LONG.

Why it works in some sessions and not others, I have no clue.

**Comment by mikrosk** [comment]
> Problems transfering the pointer to the text buffer in wind_get(handle, WF_NAME)

Fixed & uploaded. @GokMasE basically did all the hard work. ;-)

**Comment by GokMasE** [comment]
I can confirm that the issue with wind_get(handle, WF_NAME) is gone for me after installing todays xaaes.km
Since this is one of the few really serious bugs that have surfaced after the "xaaes reboot", I appreciate this massively!

Thanks for putting the effort in @mikrosk :)

**Comment by GokMasE** [comment]
Support for function G_SWBUTTON() was added to XaAES-current branch as of https://github.com/freemint/freemint/commit/540995b3b406e91930d4fdc91174fa460554a111 - this needs backporting to XaAES-Ozk.

**Comment by mikrosk** [comment]
> Support for function G_SWBUTTON() was added to XaAES-current branch as of [540995b](https://github.com/freemint/freemint/commit/540995b3b406e91930d4fdc91174fa460554a111) - this needs backporting to XaAES-Ozk.

Easier said than done. This whole block had been added: https://github.com/freemint/freemint/blob/63da70ba59baaa1389b707b32c1580b736dcaa18/xaaes/src.km/draw_obj.c#L949-L1005 in commit 63da70ba in usual Helmut fashion where I have to add just one more `case` (originally it came via https://github.com/freemint/freemint/commit/5e704435, just at the moment `helmut-enhancements` was created). 

Trouble is that `if` actually requires handling of `XAWS_RESIZED` (added in the very same commit) and affects e.g. toolbars, too (not to mention that even adding of `XAWS_RESIZED` is very risky, I may easily overlook some seemingly unrelated code).

**Comment by mikrosk** [comment]
#212 has been backported, zip archive updated.

**Comment by GokMasE** [comment]
Bug #278  has been fixed in XaAES-current, would a backport to XaAES-Ozk be doable?

**Comment by GokMasE** [comment]
Bug #300 is partly affecting xaaes-ozk as well - mouse clicks are sent to the "invisible toolbar", but the toolbar buttons will not be redrawn as they are clicked. A fix should ideally be applied to xaaes-ozk of course, but perhaps it would be best to wait until @xdelatour has looked into a working solution for xaaes-cur - perhaps it could then simply be backported to xaaes-ozk.

**Comment by mikrosk** [comment]
#278 has been backported to xaaes-ozk and attached to the first post.

#300 is waiting for @GokMasE's input.

**Comment by GokMasE** [comment]
#344  (which was recently fixed in xaaes-cur) is present also in xaaes-ozk.

**Comment by mikrosk** [comment]
#344 & #347 backported.
#300 put on hold until resolved.
Archive updated.

**Comment by mikrosk** [comment]
Btw, while talking to @GokMasE, I have realised an interesting thing. @th-otto likes to state how the effort of taking this xaaes as base and carefully cherry-picking just the useful stuff is a futile effort because Ozk left in 2010 and Helmut stopped in 2019, so that's nearly 10 years of commits, right?

Wrong.

Looking at git history I see  that Helmut was actually contributing to _master_ branch of XaAES in 2010 -  2013. Then he switched to helmut-enhancements and was working there between 2013-2019, just for himself. So that is _way better_ than we had thought.

Of course that opens question whether we shouldn't look into his branch and start picking things from there but that's for another debate.

Still, the amount of work to really start where Ozk had left is massive. Especially due to the size of Helmut's commits. But now it at least seems possible.

**Comment by skaftetryne** [comment]
> * dead menu for a few seconds after launching a program

I have not been paying attention for months, but while playing with the latest snapshot on my MonSTerbo'd STE last night I noticed that this bug is gone now.

**Comment by mikrosk** [comment]
I wonder how is that possible. @GokMasE, @lpgb can you also confirm that there's nothing odd? If so, that would be great, one more item off the (very short now) list.

**Comment by GokMasE** [comment]
Regarding the "dead menu" syndrome, I am afraid I have never experienced that one on my setup.

**Comment by lpgb** [comment]
Not noticed that dead menu syndrome, but then xaaes isn't my daily driver either. Atm I can't reproduce such symptoms.

**Comment by mikrosk** [comment]
I have given this issue a lot of thought. Especially after the recent discussions on Discord I have realised that my assumptions were basically wrong: I thought that providing this build would attract a small but visible group of people who refuse to upgrade to 1.19.cur kernels because of some fundamental XaAES bugs (see the first post).

However as it turned out, those people are also very conservative / have additional requests: making the recent kernels work with N.AES, virtual consoles etc so basically they need to have the bugs fixed and old XaAES alone is not going to make them switch from 1.16 kernel.

And looking at the list of bugs not present in xaaes-ozk... we should do just that. Fix the bugs. There are two main areas, toolbars and keyboard navigation, it surely isn't rocket science.

I have updated the snapshot in the first post, for the last time now. It contains https://github.com/freemint/freemint/pull/349, https://github.com/freemint/freemint/issues/357 and https://github.com/freemint/freemint/issues/344 fixes and that's it. I have also added the xaaes timeline and link to this issue also to https://github.com/freemint/freemint/wiki/XaAES so it's not totally buried as there are still some nice ideas for future development.

Also, I have moved my `before_helmut` branch into https://github.com/freemint/freemint/tree/xaaes-ozk for easier visibility.

What to say more... see you while bugfixing current kernel / xaaes, both have come a looong way since Alan's / Helmut's departure.

**Comment by GokMasE** [comment]
I ran into an issue where using pexec(0) to load and run a second binary from within an application would end up freezing XaAES-Ozk.

When running the GFA code below (which expects to find a dummy prg called "test.prg" in the same dir), upon return from the pexec call, the program will continue normally and terminate - but next time you try to access the AES in any way (utilize the menu bar, move or top a window, etc) XaAES-Ozk will freeze up completely:

```
$M65536                                 
INLINE fname%,1024
fname$="test.prg"                       
CHAR{fname%}=fname$                       
cmd$="cmdline 1 2 3 4 5 6 7 8 9 0 "       
cmd%=fname%+9                           
BYTE{cmd%+0}=LEN(cmd$)                   
CHAR{cmd%+1}=cmd$                         
ret%=PEXEC(0,fname%,cmd%,0)               
IF ret%<0
  PRINT "PEXEC failed and returned a negative LONG: ";ret%
ELSE
  PRINT "PEXEC was successful and returned an INT: ";WORD(ret%)
ENDIF
SYSTEM   
```

What is particularly interesting here is:

1. The problem does not appear with xaaes-cur
2. The problem will be completely bypassed if you insert a line with `~EVNT_TIMER(0)` immediately after the pexec call.

Attached is a tiny archive with 2 version of the binary doing the pexec call (`pexec06a.prg` will cause a freeze, `pexec06b.prg` will not) and also the dummy prg `test.prg`.                           
                           
[pexec_tst.zip](https://github.com/user-attachments/files/16856020/pexec_tst.zip)
