### ISSUE TITLE
EmuTOS/V4SA-patch

### ISSUE THREAD

**Issue by shoggoth77** [freemint/freemint#245]
OLs EmuTOS fork for the Vampire V4SA supports the Falcon video XBIOS and the Falcon way of passing the resolution/modecode to v_opnwk(). It was decided that the values for _VDO and _MCH was set to 0x60000 to avoid clashes with Aranym. XaAES checks explicitly for the Falcon _VDO cookie value however. This small patch makes XaAES check for 0x60000 as well, to allow the resolution/modecode to be passed to v_opnwk() on the V4SA as well.
[patch.diff.gz](https://github.com/freemint/freemint/files/8101881/patch.diff.gz)

**Comment by th-otto** [comment]
Who dediced that values? IMHO a bad idea, because no existing program is prepared for such values.

**Comment by shoggoth77** [comment]
That’s the whole point, Thorsten. New hardware, new value.

I erroneously said that _MCH had this cookie value too, but it’s -1, and will remain -1 until Atari-compatible hardware is added.

Apart from that (my bad), what’s the problem with new hardware identifying itself as new hardware? Having a _VDO value of 0x30000 would be to claim video hw compatibility with the Falcon, and while this machine can display Atari-compatible screen resolutions, it doesn’t have a single Atari-compatible hardware register.

**Comment by shoggoth77** [comment]
The values were decided by OL and me btw. The _VDO cookie indicates video hw and bios capabilities afaik. At least that's how it's been used in practice, and toshyp defines it as:

"Video hardware

The upper WORD is used the coarse classification. This can be:

-1 =	Non-ST-compatible hardware; in this case all hardware accesses must be avoided
 0 =	Atari ST (260 ST, 520 ST, 1040 ST, Mega ST, ...)
 1 =	Atari STE (1040 STE, Mega STE, ST Book)
 2 =	Atari TT
 3 =	Atari Falcon030
 4 =	Milan
The lower WORD is reserved for finer differences."

Aranym uses the value 5. Milan sports a severely mutant incarnation of the Falcon video XBIOS, don't know how compatible it is. On Aranym/EmuTOS, It seems fully compatible to the Falcon implementation.

Re-using some existing value would imply having that hardware available to the application/system, and that's not the case. The Vampire has Vampire hardware. Hence ending up using a new value. Benefit - existing stuff won't assume things are available that isn't there, and providing a familiar API for anyone wanting to support the Vampire - i.e. Falcon coders can support the Vampire, and Vampire coders can support the Falcon, and expect stuff to work.

If you have a better suggestion, I'm all ears obviously. Can you please elaborate what the problem is, Thorsten.

**Comment by mikrosk** [comment]
Does that mean that Milan's `v_opnwk` does _not_ support this way of passing the modecode?

Btw why 0x60000 and not 0x50000?

**Comment by shoggoth77** [comment]
Milan use a mechanism similar to that of the falcon, but the mode-value is 7 instead of 5.

**Comment by mikrosk** [comment]
While we are at it, where the Aranym's _VDO value comes from? I see it sets `_MCH` but not `_VDO`. Are you sure it is set at all?

**Comment by shoggoth77** [comment]
Ah, right. 0x50000 is used for the _MCH cookie, but since Aranym has VIDEL/Falcon-compatible hw it uses 0x30000 for the _VDO cookie. This can be found by just searching for the _MCH-cookie in the Aranym sources.

0x60000 was chosen as to make sure not to clash with Aranym.

**Comment by th-otto** [comment]
Aranym only sets the machine cookie when loading TOS, not when loading EmuTOS. The value can be configure on the config file, and defaults to 0x50000. And the VDO cookie is not set at all.

But why can't -1 be used for the _VDO cookie, indicating non-atari video?

**Comment by shoggoth77** [comment]
It might make sense to be able to check for Vampire-compatible video. It would also be inconsistent, given how the value is defined for the Milan (which only has PCI graphics).

How would one distinguish the Vampire implementation (which also has a proper video XBIOS attached to it) from some other implementation? Should applications for '-1', and then guess the video capabilities (and hence XBIOS capabilities) by looking at some other cookies instead?

**Comment by mikrosk** [comment]
Ok then, so Vampire actually can use 0x60000 for `_MCH` and 0x50000 for `_VDO`. 

As I see it, it is the check in XaAES which is wrong; Vampire doesn't have to enable any Atari-compatible flags if it doesn't support it (as Thorsten points out), XaAES should check for the actual VDI, same as it is done for the Milan. That way we can be sure that the value is correctly interpreted on all hardware.

**Comment by shoggoth77** [comment]
Another approach would be to let the user decide both mode and modecode, and if mode is 5 or 7 use the API defined by Atari/Milan for those modes. Hence get rid of all the gobbledygook in k_init.c, and as an added bonus - get rid of this discussion.

**Comment by shoggoth77** [comment]
Clarification; The Vampire doesn't enable any Atari-compatible flags whatsoever, it merely specifies a value for the _VDO cookie, indicating both what hardware is available, and an API to use to control it. That's probably a good idea if applications should be able to support the thing. And that's an entirely separate discussion I believe.

**Comment by shoggoth77** [comment]
Can we reach some kind of conclusion around this.
1. A cookie value for _VDO has been assigned. 
2. There's a patch which allows XaAES to run on more hardware by recognising said value.
3. Ideally one should rewrite the entire video init function.

(1) isn't the scope of this project, (2) is, and (3) haven't been done, and unless someone feels like testing this on a multitude of video solutions, it won't.

 - is the patch rejected?
 - if so, how shall such a patch be phrased to make it into the project?

**Comment by mikrosk** [comment]
From a practical point of view, I have no objections (maybe just that change the value to 0x50000 to avoid gap as Aranym really doesn't set any _VDO value for itself) but when it comes to Vampire, I'm worried about the inconsistency in general. For example, SuperVidel has its own cookie. Is it a separate hardware? Sure, it offers video capabilities competing with the Vampire. Is it Falcon compatible? You bet. And yet it doesn't expand _VDO in any way, why Vampire should? CTPCI hardware also doesn't use _VDO... so maybe that patch should be about changing `_VDO` to `_MCH` and you can leave the check for 0x60000. :) Just my humble point of view.

**Comment by shoggoth77** [comment]
The cookie is defined as "video hardware", and applications tend to use this to determine availability of certain hardware. The CTPCI rightly doesn't touch the _VDO cookie value, because the machine still has VIDEL graphics and changing it to something else would cause applications to be unable to use that hardware. The SuperVidel is VIDEL compatible, and changing the cookie value to something else would break compatibility. Same thing with Aranym. This scenario is different.

Lets contemplate over the alternatives:
1. Cookie value is set to 30000h instead. While some applications will recognise the availability of a Falcon video XBIOS, other applications will attempt to access VIDEL hardware and crash.
2. Cookie value is set to -1. Application can't use this information for anything particular.
3. Cookie value is 60000h. Applications can use this, since it signals the availability of said hardware and software interface.

An unsuspecting non-Vampire-aware application is likely to react the same to (2) and (3), but a new application can take advantage of (3). (1) would be shooting ourselves in the foot. (2) requires an additional cookie to be installed just for this purpose, and that - if anything - would be highly inconsistent.

**Comment by mfro0** [comment]
I don't see anything wrong with that patch.

It just says "if machine type is 0x60000000" (something we've never seen before, so it can't do any harm to anything existing), this machine understands the same video mode passing concept than the Falcon. Nothing else.

We have lots of way freakier code fragments/remains (several of them apparently nonworking) in that said code, so I can't see how this harmless change can make things any worse.

**Comment by mikrosk** [comment]
Can we consider this patch / issue obsolete in the light of https://github.com/freemint/freemint/commit/3223f88c432f07b5572d225904659b7d97143c0f ?

**Comment by shoggoth77** [comment]
Well, the patch has been made, albeit in a somewhat different way. The result is the desired one, however. I'd say close.
