### ISSUE TITLE
wind_close() always returns 1 (success)

### ISSUE THREAD

**Issue by xdelatour** [freemint/freemint#249]
wind_close() should return 0 if error (invalid handle, window already closed). All others AES returns right values.
[xa_wind.c.txt](https://github.com/freemint/freemint/files/8148557/xa_wind.c.txt)

**Comment by GokMasE** [comment]
I can confirm that this bug is also present in XaAES-Ozk (See https://github.com/freemint/freemint/issues/241)

**Comment by th-otto** [comment]
No, TOS does not return a value:

https://github.com/th-otto/tos1x/blob/b96e4d9482eac4f6a616061e31bff9c4da6ad4d6/aes/gemwmlib.c#L1516

And you will always get TRUE.

**Comment by xdelatour** [comment]
Tested with MagiC PC, Geneva (Hatari), N.AES (ARAnyM) : returns 1 or 0. EmuTOS crashed but I haven't set NAME (title bar) for my tests (only mover + closer).

**Comment by xdelatour** [comment]
In your opinion, returning 1 is the correct behavior ? XaAES must follow the behavior of original TOS or the behavior of newer AES ?

**Comment by th-otto** [comment]
IMHO it really doesn't matter much. I don't think that are any applications (beside test program like yours) that actually check the return value. And as you have noticed above, those that actually pass invalid handles are likely to crash older AES versions. Same with the NAME widget: if it is set in the flags, then you *must* set WF_NAME. And the ptr for the title must remain valid as long as the window is open, it is not copied by AES.

**Comment by lpgb** [comment]
MultiTOS (multitos\gemwmlib.c) is rewritten and appears to be able to return an error condition. XaAES versus MultiTOS is a far better comparison. N.AES returns 0 or 1 as well.

**Comment by GokMasE** [comment]
In general I think it would appear logical to adjust XaAES implementations of AES calls to match those of comparable products.
If N.AES / Geneva / MagiC all agrees that `1 = succes` and `0 = error` it would IMO seem fairly odd for XaAES to insinst on doing things differently.

**Comment by mfro0** [comment]
> In general I think it would appear logical to adjust XaAES implementations of AES calls to match those of comparable products. If N.AES / Geneva / MagiC all agrees that `1 = succes` and `0 = error` it would IMO seem fairly odd for XaAES to insinst on doing things differently.

That's exactly what Atari's GEM AES manual (available on DevDocs) says. If in doubt, I would take that as the definite reference.

**Comment by mikrosk** [comment]
Oh, there even was a patch. Thanks @xdelatour!

**Comment by xdelatour** [comment]
I’m happy to help
