### ISSUE TITLE
XaAES: graphic glitch

### ISSUE THREAD

**Issue by xdelatour** [freemint/freemint#256]
I just tested the latest snapshot for aranym without modification (freemint-1-19-6a556063-040-aranym.zip )
There is a display error in 256 color mode:
* Download the latest snapshot (or an older freemint-1-19-a38-040-aranym from July 2020 for example)
* Edit fvdi.sys and replace 1024x768x32 with 1024x768x8
* Run ./runme.sh
* Go to Options, Desk preferences
* Click Cancel
* A vertical bar remains on the screen

![snap000](https://user-images.githubusercontent.com/4384945/171988202-9b292337-ff2c-4abc-a5d1-f2abb139ed2d.png)

**Comment by mikrosk** [comment]
Also see https://github.com/freemint/teradesk/issues/4 ... It seems there is something wrong with the preferences dialog.

**Comment by th-otto** [comment]
If that happens only in 256 color mode, i think is is related either to fVDI or to Aranym, not to XaAES.

**Comment by xdelatour** [comment]
Hi Thorsten,
Thanks you for validating my previous patches (sorry, I'm very late)

I'm unable to make further tests (I only have ARAnyM). 
Couldn't that be related to the XAMFDB structure? fd_w is rounded up to 16 pixels. The actual size is stored in d_w and d_h.

**Comment by xdelatour** [comment]
> If that happens only in 256 color mode, i think is is related either to fVDI or to Aranym, not to XaAES.

Indeed, you're right. There is no problem when fVDI is disabled. Tested with 256colour, 80columns, VGA
In xaaes.cnf:
`screendev=5`
`modecode=0x3b`

**Comment by mikrosk** [comment]
Linked in fVDI, closing here.
