### ISSUE TITLE
Popup menu will appear in wrong position y-wise if mn_item is >1

### ISSUE THREAD

**Issue by GokMasE** [freemint/freemint#259]
If a menu (not submenu) initiated through `MENU_POPUP(menu, xpos, ypos, mdata)`, is configured with MENU struct item `mn_item` set to >1 then XaAES will add an unwanted offset to ypos. 

To the best of my understanding, the `mn_item` parameter is typically used to specify which menu entry (menu index) should be the 1st one to visibly appear in the menu when the menu has been configured to allow scrolling. The `xpos` and `ypos` parameters decides the location of the upper left corner of the menu.

**NOTE 1: While it seems `mn_item>1` potentially CAN have an impact on vertical alignment of a menu under at least N.AES, that behaviour appears to be 100% limited to _submenus_. In that context it seems to give a result resembling that of menu_istart().**

**NOTE 2 : This bug is not present in XaAES-Ozk (#241)**

**Comment by xdelatour** [comment]
Is this a bug in the current snapshot or is it a regression introduced by my patch proposal for #212 ?

**Comment by GokMasE** [comment]
> Is this a bug in the current snapshot or is it a regression introduced by my patch proposal for #212 ?

That is a justified question! I realize this issue is NOT present in the last binary I tested (from June 11th). Essentially that suggests it probably is introduced as of the patch proposal linked to issue #212.

I should have tested this with earlier builds to eliminate this as a source for the described phenomenon - sorry about that!

**Comment by xdelatour** [comment]
I just made small adjustment: 
[menu_istart-20220620.path.patch.txt](https://github.com/freemint/freemint/files/8943151/menu_istart-20220620.path.patch.txt)

I don't know if this new version can solve the problem. Do you have a program where the problem would be visible?

**Comment by GokMasE** [comment]
> I don't know if this new version can solve the problem. Do you have a program where the problem would be visible?

I made a quick example and uploaded to the comment thread for #212

**Comment by mikrosk** [comment]
Indeed, closing in favour of #212, let's continue there.
