### ISSUE TITLE
netusbee.prg doesn't detect certain USB keyboards on Atari TT

### ISSUE THREAD

**Issue by mikrosk** [freemint/freemint#261]
Follow-up from #258: I have two USB keyboards, one is correctly detected on my TT (thanks to solved #258!), one isn't.

Strangely, this issue seems to be present only on my Atari TT -- the same code works on my MegaSTE@16 MHz, Falcon030@16 MHz and even (with some changes, see https://github.com/freemint/freemint/issues/258#issuecomment-1166644082) on Falcon060@66 MHz.

Also, the second keyboard is always detected on my TT's Lightning, with just enabling `BLITZ030.PRG` instead of `NETUSBEE.PRG` makes it working.

I'm really not sure what makes the TT so special but clearly, if CT60 Falcon is happy to detect the keyboard, it can't be because of faster CPU / TT RAM...

**Comment by Perdrix24** [comment]
Since I worked on the USB project four years ago, there have been complaints about the TT. I don't have one, but if I did, I would use the Lightning VME, if only for its faster mass storage transfer rate.

I use the NetUSBee because I have a Falcon and a Mega ST (with non-socketed chip), because it's my only option and since I don't want to solder anything. I like that I can use the cartridge on several computers.

**Comment by mikrosk** [comment]
Of course. It's not my primary option (to be honest, I bought the NetUSBee mainly for its LAN port but even that one is being surpassed by the RaSCSI) but I thought that having a good, reliable NetUSBee driver on all platforms is still a good goal. :) I thought this one deserves reporting because the ROM port obviously works but only for some hardware.

As @DavidGZ mentions in https://github.com/freemint/freemint/issues/258#issuecomment-1167472164, this may be somehow related to weak power line on my TT's ROM port (although I did recapped the PSU it's true that there is additional hardware connected, which could have an effect as I'm thinking about it).

**Comment by Perdrix24** [comment]
For LAN you can use an USB Ethernet adapter on the Lightning VME.

**Comment by Perdrix24** [comment]
I have an idea. Have you tried with a powered USB hub?

**Comment by mikrosk** [comment]
@Perdrix24 this was an incredibly useful idea! Now both my keyboards are detected, even with the old drivers. Perhaps the TT really doesn't supply enough amps for some picky hardware. Closing the issue (for now ;)), many thanks for the suggestion.

**Comment by mikrosk** [comment]
Just to put a definite closure on this, this was caused by a half-blown fuse in my TT. After replacing it both keyboards are nicely detected even with the 68000 build, i.e. David's changes from https://github.com/freemint/freemint/commit/7d81217e45bfe1b569285cd47d1cc60e6ba9cf04 are not needed at all.
