### ISSUE TITLE
Speed difference between BLITZ030.PRG and BLITZ030.UCD

### ISSUE THREAD

**Issue by mikrosk** [freemint/freemint#263]
This thread on AF: https://www.atari-forum.com/viewtopic.php?p=435242#p435242 got me into some testing (again... *sigh*) so let me create some fresh new issues for you ;-)

This one is mainly for @czietz as he's already let one of their testers to confirm but in case it spawns a discussion, let's not flood the AF thread and post it here instead.

Basically, whatever driver I take, the TOS version is always _signigicantly_ slower:

```
r333 drivers + r333 blitz030.ucd: 550-530 kb/s (on top of 7d8 kernel)
r333 drivers + r333 blitz030.prg: 310 kb/s

7d8 drivers + r333 blitz030.ucd: 540 kb/s
7d8 drivers + r333 blitz030.prg: 310 kb/s

a10 drivers + r333 blitz030.ucd: 550-520 kb/s
a10 drivers + r333 blitz030.ucd: 310 kb/s

a10 drivers + a10 blitz030.ucd: 510-520 kb/s
a10 drivers + a10 blitz030.prg: 310 kb/s
```

7d8 = https://github.com/freemint/freemint/commit/7d850b71e432ca08941bf53806a5fd483f23adbe
a10 = https://github.com/freemint/freemint/commit/a10b393aa2fd55e856e7950308c1aa27fa12eb69

Tested on TT030 + ThunderStorm + Lightning + USB hub + USB stick. XFERRATE 1.2, Rwabs() numbers.

**Comment by czietz** [comment]
On my (accelerated) TT I get about 620-650 kB/s with blitz030.prg. This is roughly the number I remember, so I cannot confirm a recent regression. Note that CPU and TT-RAM are accelerated, but VME access and of course speed on the USB bus itself are not accelerated. This is why there is not a big speed increase compared to the ca. 600 kB/s on a standard TT.

Someone with a stock TT (i.e., running at 32 MHz) came back to with this result under TOS:
![lightningvme](https://user-images.githubusercontent.com/9830685/177056743-11a101c9-da65-47b7-9a86-9aa23d58d960.jpg)

**Comment by mikrosk** [comment]
Interesting. Is there any chance that my NOVA installation could have somehow interfere with the Lightning? I.e. that the bus is somehow shared / interleaved or something of that kind. I've been testing all transfers with NOVA disabled but out of despair I tried to enable and to no avail.

**Comment by czietz** [comment]
The VME bus is of course shared, but there should not be any transfers to video memory while a USB transfer is running - even with the Nova enabled.

The person with the stock TT noted that the only way he found to reproduce ca. 300 kB/s transfer rate was when he removed the TT-RAM (Storm TT), and thereby forced everything (USB drivers, XFERRATE) to run from slow ST-RAM.

**Comment by mikrosk** [comment]
> The person with the stock TT noted that the only way he found to reproduce ca. 300 kB/s transfer rate was when he removed the TT-RAM (Storm TT), and thereby forced everything (USB drivers, XFERRATE) to run from slow ST-RAM.

Christian, tell your tester that I owe him a beer! XFERRATE, as available at the official download site: http://www.anodynesoftware.com/freeware/xferrate.zip indeed has both TT-RAM flags disabled! Perhaps something what @anodynesoftware could correct if he finds time. ;)

Apart from the fact that I feel like an idiot -- many, many thanks! So everything is alright with TOS drivers.
