### ISSUE TITLE
USB.PRG regression: NETUSBEE.PRG became much slower on TT

### ISSUE THREAD

**Issue by mikrosk** [freemint/freemint#264]
This one is a real beauty. 

```
7d8 drivers + 7d8 netusbee.prg: 370-400 kb/s
a10 drivers + 7d8 usb.prg + netusbee.prg: 390-400 kb/s
a10 drivers + netusbee.prg: 330 kb/s
```

7d8 = https://github.com/freemint/freemint/commit/7d850b71e432ca08941bf53806a5fd483f23adbe
a10 = https://github.com/freemint/freemint/commit/a10b393aa2fd55e856e7950308c1aa27fa12eb69

Tested on TT030 + ThunderStorm + NetUSBee + USB hub + USB stick. XFERRATE 1.2, Rwabs() numbers.

Obviously, the only candidate here is commit https://github.com/freemint/freemint/commit/b22a9b9ad98936e0d6cea9a7f2ad090b415cc8ad. So I took a look and removed this line: https://github.com/freemint/freemint/blob/master/sys/usb/src.km/hub.c#L797 and guess what? It helped! The interesting is part is "why":
- that `mdelay(500)` is called in `usb_hub_init`
- `usb_hub_init` is called only in `ucd_register`
- `ucd_register` is called in NetUSBee's `init`
- `init` is called (in case of TOS) from `_crt_init`
- `_crt_init` is called from `_start` i.e. the program entry

How on earth this can influence NetUSBee's transfer speed? `netusbee.ucd` nor Lightning drivers are not affected.

**Comment by mikrosk** [comment]
`netus000.prg` on my MegaSTE doesn't seem to be affected, neither my Falcon nor CT60. And yet I can repeatedly reproduce it on my TT. With proper voltages, usb hub and everything.

@DavidGZ, @Perdrix24 when you'll be upgrading on your test machine(s), please try make the same test although my hopes are not high, we'd need someone else with a TT and NetUSBee (@czietz maybe?)

**Comment by DavidGZ** [comment]
It's quite weird what you're describing, I took a moment to think about it and I have no idea where the problem could lie.

> 
> @DavidGZ, @Perdrix24 when you'll be upgrading on your test machine(s), please try make the same test although my hopes are not high, we'd need someone else with a TT and NetUSBee (@czietz maybe?)

All my ATARI hardware is in the closet now, if you don't get more feedback in the coming days I'll try to find some time to take my Falcon out of his long hibernation.

**Comment by Perdrix24** [comment]
I'm starting to be confused. Are the latest drivers in the snapshots stable? Are there still two versions (000 and 030)? I would like to test them and send them to Kroll for testing on his TT.

**Comment by mikrosk** [comment]
Determined to find out whether there isn't some random fishy code path taken... I've found something even weirder. The executable is not influenced by the delay but by the amount of memory it takes. In the end I was able to verify, that:
- `usb.prg` non-stripped => 370-380 KB/s
- `usb.prg` stripped (using m68k-atari-mint-strip -s`) => 370-380 KB/s
- `usb.prg` stripped using `stripex` (only 228 bytes shorter!!!) => 330 KB/s

I did quite a few experiments with cache enabling/disabling (incl. the burst modes) but couldn't find any pattern whatsoever only that if I disable the cache entirely, I'll get equally slow results (240 KB/s). Also, I have verified that if I let cache enabled for the calibration code, the end result is still the same when cache is disabled in desktop (240 KB/s for all `usb.prg` versions).

Then I started to experiment with the XFERRATE itself: I put it in AUTO and strangely, the numbers got much better. At the end, the outcome was that if I name XFERRATE as XFERRATE.TTP, the reported speeds are slower than with XFERRATE.PRG. Yes, I could even do two consecutive tests, one with TTP, one with PRG and would get totally different numbers.

Most likely this isn't some evil bug in XFERRATE but perhaps some memory aligning where `usb.prg` code is placed on a cache-friendly boundary or something like that, I don't know. 

@Perdrix24 yes, latest drivers are stable, this is just some odd quirkiness. That `mdelay(500)` itself is not doing any harm, it just changed the file size of USB.PRG and that started to behave... unexpectedly. :)

If you can instruct Kroll to compare USB.PRG performance from https://tho-otto.de/snapshots/freemint/usb4tos/usb4tos-1-19-a10b393a.zip and https://tho-otto.de/snapshots/freemint/usb4tos/usb4tos-1-19-7d850b71.zip, that would be really great and it would lessen my paranoia a lot. :)

**Comment by czietz** [comment]
Just saw myself mentioned. Sorry, while I have a TT, I don't have a NetUSBee.

**Comment by mikrosk** [comment]
As discovered https://github.com/freemint/freemint/issues/263#issuecomment-1173998522, XFERRATE has been running from ST-RAM the whole time I had been doing my tests. After correcting its PRG flags I can confirm that not only both USB.PRG run equally fast but also that the actual speed test gives far better results with NETUSBEE.PRG -- 460 KB/s.

(it still doesn't explain the speed difference but who knows what happens there if running from ST-RAM...)

**Comment by czietz** [comment]
> (it still doesn't explain the speed difference but who knows what happens there if running from ST-RAM...)

Iirc, memory allocations are only 2-byte-aligned in ST-RAM, but always 4-byte-aligned in TT-RAM. Therefore, and basically by chance, in ST-RAM you can up with faster or slower memory - assuming 32 bit accesses by the CPU.

**Comment by Perdrix24** [comment]
@mikrosk  OK, so I take you don't need this test anymore:

> If you can instruct Kroll to compare USB.PRG performance from https://tho-otto.de/snapshots/freemint/usb4tos/usb4tos-1-19-a10b393a.zip and https://tho-otto.de/snapshots/freemint/usb4tos/usb4tos-1-19-7d850b71.zip, that would be really great and it would lessen my paranoia a lot. :) (important: instruct him to use NETUSBEE.PRG, not NETUS000.PRG)

**Comment by mikrosk** [comment]
@czietz that sounds like a plausible theory, indeed.

@Perdrix24 I think it still makes to ask Kroll to test #265 -- as the TT seems to be the most affected platform.
