### ISSUE TITLE
AKP keyboard code does not copy ALT tables from TOS

### ISSUE THREAD

**Issue by skaftetryne** [freemint/freemint#28]
If AKP keyboard handler is enabled, MiNT tries to load a "keyboard.tbl" from sysdir. If this file is not present, MiNT will copy the keyboard tables from TOS. However, it only copies the normal, shift and caps lock tables. The alt tables are ignored.

**Comment by mikrosk** [comment]
Can you provide a short description how to reproduce it? I've found it in the source code but I want to be sure the fix will be correct & well tested.

**Comment by skaftetryne** [comment]
IIRC I noticed this bug on an STE running 2.06. Easiest to test with Hatari. Use a German or Norwegian TOS 2.06. Remove any keyboard.tbl files from sysdir. Boot to MiNT. Now, try to type {[]}. It is not possible, as the ALT-tables are empty. Can be confirmed by running KeyEdit and look at the ALT-tables.

**Comment by mikrosk** [comment]
@skaftetryne what's the ALT-combo for  {[]} ? Or you literally mean pressing the keys and nothing happens?

**Comment by skaftetryne** [comment]
{[]} is located on the two keys to the right of "P". ALT+keys should result in [], ALT+SHIFT == {}.

If you run KeyEdit (http://joska.atari.org/KeyEdit/, 020+ only) and look at the ALT-tables you'll see that they are empty.

I have not looked at this code. Maybe this only happens when running MiNT on TOS < 4? The ALT-tables are present in TOS 2.x and 3.x, but not documented until 4.x.

![keys](https://cloud.githubusercontent.com/assets/25146704/26395832/9ae169d4-4071-11e7-8e45-14110e540236.png)

**Comment by mikrosk** [comment]
Aaaaahhh, that explains everything then: https://github.com/freemint/freemint/blob/master/sys/keyboard.c#L1680 ... so should the check be changed?

**Comment by th-otto** [comment]
@skaftetryne what makes you think the alt tables are present in 2.x/3.x? They aren't. All handling of alt-keys is hardcoded in the key handler there.

**Comment by skaftetryne** [comment]
What makes me think that is that the ALT-tables are present on my STE with 2.06. But upon closer inspection it turns out that those are provided by the keyboard driver I'm using to get a Norwegian keyboard under TOS! Without that driver there are no ALT tables, you are completely right.

So nothing to change here, MiNT behaves as expected. The fix for this problem is to always use a keyboard.tbl under TOS < 4.
