### ISSUE TITLE
CFLib-compiled apps crash with memory protection if NVDI/fVDI is not present

### ISSUE THREAD

**Issue by mikrosk** [freemint/freemint#283]
No, this is not a regression from fixing #22 :) To my surprise, it has been here all along - before my fix and also after my fix. How so? Well, it's reproducible only on 040+ machines. I personally tested it on Aranym and CT60, same symptoms.

Fortunately, repro is easy:
- download latest freemint snapshot for aranym
- disable `fvdi.prg` in `mint.cnf` and set `video = 26` in `xaaes.cnf`
- boot  with aranym-mmu

Desktop loads fine but TosWin2 is nowhere to be found. Double-click on toswin2.app, nothing. Double-click on qed.app, nothing.

When compiled with debug info:
```
pid   6 (toswin2): kern_procdir_get_stat: enter
pid   6 (toswin2): kern_procdir_get_stat: do ksprintf
pid   6 (toswin2): get_cookie(): tag=4D694E54 (MiNT) ret=1290DFC
pid   6 (toswin2): get_cookie(): value 00000113 returned at 1290DFC
pid   6 (toswin2): GET_COOKIE($4D694E54): r=0, val=$113
pid   6 (toswin2): get_cookie(): tag=4D616758 (MagX) ret=1290DFC
pid   6 (toswin2): get_cookie(): lookup failed
pid   6 (toswin2): GET_COOKIE($4D616758): r=-1, val=$FFFFFFD6
pid   6 (toswin2): get_cookie(): tag=4D675043 (MgPC) ret=1290E08
pid   6 (toswin2): get_cookie(): lookup failed
pid   6 (toswin2): GET_COOKIE($4D675043): r=-1, val=$FFFFFFD6
pid   6 (toswin2): get_cookie(): tag=6E414553 (nAES) ret=1290E00
pid   6 (toswin2): get_cookie(): value 0112A000 returned at 1290E00
pid   6 (toswin2): GET_COOKIE($6E414553): r=0, val=$112A000
pid   6 (toswin2): get_cookie(): tag=4E564449 (NVDI) ret=1290E08
pid   6 (toswin2): get_cookie(): lookup failed
pid   6 (toswin2): GET_COOKIE($4E564449): r=-1, val=$FFFFFFD6
pid   6 (toswin2): Mxalloc(1204,30)
pid   6 (toswin2): attach_region: reg 4, return loc 42000 (42000)
pid   6 (toswin2): [1][ PROCESS  "toswin2"  KILLED: | MEMORY VIOLATION.  (PID 006) | Type: hardware  PC: 00E57A64 | Addr: 6104487A  BP: 01246000 | 
pid   6 (toswin2): signal #10 raised [syscall_pc 0x12655E0, exception_pc 0xE57A64]
pid   6 (toswin2): ufree(0x11B3F4C, XaAES:../xa_appl.c,862)
pid   6 (toswin2): ufree(0x11B3F30, XaAES:../xa_appl.c,864)
```

This crash and PC is repeated for every attempt. First I thought whether that 0x30 mode (supervisor protected) doesn't do some damage there but nope, there are other allocations with this mode. And then it hit me - what if it is the startup-code? And indeed, if one starts COPS or HypView from the snapshot, they work fine. Only QED and TosWin2 crash.

From EmuTOS map file I could see that it is crashing somewhere in `_vdi_vst_load_fonts` and indeed, it really crashes at this place: https://github.com/freemint/cflib/blob/master/appinit.c#L94

So ...

- why does it crash only on 040+ machines?
- is the check for GDOS presence above it not sufficient?
- what's so special about this function that it crashes in both EmuTOS and CT60 TOS (4.x) ?
- why does it crash at all?

**Comment by mikrosk** [comment]
Looking at what [vst_load_fonts](https://freemint.github.io/tos.hyp/en/vdi_control.html#vst_load_fonts) [does](https://github.com/emutos/emutos/blob/master/vdi/vdi_text.c#L1284)... it would seem that it tries to iterate over loaded fonts which are (obviously) not loaded. But is it really reason to crash?

**Comment by mikrosk** [comment]
Simple rero (verified in Hatari040, too):

```
#include <gem.h>
#include <stdint.h>

int main()
{
        int16_t app_id = appl_init();

        int16_t work_out[57];

        int16_t handle;
        //int16_t work_in[11];
        int16_t work_in[16] = {};
        int16_t i;

        for (i = 0; i < 10; i++)
                work_in[i] = 1;
        work_in[10] = 2;
        v_opnvwk(work_in, &handle, work_out);

        vst_load_fonts(handle, 0);

        appl_exit();
}
```

**Comment by mikrosk** [comment]
Adjusted example code:

```
#include <gem.h>
#include <stdint.h>
#include <stdio.h>

int main()
{
        int16_t app_id = appl_init();

        int16_t work_out[57];

        int16_t handle;
        int16_t work_in[11];
        int16_t i;

        int gdos = vq_vgdos();
        printf("%d\n", gdos);

        for (i = 0; i < 10; i++)
                work_in[i] = 1;
        work_in[10] = 2;
        v_opnvwk(work_in, &handle, work_out);

        if (gdos != -2)
                vst_load_fonts(handle, 0);

        v_clsvwk(handle);

        appl_exit();
}
```

This actual does the right thing (one can't call vst_load_fonts without GDOS presence), same as cflib.

What is however scary is the fact that really, on fast machines in XaAES vq_vgdos() doesn't return -2 anymore but some random number! When launching just `INIT=/bin/bash` it is still -2, when running `xaloader.prg` from bash and running the same program, it's not -2 anymore!

**Comment by mikrosk** [comment]
> vq_vgdos() doesn't return -2 anymore but some random number

Getting closer... it doesn't return some _randnom_ number, just upper 16-bits are trashed. My guess would be the VDI handler in kernel.

**Comment by mikrosk** [comment]
Hmm, this looks to be a bigger problem than I thought.

First some facts:

1. tos.hyp defines `vq_gdos` as:
```
              move.w   #-2,d0
              trap     #2
              cmp.w    #-2,d0
              sne      d0
              ext.w    d0
              rts
```
and  `vq_vgdos` as:
```
vq_vgdos:     move.w   #-2,d0
              trap     #2
              rts
```
2. The Compendium defines `vq_gdos` / `vq_vgdos` as returning `ULONG` value:
```
ULONG vq_gdos( VOID ) or
ULONG vq_vgdos( VOID )
```
while:
```
              ; Correct binding for vq_gdos. Some compilers
              ; use the name vq_vgdos for the new version
              ; and vq_gdos for the old version which
              ; looked like:
              ;    move.w  #-2,d0
              ;    trap    #2
              ;    cmp.w   #-2,d0
              ;    sne     d0
              ;    ext.w   d0

              _vq_gdos:

              move.w   #-2,d0
              trap     #2
              rts
```
So in both cases we see that `vq_gdos` expects a **word** -2 in and a **long** zero or -1 out. However with `vq_vgdos` we are supposed put a **word** -2 in but what about the return value? It is only implied from `vq_gdos` handling that it should be a **word** value.

3. gemlib puts a **long** -2 as input in both cases and for `vq_gdos` it extends its **word** output to a **long** 0 / -1 while in `vq_vgdos` ... it leaves the **long** return value as is: https://github.com/freemint/gemlib/blob/master/_gc_vq_vgdos.c

Now the interesting question. What should we do? TOS and EmuTOS always return the whole thing for `vq_vgdos`, i.e. if a long -2 is on input, it is also on output.

However FreeMiNT seems to break this promise: https://github.com/freemint/freemint/blob/master/sys/arch/syscall.S#L746

When looking at `_build_context` in context.S, my eyes are bleeding. Everything seems to work there with `d0.w` except: https://github.com/freemint/freemint/blob/master/sys/arch/context.S#L82 ... 040 or 060, what a coincidence! (Aranym and CT60, anyone?)

So I'm tempted to fix this on the kernel level and not in gemlib, as we should keep the promise "do not touch d0 when called with -2".

@th-otto @vinriviere @czietz what do you think?

**Comment by th-otto** [comment]
>     3. gemlib puts a **long** -2 as input in both cases

Yes, but only because a moveq is shorter and faster than a move.w #-2,d0

> for `vq_gdos` it extends its **word** output to a **long** 0 / -1 while in `vq_vgdos` ... it leaves the **long** return value as is: https://github.com/freemint/gemlib/blob/master/_gc_vq_vgdos.c

It does not extend the return value from the vdi call. It extends the result from cmp.**w** #-2,d0. Too me, that looks perfectly correct. And even if someone trashes the upper bits, vg_gdos() should still work. It would only break vq_vgdos(). Also IIRC, NVDI for example simply returns "0" for vq_vgdos() instead of some meaningful value.

> Now the interesting question. What should we do? TOS and EmuTOS always return the whole thing for `vq_vgdos`, i.e. if a **long** -2 is on input, it is the same **long** on output.

Essentially, the output is always long. For the VDI, both calls are the same.

> However FreeMiNT seems to break this promise: https://github.com/freemint/freemint/blob/master/sys/arch/syscall.S#L746

I can't see anything wrong there. It does a cmp.**w** #-2,d0, and then in https://github.com/freemint/freemint/blob/27e90eecd08ed80a231df63883e9e9eb1b1bf696/sys/arch/syscall.S#L1570 returns a long for the version.

> so I'm at lost how this could damage the upper 16 bits).

Me too. At least from just looking at the code, i can't see any problem currently, neither in gemlib nor the kernel.
BTW, there seems to be register_trap2 which is supposed to install either a AES or VDI handler. But i looks like only XaAES uses it to install the AES handler, a VDI handler is never installed or removed.

**Comment by mikrosk** [comment]
> A simple fix would of course be to use vq_gdos() in QED and toswin2 instead of vq_vgdos(), but that just hides the problem if there is really something going wrong.

Indeed. Also, if someone else expects `vq_vgdos`'s -2 return value as **long** (e.g. in his program in asm), it would reappear anyway.

> BTW, i still don't understand why vst_load_fonts() crashes, even if you call it without a GDOS installed.

I do, see my (misguided :-)) email to EmuTOS ML: https://sourceforge.net/p/emutos/mailman/message/37720155. Basically CF-Lib, "thanks" to gemlib, [breaks](https://github.com/freemint/gemlib/blob/master/vst_load_fonts.c#L13) the [contract](https://www.tho-otto.de/hypview/hypview.cgi?url=%2Fhyp%2Fcompend.hyp&charset=UTF-8&index=617): we do call `vq_vgdos` but basically ignore its return value if no GDOS is present.

Unless someone is happy to do so, I'll fire up Hatari's debugger today to see what's going on in that handler.

**Comment by mikrosk** [comment]
Haha, it was right under our noses:

> > However FreeMiNT seems to break this promise: https://github.com/freemint/freemint/blob/master/sys/arch/syscall.S#L746

> I can't see anything wrong there.

It was really caused by the 040/060 instruction destroying the upper 16 bits while the handler restoring only the lower 16 bits.

**Comment by th-otto** [comment]
??? Thats the entry to the handler, not the return.

**Comment by mikrosk** [comment]
Let's follow up in the MR.

**Comment by mikrosk** [comment]
I have just confirmed the fix in gemlib -- when running fsetter, toswin2 and qed with the old kernel, they do not crash anymore either.

Now I'm happy. :)
