### ISSUE TITLE
XaAES "clients" submenu causes endless stream of "memory violation" messages in kernels compiled with "-DDEBUG_INFO".

### ISSUE THREAD

**Issue by mikrosk** [freemint/freemint#285]
Repro is same as in #283: no NVDI/fVDI, `video = 26`, aranym-mmu, latest emutos + freemint.

With #283 fixed we can observe either of these two scenarios when XaAES finishes loading and one goes into the submenu (mouse cursor on the down-arrow):
- nothing is shown (at least TosWin2 should be there) but nothing terrible happens
- an endless stream of:
```
pid   8 (qed): [1][ PROCESS  "qed"  KILLED: | MEMORY VIOLATION.  (PID 008) | Type: hardware  PC: 04EE7148 | Addr: 61D401A1  BP: 013B8000 |         
pid   8 (qed): signal #10 raised [syscall_pc 0x13FA874, exception_pc 0x4EE7148]
pid   8 (qed): [1][ PROCESS  "qed"  KILLED: | MEMORY VIOLATION.  (PID 008) | Type: hardware  PC: 04EE6CF8 | Addr: 61D408F3  BP: 013B8000 |         
pid   8 (qed): signal #10 raised [syscall_pc 0x13FA874, exception_pc 0x4EE6CF8]
pid   8 (qed): [1][ PROCESS  "qed"  KILLED: | MEMORY VIOLATION.  (PID 008) | Type: hardware  PC: 04EE6CF8 | Addr: 61D408F3  BP: 013B8000 |         
pid   8 (qed): signal #10 raised [syscall_pc 0x13FA874, exception_pc 0x4EE6CF8]
```
(please note that the first and second, third, ... PC and addr differ)

The name of process causing it is quite misleading, if only TosWin2 is loaded, it's TosWin2, this log was taken when Qed and COPS were launched.

If the first scenario happens, it's very easy to ignite the second one: just repeatedly go with mouse cursor on the down-arrow and *will* crash. :)

**Comment by mikrosk** [comment]
From my quick tests it seems to be related to applications installing their own menu. LHarc leads to crash as well. COPS, GEMmkfats etc do not.

**Comment by mikrosk** [comment]
Erm, OK, happens only with kernels compiled with `-DDEBUG_INFO`. Wow.

**Comment by mikrosk** [comment]
@th-otto this was broken by your commit 8dce282e and has quite serious consequences as most of the time the event handler doesn't work at all.

What I _think_ is happening there is that your had assumed that the `a0` / `d0` register directives will force gcc to retain those values in `d0` and `a0` until calling `evnt`. However from what I see in disassembly, this is really not the case - both registers are freely reused, so by the time `evnt` is really called, they contains some bogus values.

Default state with `TRACE` inactive, i.e. without `-DEBUG_INFO`:
```
// old->when = *(long *) 0x4ba + TIMEOUT_EXPIRE_LIMIT;
0105cf38 2238 04ba                move.l $000004ba.w,d1
0105cf3c 0681 0000 0190           add.l #$00000190,d1
0105cf42 2341 0008                move.l d1,(a1,$0008)
// expire_list = old
0105cf46 23c9 0111 0250           move.l a1,$01110250
// spl (sr);
0105cf4c 46c2                     move.w d2,sr
// (*evnt)(p, args)
0105cf4e 2f00                     move.l d0,-(a7)
0105cf50 2f08                     move.l a0,-(a7)
0105cf52 4e93                     jsr (a3)
```
All good. Now with `TRACE` enabled:
```
// old->when = *(long *) 0x4ba + TIMEOUT_EXPIRE_LIMIT;
0105cf58 2038 04ba                move.l $000004ba.w,d0    // <--- oh no!
0105cf5c 0680 0000 0190           add.l #$00000190,d0
0105cf62 2340 0008                move.l d0,(a1,$0008)
// expire_list = old;
0105cf66 23c9 0111 0284           move.l a1,$01110284
// spl (sr);
0105cf6c 46c1                     move.w d1,sr
// TRACE (("doing timeout code for pid %d", p->pid));
0105cf6e 3f2a 0410                move.w (a2,$0410)
0105cf72 487a ff54                pea.l (pc,$ff54)
0105cf76 4e94                     jsr (a4)
// (*evnt)(p, args) called with completely bogus register content
// as the function above (any function, really) freely uses d0/a0 as scratch registers
0105cf78 2f00                     move.l d0,-(a7) [06c60000]
0105cf7a 2f08                     move.l a0,-(a7) [06c60000]
0105cf7c 4e93                     jsr (a3)
```

My naive patch:
```
diff --git a/sys/timeout.c b/sys/timeout.c
index 88521c87..bed439e9 100644
--- a/sys/timeout.c
+++ b/sys/timeout.c
@@ -417,8 +417,8 @@ checkalarms (void)
                 * need a cast and have to place it in t->arg themselves but
                 * that way everything else still works without change -nox
                 */
-               register long args __asm__("d0") = tlist->arg;
-               register PROC *p __asm__("a0") = tlist->proc;
+               register long args = tlist->arg;
+               register PROC *p = tlist->proc;
                to_func *evnt = tlist->func;
                register TIMEOUT *old = tlist;
                
@@ -450,6 +450,9 @@ checkalarms (void)
                 * to be drivers around that were compiled by it.
                 */
                __asm__ __volatile__(
+                       "\tmove.l %1, %%d0\n"
+                       "\tmove.l %0, %%a0\n"
+
                        "\tmove.l %1,-(%%a7)\n"
                        "\tmove.l %0,-(%%a7)\n"
                        "\tjsr (%2)\n"
@@ -460,7 +463,7 @@ checkalarms (void)
 #endif
                : /* no outputs */
                : "a"(p), "d"(args), "a"(evnt)
-               : "d1", "d2", "a1", "a2", "cc", "memory");
+               : "d0", "d1", "d2", "a0", "a1", "a2", "cc", "memory");
                
                sr = spl7 ();
        }
```
solves the problem but it has the annoyting Dx,Dx and Ax,Ax `move` in there so perhaps you can come up with a more elegant solution?

**Comment by th-otto** [comment]
Wow. That's strange. I thought that my construct just does what it obviously meant to: move the inputs of p and args to a0 and d0, since that are the inputs to the asm. I think there is no other way of explicitly assigning an input to a specific register, so feel free to apply your patch. Maybe moving the assignment to p and args until after the TRACE() call will fix it, but it surely does not wok in the way i thought it should.

I'll also have to check whether i have used similar constructs in other places.

**Comment by mikrosk** [comment]
It's really strange, indeed. To me it nearly looks like a gcc bug, if for nothing else how would one pass `p` and `args` into another, regular, function? After `TRACE` they contain bogus values anyway.

Maybe it's worth trying to test it with such regular function. If that works, maybe it means that gcc forgets to guard the value(s) only in case of `__asm__` directive.

@vinriviere any idea?

**Comment by mikrosk** [comment]
@czietz I could understand why it didn't stay in given register but take that `d0` in my example above - it is clearly overwritten even before the trace call and yet when passing to `__asm__` as `args`, gcc still thinks that is is `d0` which contains given value. Isn't that a problem?

**Comment by czietz** [comment]
Yes, the code obviously _is_ a problem, evidenced by the fact that it crashes.

You would need to dump the intermediary steps during gcc's optimization to see exactly what happens. But I guess it knows that `D0` is clobbered anyway by the call (which is enabled in debug mode); and therefore deduces it's free to use `D0` for other purposes prior to the call, too.

This is why gcc's manual warns you about using call-clobbered registers in such a way.

Consider the following example:
```c
extern int clobbers_d0(long);

int test1(int num) {
    register long foo __asm__("d0") = num;
    clobbers_d0(foo+2);

    __asm__ volatile("move.l %0,0x1234": : "d"(foo) : "memory");
}

int test2(int num) {
    register long foo __asm__("d2") = num;
    clobbers_d0(foo+2);

    __asm__ volatile("move.l %0,0x1234": : "d"(foo) : "memory");
}
```

You can see (https://tinyurl.com/2oymj3qf) that for `test1()` `D0` is also modified (to perform the addition) before the call that clobbers it. Hence, the `__asm__` statement uses some undefined value as input operand. When using a _non-call-clobbered_ register like `D2`, the result is as you would have expected.

**Comment by czietz** [comment]
PS: It's the same for x86 and (ARM)[https://godbolt.org/z/csY5WvE3r], not specific to m68k gcc.

**Comment by mikrosk** [comment]
Thanks for the nice demonstration, Christian - I was missing the link between `__asm__("d0") ` and `__asm__ volatile...`. If you remove the latter, the compiler doesn't feel obliged to use `d0` anymore and treats it as a generic `register` recommendation.

Anyway, since the PureC convention requires a0/d0, i.e. prime examples of clobbered registers, it's clear that current code must be more explicit.
