### ISSUE TITLE
XaAES question - new Screen device selection, Modecode specifiers

### ISSUE THREAD

**Issue by ragnar76** [freemint/freemint#286]
Hi there,

since "video = 0x02342" is now depricated, what do i enter for a 1920x1080x16bit on my firebee? Either, i'm blind or stupid. I dont't find anything in the docs :(

bye
Bernd

**Comment by ragnar76** [comment]
To be more precise. i have this line in my xaaes.cnf so far

video = 0x4335		# 1920x1080 60Hz (32 bit)

**Comment by mikrosk** [comment]
My guess would be `screendev = 5` and `modecode = 0x4335`.

However please note that the modecode (or video before) is highly machine-specific, it is passed to XBIOS on your FireBee. So you have to look for proper codes in FireBee's documentation.

**Comment by ragnar76** [comment]
So, it basically stays as decribed here "https://github.com/freemint/freemint/wiki/FireBee" but with another "prefix".

Anyhow, it works :)
