### ISSUE TITLE
code cleanup: remove duplicate constants from xa_aes.h

### ISSUE THREAD

**Issue by xdelatour** [freemint/freemint#288]
Here is a patch to remove all unneeded constants from xa_aes.h because all of them are already available in gemlib. 
Only AGI_OBJCDATA is remaining.

By adding AGI_OBJCDATA to gemlib, the whole part from 'constants that might be missing from current gemlib headers...' to 'end of missing constants' could be deleted.

[xa_aes.h.patch.txt](https://github.com/freemint/freemint/files/10347699/xa_aes.h.patch.txt)

**Comment by mikrosk** [comment]
As I feared, these constants are the ones missing from the older gemlib package distributed by @vinriviere in his m68k-atari-mint cross tools and were explicitly added by @th-otto in 67111242. I'm not happy with this state either but I guess we'll need to wait until Vincent updates his package as his cygwin installer is used by many people.

**Comment by mikrosk** [comment]
@xdelatour would you mind to propose a patch for gemlib with the missing constant so @vinriviere can update his package with complete set of constants and we can get rid of *all* `#ifdef`s?

**Comment by xdelatour** [comment]
Patch to add AGI_OBJCDATA to mt_gem.h.in : 
[mt_gem.h.in.patch.txt](https://github.com/freemint/freemint/files/10376431/mt_gem.h.in.patch.txt)

**Comment by mikrosk** [comment]
Gemlib has ben patched & published, so let's wait for Vincent and then I'll merge your changes into XaAES. Thanks!

**Comment by vinriviere** [comment]
As stated in https://github.com/freemint/freemint/pull/289#issuecomment-1383270802, I've updated my cross-tools binaries with the latest GemLib.

**Comment by mikrosk** [comment]
Closing, any further comments can be adressed in the pull request.
