### ISSUE TITLE
Svethlana driver is missing

### ISSUE THREAD

**Issue by jvaltane** [freemint/freemint#29]
Someone should integrate SvETHlana driver to FreeMint git repository.

Sources has been available for a while at http://hencox.gildaelectronics.se/homepage/ataristuff.php

**Comment by mikrosk** [comment]
You're very right, @jvaltane. I'd had it in my TODO even before they published it. So I guess they did it because no output had been come from my side. :-(

**Comment by jvaltane** [comment]
I added new fork and added driver there. It needed only minor modifications.

Compiled the whole 1-19-cur tree and tested it with with my set up. Looks like it works as good as original version. I have some problems with big packages and longer downloads even with the original pre-compiled versions so I'm not sure how well it works.

Build-files are taken from ethernat driver. Should I make pull request from this and fix what ever needed?

**Comment by mikrosk** [comment]
> Should I make pull request from this and fix what ever needed?

Please do. :)

**Comment by mikrosk** [comment]
Resolved by #31
