### ISSUE TITLE
xaloader is hardcoded to load xaaes.km from $SYSDIR

### ISSUE THREAD

**Issue by mikrosk** [freemint/freemint#290]
As @swe-yc reported on Discord: it would seem that `xaloader.prg <path to xaaes>` doesn't really work. I remember having FreeMiNT installed on D: & E: so I'm wondering how did I do that, I could swear it was with specifying xaaes path like that.

To be investigated.

**Comment by swe-yc** [comment]
Found the solution. xaaes.km was not found. However i remembered some probs with .ovl or .ldg on ext2 filesystem... xaaes.km and .adi files must be executable. That solved the problem, and xaaes loaded.

**Comment by mikrosk** [comment]
Oh, so what was needed in the end? Just placing xaloader on a different drive was enough or you had to use path as the argument ?

**Comment by swe-yc** [comment]
I used path as argument as well...  will do some more tests.  I made .km executable and it almost worked. Log showed .adi files wasnt loaded, so i made them executable as well. That did the trick

**Comment by mikrosk** [comment]
@swe-yc when please, come back and report, so we can close this one. I'm really curious whether it works by default or it needs the path argument as well.

**Comment by swe-yc** [comment]
> @swe-yc when done please come back and report, so we can close this one. I'm really curious whether it works by default or it needs the path argument as well.

    I just tested:  i does need path as argument. Path also must include trailing "/" aka  so /aes/XaAES wont work, /aes/XaAES/  will.  Same if using backslash and TOS style.

**Comment by xdelatour** [comment]
@mikrosk @swe-yc 
SYSDIR is default path

https://github.com/freemint/freemint/blob/aa307992c6cfa355e79961077ef587e4960a9bda/xaaes/src.km/xaloader/xaloader.c#L60-L66

**Comment by swe-yc** [comment]
> @swe-yc when done please come back and report, so we can close this one. I'm really curious whether it works by default or it needs the path argument as well.

    I just tested:  i does need path as argument. Path also must include trailing "/" aka  so /aes/XaAES wont work, /aes/XaAES/  will.  Same if using backslash and TOS style.

> @mikrosk @swe-yc SYSDIR is the default path
> 
> https://github.com/freemint/freemint/blob/aa307992c6cfa355e79961077ef587e4960a9bda/xaaes/src.km/xaloader/xaloader.c#L60-L66

 Yes, but even if i set SYSDIR (setenv SYSDIR path) it still wont start without path as an argument...   Or SYSDIR is always kernel path?

**Comment by xdelatour** [comment]
AFAIK SYSDIR is set by the kernel itself, from either /MINT/<version> or /MINT (if /MINT/<version> doesnt existe). <version> is hardcoded in the source

**Comment by swe-yc** [comment]
> AFAIK SYSDIR is set by the kernel itself, from either `/MINT/<version>` or `/MINT` (if `/MINT/<version>` doesn't exist).
> 
> `<version>` is hardcoded in the source

I see, now it makes sense :)  Thanx!

**Comment by mikrosk** [comment]
Mystery solved then, closing. :) Swe, thanks for reporting & checking!
