### ISSUE TITLE
XaAES - Removes mvdi.c

### ISSUE THREAD

**Issue by xdelatour** [freemint/freemint#294]
Unused code in k_main.c looks like an attempt to manage a resolution change but all related functions are missing:
open_reschange/open_reschange/open_milan_reschange/open_nova_reschange. 

So, mvdi.c and mvdi.h are useless. Only vcheckmode() is called once from k_init.c but Validmode() is available from MiNT kernel (passthrough to trap14)

I removed COOKIE_fVDI from k_init.c because it was added by commit 22cc5e51baa84212a389f851aa3c47bcf74721d1

We can either:
- keep the code/files (if it can be fixed/completed - I don't have real hardware to check anything)
- remove them (patch)
[removal-mvdi-v2.patch.txt](https://github.com/freemint/freemint/files/10889176/removal-mvdi-v2.patch.txt)

Besides, in k_init.c, I don't understand why the return value of Validmode/vcheckmode is stored into work_out[45] just before calling vopnwk().

Kernel module map (made by hand): https://blog.xdelatour.fr/fr/home/xaaes-kernel-module-map

**Comment by mikrosk** [comment]
I vote for removal (because yeah, there doesn't seem to be an active Milan developer around) but I let others to express opinion, too.

Btw nice work with the map, maybe we could add it to our [wiki](https://github.com/freemint/freemint/wiki/XaAES)? (which is, unfortunately, also quite abandoned these days...)

**Comment by xdelatour** [comment]
> Btw nice work with the map, maybe we could add it to our wiki? (which is, unfortunately, also quite abandoned these days...)

Nice idea. 
I noticed there are three kinds of people:
- People who are note aware about MiNT
- People who are using MiNT (how many?)
- People who discover MiNT just now, but are unable to find any (recent) documentation

That's why I fixed a lot of broken links last month (without change the content itself). I think we must have a table of contents first (instead of the default alphabetical list), before updating pages.

**Comment by mikrosk** [comment]
Yeah, that header table or how to call it sucks massively. It is default (or was default when creating/importing the old sparemint wiki) but it is easily possible to create a custom one. Ideally, if some kind of table of contents could be created automatically and just hand-edited afterwards to nicely format it etc.

In my experience, if something is set up nicely, people do start using/editing/improving it, this github repository is a nice example of that. Not that we have now 20 contributors but without github and preconfigured builds, this project would have died 6 years ago: autobuilds were failing more often than working, they were just bunch of raw binaries, mailing list was equally unreliable... so it's worth investing time into such stuff but yeah, it's way less exciting that just sending an useful patch. :)

To your list I'd add a fourth category, people who thinks that MiNT is "that unix thing" and completely ignore the fact that could be more or less the same as MagiC or Geneva, i.e. no command line stuff at all.

**Comment by xdelatour** [comment]
Custom sidebar just added!

To avoid command line we need some user-friendly setup tools. 
Unfortunately I don't know how to write CPX, but thanks to multitasking CPX are probably not required.

**Comment by mikrosk** [comment]
Oh wow, that was fast!

CPX are perhaps really an overkill, for example @skaftetryne has done some work for his VanillaMiNT: https://atari.joska.no/VanillaMiNT/, just a couple of tools and it made a huge difference.

**Comment by xdelatour** [comment]
I intend to work on this [todo (replace RECT with GRECT)](https://github.com/freemint/freemint/blob/708646831fc16e92615ab062c34b4445cf1cb696/xaaes/src.km/xa_aes.h#L238-L241), I need to known if the removal of mvdi.c is OK or rejected.

(I would like to replace XaAES specific values with gemlib ones when available. For example, XaAES defines its own constants for vst_effects instead of using constants from gemlib)

**Comment by th-otto** [comment]
The constants are maybe relicts from older gemlib versions where they weren't defined.

I've never understood why someone invented that new RECT struct. Henk Robberts seems also to be a big fan of it. But only to save a few typings (x vs g_x etc) , at the cost of an incompatible name is really odd.

So just go ahead (but be prepared that it might be some amount of very boring work, like the comment says).

**Comment by xdelatour** [comment]
> So just go ahead (but be prepared that it might be some amount of very boring work, like the comment says).

Done!  (based on master, I ignored the removal of mvdi.c for now)

[grect.patch.txt](https://github.com/freemint/freemint/files/11008499/grect.patch.txt)

**Comment by th-otto** [comment]
Many thanks!  Applied now. i'll leave this issue open in case you want to also look at mvdi again.

**Comment by th-otto** [comment]
BTW: about CPX, writing them isn't that difficult. However, with gcc there are some minor issues:

- You have to watch out for the calling convention. Calls go in both directions, from xcontrol to the CPX, and vice versa
- CPX are supposed to be small, so you definitely don't want to link with mintlib. libcmini might be an alternative, but in general you want to avoid as much dependencies on libraries as possible
- Finally building them is a bit cumbersome. They need a 512byte binary header in front of the actual executable. I think Lattice-C has support for this, but neither Pure-C nor gcc have. You can just "cat" them together in a shell, but you'll have to find a way to generate the header file.

**Comment by xdelatour** [comment]
I found this tool [MAKECPX](https://github.com/ggnkua/Atari_ST_Sources/tree/master/C/MAKECPX) including SAMPLE.CPX but I don't know how to compile it with gcc because there is no function `main`.

**Comment by th-otto** [comment]
There is no main function in CPX modules. You need to link with -nostartfiles, and use the cpxstart.s as first module instead. That will jump to your cpx_init function.

**Comment by th-otto** [comment]
Maybe that will help. Its not well documented, and i haven't worked on it for a while, so i cannot guarantee that it even works, but it should give you an idea.

[cpxsample.zip](https://github.com/freemint/freemint/files/11011638/cpxsample.zip)

**Comment by xdelatour** [comment]
It works! bubblgem.cpx built successfully, thank you :+1:

**Comment by mfro0** [comment]
> However, with gcc there are some minor issues:
> 
I have some (working, but functionality-wise unfinished) examples of how to implement CPXs with gcc and libcmini (working Makefiles included) in my libcmini-examples repository here: https://github.com/mfro0/libcmini-examples.git if somebody wants to try. The header implementation is done as a C struct (and ist utterly trivial).

CPX binary size is between about 6K (prgflags) and 20K (colorvdi).

**Comment by mikrosk** [comment]
@xdelatour as this got a bit offtopic from the original goal -- is there something you'd like get pushed for this task (mvdi related) ? Is your patch from the first post still applicable or you'd like to adjust it?

**Comment by xdelatour** [comment]
I need to check if it is still applicable since the last changes, but I believe it is (related files are: SRCFILES, k_init.c, k_main.c, mvdi.c, mvdi.h, taskman.c, xa_global.c and xa_global.h)

**Comment by xdelatour** [comment]
It's OK, no need to change

**Comment by mikrosk** [comment]
Pushed. Feel free to open a pull request if/when you decide to work on the UI tools.

**Comment by xdelatour** [comment]
Thank you @th-otto @mfro0

@mikrosk I started to work on a small tool and I had been stuck on a stupid bug for about 2 weeks :-( 
My problem at the moment is freemint/mintlib#35: how can I get SYSDIR value from a CPX without getenv and shel_envrn?

**Comment by mikrosk** [comment]
Why not read it directly from /kern/sysdir (IIRC) ?

**Comment by xdelatour** [comment]
I thought environment variables was a better method. I will try later, thanks 👍

**Comment by th-otto** [comment]
You can also try Ssystem(S_GETBOOTLOG, buf, sizeof(buf)). That should give you the name of the boot.log file, including its path.
BTW, i think shel_envrn should work too, even for CPX.
