### ISSUE TITLE
Wiki update

### ISSUE THREAD

**Issue by xdelatour** [freemint/freemint#295]
Custom sidebar just added!

To avoid command line we need some user-friendly setup tools. 
Unfortunately I don't know how to write CPX, but thanks to multitasking CPX are probably not required. 

[EDIT] Among missing links in sidebar: some tools, details about filesystems and some Sparemint related pages.

_Originally posted by @xdelatour in https://github.com/freemint/freemint/issues/294#issuecomment-1454839843_

**Comment by xdelatour** [comment]
In fact, I've been preparing the draft for about two weeks, some pages are probably no longer necessary or too outdated (those about the CVS repository in particular)

**Comment by mikrosk** [comment]
Absolutely, it is just a raw dump from the original wiki. Unless you want to do some _serious_ changes, you have free hand in editing / changing stuff (in the worst case, there is always the revert button :-)).

Unlike the old spareming website (https://freemint.github.io/sparemint/sparemint), I have no objections to completely rework sparemint wiki, it's the information which counts, not the layout / structure.

**Comment by xdelatour** [comment]
Lot of fixed links, table of contents, [updated list of MiNT-based distros](https://github.com/freemint/freemint/wiki/FreeMiNT_downloads#independent-distributions), I close the issue.
