### ISSUE TITLE
Files with same name 'xaaeswdg.rsc' in SYSDIR/xaaes and SYSDIR/xaaes/widgets are different

### ISSUE THREAD

**Issue by xdelatour** [freemint/freemint#298]
In the binary snapshot, RSC file 'xaaeswdg.rsc' is both in `SYSDIR/xaaes` and in the `SYSDIR/xaaes/widgets`  subdirectory.

In the source tree, `src.km` includes three files:
- xaaeswdg.h
- xaaeswdg.hrd
- xaaeswdg.rsc
Files with same names are also in `src.km/widgets`

The issue is the following:
- xaaeswdg.h and widgets/xaaeswdg.h are the same
- xaaeswdg.hrd and widgets/xaaeswdg.hrd are the same
- xaaeswdg.rsc is older and bigger (18 years ago, 7998 bytes) than widgets/xaaeswdg.rsc (3 years ago, 5944 bytes)

By default, XaAES loads xaaeswdg.rsc from the current directory (xaaes). Thus, the newest widgets/xaaeswdg.rsc is ignored (except if manually specified in xaaes.cnf).

What is the best solution?
- Rename one of the two files to avoid confusion
- Remove xaaeswdg.rsc file from `xaaes` , only store widgets files in widgets subdirectory and load default from there

**Comment by mikrosk** [comment]
Wow, I wasn't aware of this. If the newer file works fine (after deleting the older one), there's no reason to keep using the old one then.

I always thought that `xaaeswdg.rsc` in `xaaes` root is mandatory.

**Comment by xdelatour** [comment]
Right, XaAES failed to start if `xaaeswdg.rsc` is removed from the `xaaes` directory because this is the default value (when `widgets = <path>` is not set in xaaes.cnf)

**Comment by xdelatour** [comment]
Explanation found [here](https://github.com/freemint/freemint/blob/100b09777074031d91d5045a24cb16a607e5adf7/xaaes/src.km/CHANGES.txt#L28-#L40).

Why `xaaeswdg.rsc` was updated only in `widgets` without renaming since XaAES loads the default file from `xaaes`?

**Comment by mikrosk** [comment]
Perhaps somebody didn't realize this. :) In that case it makes sense to move the newer version from `widgets` and keep `xaaeswdg.rsc` in `xaaes` root as before.
