### ISSUE TITLE
Dead code removal

### ISSUE THREAD

**Issue by xdelatour** [freemint/freemint#304]
Small patch to remove unused code (#if 0) in scrlobjc.c. Identical lines are just above

By the way, fixed some typos in comments and make TODO uppercase.

[scrlobjc-v2.c.patch.txt](https://github.com/freemint/freemint/files/11241549/scrlobjc-v2.c.patch.txt)

**Comment by th-otto** [comment]
Thanks, applied now.

**Comment by xdelatour** [comment]
I'll close this issue. I will reopen it when there are other code removal to do (instead of creating too many issues. Each time I try to close an issue, I find other bug - I have a patch to add appl_options() in GEMLib but on failure (return value is 0), intout contains garbage because it is unchanged).
