### ISSUE TITLE
Strange value of APP_TASKINFO

### ISSUE THREAD

**Issue by th-otto** [freemint/freemint#305]
Just stumbled upon this:

https://github.com/freemint/freemint/blob/c022b02d3aee926afdb5af2600deda0c54949e23/xaaes/src.km/xa_appl.c#L1013

Who invented that nonsense? APP_TASKINFO has the value 0x100. That means you cannot pass appliction IDs >= 256 to appl_search. Since application IDs and process IDs are the same in XaAES, that means you will run into problems when using applications such as taskbar after 256 processes have been started.

**Comment by th-otto** [comment]
Yes, but what if you want to query the normal (short) name for an apid >= 256? That will look like APP_TASKINFO is set.

**Comment by xdelatour** [comment]
According to the code, it is impossible. When ap_smode is -pid, only the long name can be retrieved.

I guess the correct usage of the function is:
- first, call appl_search with a positive value and without APP_TASKINFO to get both pid and short name (but not extra details)
- secondly, call appl_search with the pid to get the long name (no extra info again)

Or
- call appl_search with a positive value and APP_TASKINFO to get pid, long name and extra info

The purpose  of APP_TASKINFO is to return extra details like APP_HIDDEN and APP_FOCUS and the longname if the pid is unknown

What I understood:

```mermaid
  graph TD;
    A{ap_smode<br/>spec=longname=0}; 
     A -- ap_smode <0 -->B;
     A -->C;
      A -->D;
      B[next=-ap_smode<br/>longname=1];
       style B fill:#ff2020
     B-->G;
      C[APP_DESK<br/>next=desk]-->G;
      D[APP_FIRST APP_NEXT]-->E;
      E[spec=APP_TASKINFO?<br/>if spec then longname=1]-->F
       style E fill:#ff2020
     F[next=FIRST, NEXT]-->G;
      G{next==0};
      G -- 0 -->H;
      G -- !0 -->I;
     H[No more clients];
    I[pid = next->p->pid<br/>o1=APP_SYSTEM or APP_APPLICATION...] --> J;
   J[if spec then o1=o1 OR APP_HIDDEN or APP_FOCUS...] --> K
       style J fill:#ff2020
  K[o2 = pid] -->L;
    L[if longname then fname = next->name else] --> M;
       style L fill:#ff2020
    M[if !longname then fname = next->proc_name];
subgraph ap_smode >=0
 C
  D
  E
F
end
subgraph set return values
 I
 J 
 K
 L
 M  
end
```

**Comment by th-otto** [comment]
You're right, i was a bit confused. A positive value in smode is always a bitmask, not some id. Still that interface is really strange.
