### ISSUE TITLE
Bad link in Wiki Installation_guide page

### ISSUE THREAD

**Issue by adamprice2** [freemint/freemint#315]
In the wiki page Installation_guide the link to [CrippleMiNT](http://atari.st-katharina-apotheke.de/home.php?lang=en&headline=CrippleMiNT&texte=cripple) goes to a parking page, looks like it's no longer live.

It's a pity because I really need a single-disk mint install right now.

**Comment by th-otto** [comment]
Dunno upon which mint version that was based, but it will be difficult to achieve with current version. mint.prg + xaaes alone are about 900k, not counting any drivers or applications like a desktop. I think that won't fit on a disk, except maybe ED disk with 2.88 MB

**Comment by xdelatour** [comment]
I haven't tested either but the current homepage is https://atari.grossmaggul.de/home.php?lang=en&headline=CrippleMiNT&texte=cripple

Anyway, both download links are broken.

You can find them here:
- [CrippleMiNT 0.10 (Kurobox FTP server)](https://storage.atari-source.org/atari/mirrors/kurobox.serveftp.net/mint/installers/cripple1.zip)
- [CrippleMiNT 0.15 (official website via web.archive.org)](http://web.archive.org/web/20160309092524/http://atari.st-katharina-apotheke.de/download/cripple.zip)

**Comment by th-otto** [comment]
Ah ok, its only an installation disk. That may eventually still work, just create updated zip archives in the "pakete" folder. You may also which to omit kernels you don't need.

**Comment by mikrosk** [comment]
Actually the links are not broken, just under the https://atari.grossmaggul.de url, namely:

https://atari.grossmaggul.de/download/cripple.zip
https://atari.grossmaggul.de/download/cripple1.zip

I've fixed all CrippleMiNT links in the wiki + added a link to this issue for proper download links.
