### ISSUE TITLE
Possible problem with inline asm

### ISSUE THREAD

**Issue by th-otto** [freemint/freemint#316]
Seen at https://github.com/freemint/freemint/blob/3af621ef686abcb3dd89379d7ce978bdf6566246/sys/usb/src.km/ucd/ehci/ehci-hcd.c#L287 and https://github.com/freemint/freemint/blob/3af621ef686abcb3dd89379d7ce978bdf6566246/sys/usb/src.km/ucd/ehci/ehci-hcd.c#L305

There are inline statement that are neither volatile, nor declared as modifying memory, nor having any inputs or outputs. If i'm not wrong, such statements can be moved around by the compiler, which is usually unwanted.

@DavidGZ : can you have a look at it if time permits?

**Comment by vinriviere** [comment]
Side note:
It's suspicious that ColdFire uses a system call (s_system) while 68040/68060 directly uses assembler.
https://github.com/freemint/freemint/blob/39bf26fdab180918bdc84748d75d8a1dd3b9932d/sys/usb/src.km/ucd/ehci/ehci-hcd.c#L283-L288

Theoretically, calling the system call in all cases should be better, instead of messing with supervisor stuff. However, I have no idea if it's correctly implemented in all cases.

**Comment by mikrosk** [comment]
@vinriviere nicely spotted.

According to this commit: https://github.com/freemint/freemint/commit/6c7a1470a73ec2b94f6d998ee1be2f724e9e1171  it seems that the function wasn't first available and it seemed enough to just put a small code there but then it was discovered that for CF the function is actually required: https://github.com/freemint/freemint/commit/e2d42172166a238b57b191f3de2ea76dbe0dd617.

Why the 680x0 code was still kept isn't clear, to me it looks like a speed optimisation of sorts.

**Comment by vinriviere** [comment]
Good summary.

I don't know if that code is time-critical. I would be in favor of calling s_system() unconditionally. Because cache management is tricky, a task typically for a kernel. But if it works like this, even if it's inconsistent, well that's fine.

**Comment by DavidGZ** [comment]
I've just read the messages on this issue, thanks for spotting this and for the comments. I don't remember why I left the inline assembler for the 68040 and 68060, probably an oversight. The interesting thing is that this driver never worked correctly, it would be nice that @th-otto found the reason. I'll fix it in the coming days.

**Comment by th-otto** [comment]
(updated links above since source has changed)

> it's suspicious that ColdFire uses a system call (s_system) while 68040/68060 directly uses assembler.

That is the case for the cinva (inside invalidate_dcache) but not for cpusha (inside flush_dcache).

Generated code for the call invalidate_dcache (inside ahci_submit_async, gcc-7.5.0) seems to be this:
```
LBB1019:                                                       do {
[000006d0] f458                      cinva      dc  invalidate_dcache();
.LBE1020:
[000006d2] 242e 0008                 move.l     8(a6),d2 token = hc32_to_cpu(vtd->qt_token);
.LBB1022:
[000006d6] e15a                      rol.w      #8,d2 
[000006d8] 4842                      swap       d2
[000006da] e15a                      rol.w      #8,d2
.LBE1022:
[000006dc] 787f                      moveq.l    #127,d4   if(!(token & 0x80))
[000006de] 4604                      not.b      d4
[000006e0] c882                      and.l      d2,d4
[000006e2] 671a                      beq.s      .L65               break
.LBB1024:
[000006e4] 2079 0000 0000            movea.l    _kentry,a0   inlined udelay()
[000006ea] 2068 001c                 movea.l    28(a0),a0
[000006ee] 2010                      move.l     (a0),d0
[000006f0] 4c06 0407                 mulu.l     d6,d7:d0 ; 68020+ only
.LBB1017:
[000006f4] 5387                      subq.l     #1,d7            __delay inner loop
[000006f6] 64fc                      bcc.s      .LBB1017
.LBE1024:
[000006f8] 5281                      addq.l     #1,d1         __ts++
[000006fa] b681                      cmp.l      d1,d3
[000006fc] 62d2                      bhi.s      .LBB1019   } while(ts < timeout);
```

So there doesn't seem to be a problem with this in practice, atleast not for gcc 7. But maybe that changes with more aggressive optimizations.

cpusha is embedded somewhere in some other inlined functions, so i cannot tell for sure.

Another note: the C-code that is used for __const_bswap32() is compiled to the same as used in the inline asm in __asm_bswap32(). Using the C-code would be better in this case, since gcc then can avoid doing the swap twice, like in 
```
	usbsts = ehci_readl(&gehci->hcor->or_usbsts);
	ehci_writel(&gehci->hcor->or_usbsts, (usbsts & 0x3f));
```
However the optimization is not done by gcc-4.6.4

If you change the inline asm, don't forget to change the % to %%. Currently that is not needed, because it is not an "extended-asm", ie. it has no clober list.

**Comment by DavidGZ** [comment]
I've just committed a patch for this issue.

> 
> Another note: the C-code that is used for __const_bswap32() is compiled to the same as used in the inline asm in __asm_bswap32(). Using the C-code would be better in this case, since gcc then can avoid doing the swap twice, like in
> 
> ```
> 	usbsts = ehci_readl(&gehci->hcor->or_usbsts);
> 	ehci_writel(&gehci->hcor->or_usbsts, (usbsts & 0x3f));
> ```
> 
> However the optimization is not done by gcc-4.6.4
> 

I don't know if I understand your note. For what I've seen the driver uses MiNT header files to handle endianness, so if the driver ends using the assembler routine instead of the C function is because how those headers are implemented. So I think this goes beyond a driver issue and it should be fixed in the header files.

**Comment by th-otto** [comment]
Yes, thanks for looking into it. The bswap() thing is another issue, but not really urgent.
