### ISSUE TITLE
Possible problem in do_callout in xaaes

### ISSUE THREAD

**Issue by th-otto** [freemint/freemint#318]
Just seen in https://github.com/freemint/freemint/blob/39bf26fdab180918bdc84748d75d8a1dd3b9932d/xaaes/src.km/draw_obj.c#L338-L346

Isn't the constraint for the inputs wrong? Its the same problem as with all the trap_x macros for gemdos etc, the inputs must imho be in registers, because the stack-pointer is changed in the asm. Otherwise ``"move.l %2,-(sp)\n\t"`` may access the local variable with a wrong stack-pointer offset.

I also don't understand why d3-d7/a3-a6 have to be pushed at all; those are not allowed to be changed by the callback.

**Comment by mikrosk** [comment]
Can `g` lead to code directly referencing the stack, though? I'm not using it very often but IIRC I have seen only Dx/Ax or an absolute address there.

Maybe there were callbacks not really adhering to that rule. :)

**Comment by th-otto** [comment]
```
‘g’

    Any register, memory or immediate integer operand is allowed, except for registers that are not general registers.
```

So that can basically be anything that is addressable, a parameter, a local or global variable, or register.

I once tried to change the asm constraints for gemdos because i found it ineffective to load them all in registers first, but that revealed exactly that problem, and it does not work.

**Comment by th-otto** [comment]
Just as a proof:

```
void test(long c)
{
 __asm__ __volatile__(
 "movem.l %%d3-%%d7/%%a3-%%a6\n\t"
 "move.l %0,-(sp)\n\t" 
 "lea	4(sp),sp\n\t" 
 "movem.l %%d3-%%d7/%%a3-%%a6\n\t"
 	:
 	: "g"(c)
 );
}
```
compiling with -fomit-frame-pointer  gives:
```
        movem.l %d3-%d7/%a3-%a6
        move.l 4(%sp),-(sp)
        lea     4(sp),sp
        movem.l %d3-%d7/%a3-%a6
```

It works by accident in xaaes because the inputs are already in registers, but that cannot be guaranteed.

I've changed that now, just to be safe.

**Comment by vinriviere** [comment]
> Isn't the constraint for the inputs wrong? Its the same problem as with all the trap_x macros for gemdos etc, the inputs must imho be in registers, because the stack-pointer is changed in the asm. Otherwise `"move.l %2,-(sp)\n\t"` may access the local variable with a wrong stack-pointer offset.

You are very right. Inline assember can't see that the stack has moved during the first instructions, so "g" isn't reliable anymore. It's a shame that inline assembly has no way to optimally handle this case (by adjusting the stack offset), instead of using "r" which will generally add an extra move.

**Comment by vinriviere** [comment]
> I once tried to change the asm constraints for gemdos because i found it ineffective to load them all in registers first, but that revealed exactly that problem, and it does not work.

"g" can actually work safely for the **first** parameter, provided that the stack has not been changed yet (except if there's a movem above, of course, like in the example here). Only subsequent parameters actually requires "r".
