### ISSUE TITLE
V4SA: XaAES seems to ignore Bconstat()

### ISSUE THREAD

**Issue by RajahLone** [freemint/freemint#333]
On Atari V4SA, Logitech K120 on the keyboard usb port.
With lastest FreeMiNT+XaAES. Some programs uses Bconstat(2 or 4) and keyboard seems not responding. Seeing with my VDI_FX mini-demos (BIOS(1,2) always returns 0). Had to add a GRAF_MKSTATE in the programs to quit properly.
His is not happening under EmuTOS only, or FreeMiNT+MyAES.

**Comment by mikrosk** [comment]
Just to be on the safe side, can you try to replicate the issue in Aranym? V4SA still contains some bugs (sometimes not very obvious), so just to rule something like that out.

**Comment by RajahLone** [comment]
Tried with latest MacAranym.app + latest FreeMiNT/bootable uncustomized: Bconstat() is responding.
