### ISSUE TITLE
Add build artifacts to each build (especially on PRs)

### ISSUE THREAD

**Issue by mikrosk** [freemint/freemint#336]
I was completely unaware of this Github Actions' functionality until a good soul showed it to me in the Atari800 project: https://github.com/atari800/atari800/issues/177#issuecomment-2106411582.

Basically for about 90 days you can have a downloadable build with given changes. In the past we used a pretty terrible method (a plain text key to bintray...) but since bintray's closure we don't offer anything for PRs.

This would help testing PRs a lot, be it freemint, xaaes or mintlib. The 'master' builds can stay at @th-otto's server as they provide a nice bisecting ability when tracking regressions by users.

**Comment by czietz** [comment]
There is one caveat, though: Afaik, artifacts can only be downloaded when one is logged in to GitHub. This is fine for developers, imho; but less optimal for end users, since not everyone will even have a GitHub account.

**Comment by th-otto** [comment]
I get the same feeling. The one who was creating the PR certainly has a GitHub account, however he should also be able to compile the kernel himself. And compilation tests are done already currently, only the results are not saved anywhere.

**Comment by mikrosk** [comment]
I think this is still OK / useful: my main goal with this feature was to make _our_ lives easier. For instance, somebody submits a formatting fix (e.g. xaaes help), so instead of me pulling his branch, compile xaaes by myself, maybe even messing with correct $SYSDIR I just download a whole snapshot, run it, see how it looks and approve the PR.

End users usually don't care about PRs and on the other hand, you can't submit a PR without a Github account.

**Comment by mikrosk** [comment]
Nice! Let's see how this is going to work out, thanks for looking into it.

**Comment by th-otto** [comment]
BTW, when i worked on it, got a link error on programs that use libcmini (lik nohog2.acc). See https://github.com/freemint/freemint/actions/runs/9097245168/job/25004617490#step:8:6116

Reason was that the link command for such programs looked like:
```
$(CC) -I$(LIBCMINI_INCPATH) -nostdlib -o $@ $(CFLAGS) $(LIBCMINI_STARTUP) $(OBJS) -L$(LIBCMINI_LIBPATH) -lcmini $(LIBS) -lgcc
```
But libgcc implements the __main() function that is automatically inserted at the start of main(), and that has references to atexit(). For that reason the link order should be `-lgcc -lcmini -lgcc`.  

I have no idea why that error did not pop up before. I have updated the gcc toolchain some days ago (mainly to be able to compile mintlib etc. with -mfastcall), but the behaviour of gcc inserting a call to __main() has always been there.

**Comment by mikrosk** [comment]
Interesting. But I wonder, `-lcmini -lgcc -lcmini $(LIBS) -lgcc` seems a bit strange, why we need _both_ libraries twice there?

**Comment by th-otto** [comment]
Yes, i think `-lgcc -lcmini -lgcc` should suffice (that's what gcc also does when using mintlib). Maybe the `$(LIBS)` should then be moved first. But that would only be a cosmetic change, currently it works.
