### ISSUE TITLE
DNS lookup from multiple nameservers

### ISSUE THREAD

**Issue by th-otto** [freemint/freemint#339]
While trying a few things, i stumbled upon this code in mintlib:
https://github.com/freemint/mintlib/blob/9a35264c4ba4a7bed42a0b81fe6cdf65c97b1b34/socket/res_send.c#L293-L301

It tries to close the connection by passing a sockaddr off all zero. However, neither the upper layer https://github.com/freemint/freemint/blob/73149c027c25ec71fea3b789e8a3e6679194a4ef/sys/ipc_socket.c#L502-L510 nor the tcp layer https://github.com/freemint/freemint/blob/73149c027c25ec71fea3b789e8a3e6679194a4ef/sys/sockets/inet4/tcp.c#L170-L174 seem to support this kind of call, they bot return return with EISCONN in this case, without checking the address/port first.

Shouldn't they do something like the udp layer https://github.com/freemint/freemint/blob/73149c027c25ec71fea3b789e8a3e6679194a4ef/sys/sockets/inet4/udp.c#L92-L97, and close the connection if port == 0?

Does anybody have a setup where multiple nameservers are configured, and could test this? (the library should allow up to 3 nameservers: https://github.com/freemint/mintlib/blob/9a35264c4ba4a7bed42a0b81fe6cdf65c97b1b34/include/resolv.h#L57

**Comment by ragnar76** [comment]
I'm at the playground with my kids but I think, I have configured two
nameservers (8.8.8.8 and 1.1.1.1) on my firebee. Will check that later and
what should I do then?

Thorsten Otto ***@***.***> schrieb am So., 23. Juni 2024,
13:02:

**Comment by th-otto** [comment]
> what should I do then?

Good question. The code is a bit difficult to follow, with all the error conditions and gotos, so i'm not entirely sure when that point is actually reached. And since the return code from that connect() call is ignored, you would need to modify the routine, and check whether that call returns an error or not. And then you would need a small test program that calls gethostbyname(), getnameinfo() or similar, and link it with that modified library.

**Comment by ragnar76** [comment]
That's way over my knowledge. If you can give me a modified lib and a test
program, I can provide you the output

Thorsten Otto ***@***.***> schrieb am So., 23. Juni 2024,
15:05:

**Comment by th-otto** [comment]
Thanks for the offer, but i think it is easier to setup a similar environment instead ;)

**Comment by th-otto** [comment]
I think the code in the kernel is ok, connect() call in mintlib is only done on UDP sockets.

But there seem to be some quirks in mintlib in the resolver code instead. Will open a new issue there.
