### ISSUE TITLE
What is the real purpose of mouse_w.adi ?

### ISSUE THREAD

**Issue by mikrosk** [freemint/freemint#341]
My initial setup: Aranym in its default settings, `mouse.adi` and `mouse_w.adi` present in my $SYSDIR folder. My initial understanding was that `mouse_w.adi` is the one which translates mouse wheel up/down to actual slider down/up events.

EDIT: (I have remembered the story wrong, corrected)

Since I wanted to test my custom keyboard driver with the real Eiffel codes, I switched in Aranym to `WheelEiffel = Yes` and ... desktop sliders stopped working, with neither ADI driver. Also, my custom keyboard handler wasn't receiving anything. Neither up/down nor eiffel wheel down/up scancodes. So then I switched to my real Eiffel interface and tested the wheel in XaAES. And nothing worked! `mouse.adi`, `mouse_w.adi`, nothing made it work. And as a bonus, my custom keyboard handler _was_ receiving Eiffel wheel up/down events. Hmm.

So I went back to Aranym and  ... found out that Aranym had been broken for 20 years. So I quickly [fixed it](https://github.com/aranym/aranym/commit/56a7118d9083bda860bf4475950eae91c714d2f1) and hooray! My custom keyboard handler started to work as well. But not the desktop sliders.

After some investigation I have found out that I have to enable _yet another_ option, this time in `xaaes.cnf`: `eiffel_support = true`. OK, now _that_ made XaAES sliders working again.

So what's the problem? Well... that mouse wheel now works with either `mouse.adi` or `mouse_w.adi`.

So I'm totally confused, what's the point of existence of those ADI drivers?

**Comment by th-otto** [comment]
Accidently added the comment to the aranym commit, so repeat it here:

I have no eiffel interface, but according to the documentation (see http://didier.mequignon.free.fr/eiffel-e.htm) the original code did exactly send the packets that are described there.

If that does not work with your own handler, it does not mean it is wrong. I really would like to revert that change.

>so I'm totally confused, what's the point of existence of those ADI drivers?

With the wheel driver, you can also wait for MU_WHEEL events in GEM programs.

**Comment by mikrosk** [comment]
Sorry I don't get your point. I do have the real Eiffel interface and it works as expected in my driver. I suppose you want to emulate real behaviour and not what docs say.

**Comment by th-otto** [comment]
The docs say "It's possible to use the status frame" (the 8 byte one that was sent until now). So maybe there is an ooption for that in the interface? Also its a bad idea to change aranyms behaviour when the mouse driver relies on this packets. That will make them incompatible.

**Comment by th-otto** [comment]
BTW, unconditionally treating 0x59/0x5a/0x5c/0c5d as wheel codes is imho a bad idea anyway because they conflict with Shift-F6 - Shift-F10

**Comment by th-otto** [comment]
Eiffel support was initially added by @joy with commit https://github.com/aranym/aranym/commit/90b1b13ca53b1d19acabdff4ac612adbd16cc47d (back in 2004) and i'm quite sure he did not do that without some testing.

**Comment by mikrosk** [comment]
To reiterate:

- before my commit and in aranym's and freemint's default state mouse wheel ... works => by default aranym sends arrow up/down events for the mouse wheel

- with aranym's `WheelEiffel = Yes` and freemint's default state mouse wheel ... doesn't work => now aranym sends the multi-byte packet

- with aranym's `WheelEiffel = Yes` and freemint's `eiffel_support = true` mouse wheel ... doesn't work => because even xaaes expects the simple format of the mouse wheel packet

- with aranym's `WheelEiffel = Yes` and freemint's `eiffel_support = true` and with my aranym commit mouse wheel ... works => because that's what xaaes expects (see for yourself in the function `eiffel_wheel`)

- on real hardware (Falcon + Eiffel) and freemint's `eiffel_support = true` mouse wheel ... works => because that's what xaaes expects (see for yourself in the function `eiffel_wheel`) and **it is the Eiffel's default state**

Two notes, Thorsten.

1. I find it very rude to revert someone's commit without at least checking with the author of the original code (@joysfera), let alone without reaching a conclusion in this thread.

2. It's possible that yes, in 2004 it used to work with the multi-byte packet, too. However only three years later, Ozk introduced this single-byte `eiffel_wheel` handler and you know what my guess is? As he was coding XaAES on his Atari, he had found out exactly what I did: that the Eiffel support is broken and fixed it. So that fixed the XaAES part but nobody noticed the Aranym's. This is what a proper analysis looks like but no, you just reverted my fix and now Aranym is broken again. Thanks.

**Comment by mikrosk** [comment]
> Eiffel support was initially added by @joysfera with commit https://github.com/aranym/aranym/commit/90b1b13ca53b1d19acabdff4ac612adbd16cc47d (back in 2004) and i'm quite sure he did not do that without some testing.

Not only I mentioned the same thing in my commit but also I challenge your "I'm quite sure" statement. Because further `git blame` has just revelead that Ozk did not fix anything -- he _introduced_ Eiffel support in 2007. So _if_ Petr 
 was testing something in 2004, it certainly wasn't FreeMiNT + XaAES Eiffel support from 2007.

**Comment by mikrosk** [comment]
And the last comment on this from me:

```
...
Date:	2002 August 15
...
II/ News "Atari" scan-codes for MOUSE
=====================================

Theses Scan-Codes are now the default values
burn into the Flash Data of Eiffel. With a small utility
you can change these for what's you want.

Mouse									Atari SCAN-CODE default values
										
Wheel UP								$59
Wheel DOWN								$5A
Wheel LEFT ?							$5C
Wheel RIGHT ?							$5D
Middle button(Button 3)					$37
Button 4								$5E
Button 5								$5F
```
So Ozk, me and anyone else coding Eiffel support as early as on August 15, 2002 is perfectly allowed to use this single-byte format.

**Comment by vinriviere** [comment]
Not strictly related, but for information.
In 2010, I got my FireBee and an Eiffel adapter. I wanted to add wheel support in plain EmuTOS. I did it properly at BIOS and VDI level. Due to lack of knowledge, I didn't add support in AES. So that support is currently incomplete and unavailable in plain EmuTOS/EmuDesk. But it is supposed to be OK if another AES hooks the VDI vector.

Anyway, part of that support is here.
https://github.com/vinriviere/emutos/blob/c848d1a868bdcd3d43be3ec8760b9ac85b4086e0/vdi/vdi_mouse.c#L515-L550
We can see that I used the single-byte scancodes (the ones produced  by default by Eiffel).

I indeed may have noticed that ARAnyM used the other method for the wheel (multibyte packets).
I'm sorry, that's too old, I don't remember the full details.

**Comment by th-otto** [comment]
I've added now a configartion option where you can choose to send only single bytes. It is disabled by default. Hope that should solve this issue.

> We can see that I used the single-byte scancodes (the ones produced by default by Eiffel).

It's of course  easier to handle those single-byte messages, especially since the others are status reports, which are just discarded by TOS by default, so you have to install a statvec first. My main concern was that the single-byte scancodes conflict with the scancodes for shifted F* keys that are produced by the bios (they are different from what the ikbd sends, but when using bios or gem to read them, you cannot distinguish them anymore).

While looking at it, i noticed also a few other things:

- both the eiffel interface and the mouse driver seem to also support a horizontal wheel. But from what i've seen, you cannot distinguish them in the message that arrives in gem. Does anybody have a mouse with more than one wheel?

- The eiffel interface seems to also send status packets for most media keys. Does anybody have a keyboard with such keys attached to the eiffel interface? And are there any applications that would make use of them?

**Comment by mikrosk** [comment]
> My main concern was that the single-byte scancodes conflict with the scancodes for shifted F* keys

1. I'm not aware of an application which would need both the same time.
2. I would speculate that's the reason why Eiffel emulation is disabled by default.

> Does anybody have a mouse with more than one wheel?

More specifically, a PS/2 mouse with more than one wheel. But the concept of multiple wheels does exist: https://www.reddit.com/r/buildapc/comments/xsm8cv/anyone_know_of_a_mouse_with_two_scroll_wheels.

> And are there any applications that would make use of them?

In ScummVM, I added only the basic keys, i.e. the Windows key, PrintScr, Numlock etc. If I were to guess, I would say that Aniplayer is probably the only application of having chance to support multimedia keys as Didier was modifying the firmware to support built-in LCD to show song names etc.

**Comment by DavidGZ** [comment]
> 
>     * both the eiffel interface and the mouse driver seem to also support a horizontal wheel. But from what i've seen, you cannot distinguish them in the message that arrives in gem. Does anybody have a mouse with more than one wheel?
> 

I have an old PS/2 mouse with 2 wheels which I used to use with a JerryST adapter in my Falcon, though I have never made any use of the second wheel.

**Comment by mikrosk** [comment]
@DavidGZ you wouldn't happen to also own an Eiffel, would you. ;)

**Comment by DavidGZ** [comment]
> @DavidGZ you wouldn't happen to also own an Eiffel, would you. ;)

Yes, I have one :-)
