### ISSUE TITLE
Single click on parent menu with a submenu is ignored

### ISSUE THREAD

**Issue by lpgb** [freemint/freemint#347]
Single clicking a parent with a submenu is inconsistent with atari's aes 4.1. It requires a double click which is weird. I take advantage of this by having options in the submenu and a dialog with more options if the parent is clicked. Of course naes mimics atari's aes.

**Comment by th-otto** [comment]
I think that is caused by https://github.com/freemint/freemint/blob/b227ddf9df1513b6fbf9b3b85779e5e917dbdb94/xaaes/src.km/menuwidg.c#L1905, which has been changed in https://github.com/freemint/freemint/commit/bfe8d3625a749cab330bfcc1b1bf9d937c7b9881

**Comment by lpgb** [comment]
Little more info. Atari's aes 4.1 and naes except single or double clicks on the parent.

**Comment by th-otto** [comment]
Should be fixed by https://github.com/freemint/freemint/commit/85b2534f0bb6c96c00cfc4c4dcfe8861ba4b419d

**Comment by th-otto** [comment]
Hm, seems i cannot find the issue that you mentioned, and github does not allow me to search for attachments. Can you provide a link to it?

**Comment by lpgb** [comment]
Nor can I, strange. Here it is.
[aesdemo.zip](https://github.com/user-attachments/files/16516213/aesdemo.zip)

**Comment by GokMasE** [comment]
> This is working ok. Thanks.
> 
> Can someone try that AES demo I posted in the other issue as it freezes the machine. It was doing this on the previous snapshot (arrow fix) prior to this fix. Click character->position->superscript and it locks up. Seems to be calls to menu_istart() that are fatal.

I can confirm the situation described above to freeze my setup here too.

(Tested here with XaAES from 2024-07-29 on my Falcon/CT60)

**Comment by th-otto** [comment]
Confirmed. Seems indeed to be caused by menu_istart(); selecting an entry in the styles submenu also locks up.

**Comment by th-otto** [comment]
Should be fixed by https://github.com/freemint/freemint/commit/bc5c73de082f12ce1d0eb9aa16d4b10fcbdeb136

**Comment by lpgb** [comment]
Tested snapshot and it seems good now. Appreciate the fixes, thanks.

**Comment by mikrosk** [comment]
Happily closing then.
