### ISSUE TITLE
XaAES 'About' dialog is crashing in Russian and Hungarian languages

### ISSUE THREAD

**Issue by avtandil33** [freemint/freemint#35]
When played with EasyAraMint setup, I discovered following:

If I put lang = ru
or
lang = hu in Xaaes.cnf,

XaAES 'About' dialog is crashing. While other dialog items are OK.

To make clear experiment, I took initial setup and just added
rsc_lang  = 1 at the end of app_options = aessys line (to enable ZaAES
translation).

I  didn't  install any additional fonts, but in another installation -
even with all the fonts, XaAES behave the same.

I  scrolled  the  history - in 2014 we discussed same issue with Lars,
but didn't find any solution that time.

 Dima

**Comment by zabruder** [comment]
I cannot reproduce it. I tried:

current trunk-Xaaes from http://www.fairlite.co.uk/FreeMiNT/builds/freemint, my own build with and without memory-protection, and with the d_kur??.fnt-fonts (see attachments):

![59213fb0](https://cloud.githubusercontent.com/assets/3058322/26282025/6cc077cc-3e08-11e7-8666-b79eeae94bc6.gif)
![592137d2](https://cloud.githubusercontent.com/assets/3058322/26282027/72b499ba-3e08-11e7-81e2-966c358748ff.gif)
![59213438](https://cloud.githubusercontent.com/assets/3058322/26282029/78b56704-3e08-11e7-9377-04fe7c90df21.gif)


Please tell me how to reproduce the crash.

**Comment by avtandil33** [comment]
Hi, Helmut (I hope it's you:-) )

I used AranyM 1.02 and EasyAraMint (https://sites.google.com/site/emaappsarch/news/finallythebetaishere), based on mint 1-18 with added Russian fonts and edited assign.sys and fvdi.sys (info about Russian fonts added).

Then I see following:

![xaaes](https://cloud.githubusercontent.com/assets/28313867/26307539/ce480d66-3efd-11e7-8774-0a246f05430b.jpg)

 and system become stuck.

**Comment by avtandil33** [comment]
Hi, Helmut - I hope it's you ;-) !

I used AranyM 1.02 and [EasyAraMint](https://sites.google.com/site/emaappsarch/news/finallythebetaishere) , based on mint 1-18 with added Russian fonts and edited assign.sys and fvdi.sys (info about Russian fonts changed to Russian font).

Then I see following:

![xaaes](https://cloud.githubusercontent.com/assets/28313867/26307698/961d312c-3efe-11e7-8092-49bb8ebacdfb.jpg)

and system become stuck.

I didn't find the way how to test your trunk with EasyAraMint, as the path is different and system is not loading if I just put your trunk instead, but maybe if you test from scratch installation similar to my, you can find the reason of the crash.

Thanks !

Dima-

**Comment by mikrosk** [comment]
@avtandil33 I'd suggest to try this on latest build before filing a bug report, this might have been fixed years ago.

**Comment by avtandil33** [comment]
@mikrosk I agree, that this should be first step, but unlucky I was not successful to run new build. Already asked EasyAraMint author for update instruction.

**Comment by avtandil33** [comment]
@mikrosk I agree, that this should be first step, but unlucky I was not successful to run new build. Already asked EasyAraMint author for update instruction.

**Comment by zabruder** [comment]
I agree with mikro: You should run the current version. That is more important anyway ;)

And very likely the 1.18-version won't change anymore.

**Comment by zabruder** [comment]
No problem.
