### ISSUE TITLE
Recheck all filenames to be 8+3 only

### ISSUE THREAD

**Issue by mikrosk** [freemint/freemint#352]
ST-Zip otherwise complains and it's bad user experience. 

I once fixed it so it must have reappeared at some point.

**Comment by th-otto** [comment]
IIRC you fixed it for some docs, but not for the keyboard tables.

Using a variant of hatari's script, and manually filtering out files that are not included in any builds, i get
```
- ./fonts/cs/cp1250_08.txt -> cp1250_0.txt
- ./fonts/cs/cp1250_09.txt -> cp1250_0.txt
- ./fonts/cs/cp1250_10.txt -> cp1250_1.txt
- ./fonts/pl/ISO-8859-2.fnt -> ISO-8859.fnt
- ./sys/tbl/Czech/czech_iso.tbl -> czech_is.tbl
- ./sys/tbl/Czech/czech_kam.tbl -> czech_ka.tbl
- ./sys/tbl/France/french-pc.tbl -> french-p.tbl
- ./sys/tbl/Hungary/hungarian.tbl -> hungaria.tbl
- ./sys/tbl/Netherlands -> ./sys/tbl/Netherla
- ./sys/tbl/Norway/norwegian.tbl -> norwegia.tbl
- ./sys/tbl/Switzerland -> ./sys/tbl/Switzerl
- ./tools/mktbl/keyboards/british-pl.src -> british-.src
- ./tools/mktbl/keyboards/czech_iso.src -> czech_is.src
- ./tools/mktbl/keyboards/czech_kam.src -> czech_ka.src
- ./tools/mktbl/keyboards/french-pc.src -> french-p.src
- ./tools/mktbl/keyboards/french-pl.src -> french-p.src
- ./tools/mktbl/keyboards/german-pl.src -> german-p.src
- ./tools/mktbl/keyboards/hungarian.src -> hungaria.src
- ./tools/mktbl/keyboards/italian-pl.src -> italian-.src
- ./tools/mktbl/keyboards/norwegian.src -> norwegia.src
- ./tools/mktbl/keyboards/spanish-pl.src -> spanish-.src
- ./tools/mktbl/keyboards/swiss_french-pl.src -> swiss_fr.src
- ./tools/mktbl/keyboards/swiss_french.src -> swiss_fr.src
- ./tools/mktbl/keyboards/swiss_german-pl.src -> swiss_ge.src
- ./tools/mktbl/keyboards/swiss_german.src -> swiss_ge.src

Names that aren't unique:
- ['./fonts/cs/cp1250_08.txt', './fonts/cs/cp1250_09.txt']
- ['./tools/mktbl/keyboards/french-pc.src', './tools/mktbl/keyboards/french-pl.src']
- ['./tools/mktbl/keyboards/swiss_french-pl.src', './tools/mktbl/keyboards/swiss_french.src']
- ['./tools/mktbl/keyboards/swiss_german-pl.src', './tools/mktbl/keyboards/swiss_german.src']
```


[atari-check-dir.zip](https://github.com/user-attachments/files/16494169/atari-check-dir.zip)

**Comment by mikrosk** [comment]
Nice! @uweseimet feel free to give it a test in your ST Zip environment, hopefully now it goes without any warnings.

**Comment by uweseimet** [comment]
@mikrosk I'm afraid STZIP still reports errors, several times "Cannot write file". And at least some files (fsck.ext2, fsck.ext4) appear to be duplicates, because STZIP warns that they already exist.
I used the latest snapshot with STZIP for the Atari for testing. I guess you have not tested with STZIP but with something else?

**Comment by mikrosk** [comment]
Both valid points - the extfs tools slipped this check and indeed, at least I use unzip.ttp which seems to be more forgiving. I'll reopen this so we don't forget.

**Comment by th-otto** [comment]
>  at least some files (fsck.ext2, fsck.ext4) appear to be duplicates

Those are hardlinks originally. Maybe we should remove them, since there filenames are again too long, anyway.

Another problem is the toplevel directory name (eg. aranym-1-19-cc5) which will always be too long for 8+3.

**Comment by mikrosk** [comment]
I think nobody is doing to unzip aranym snapshot with ST Zip on a real machine. :)

It's totally OK to have this solved only for the ST/STE, TT/Falcon/clones and FireBee archives. However it also nicely points out on the fact  that we shouldn't overdo this initiative of supplying everything possible in the archive: hopefuly we somehow fix the extfs tools but unix world by default expects long names so we can't do this forever.

**Comment by th-otto** [comment]
fsck.ext2 etc. are just hardlinks to the real executable (e2fsck). The fscheck.sh script just uses e2fsck, so it should be save to omit them from the builds. Of course they can still be included in the rpm packages.

**Comment by th-otto** [comment]
Archives have been updated. Could someone pls. test on real hw? On aranym with hostfs, STZIP seems to behave differently.

**Comment by mikrosk** [comment]
I did, in both TOS and FreeMiNT depacking on a classic FAT 8+3 partition. No warnings reported.
