### ISSUE TITLE
XaAES compiled with -DGENERATE_DIAGS=1 doesn't start desktop

### ISSUE THREAD

**Issue by mikrosk** [freemint/freemint#355]
Tested in Aranym and Hatari (with mint030h.prg). One doesn't have to do anything else (e.g. enable the actual debug outputs in the boot menu's debug level selection), the flag alone prevents TeraDesk from launching.

**Comment by th-otto** [comment]
Tested with aranym and the xaaes040.km compiled with `-DGENERATE_DIAGS=1`, and cannot reproduce this. xa_boot.log also looks ok (ie contains lots of additional output).

Maybe an issue only in the Hatari kernel, because of OLDTOSFS?

**Comment by mikrosk** [comment]
That's weird, I tested it also on Aranym. What I did was:
- downloaded the latest snapshot
- built my own xaaes040.km, copied it to the snapshot
- built my own xaaes040.km with `DGENERATE_DIAGS=1`, copied it to the snapshot
- teradesk didn't start

I can try again tonight. I was using m68k gcc 7.5 (not mintelf).

**Comment by th-otto** [comment]
And you are sure that you used the current paths? The bootable builds use a prefix of 1-19-xxx (with xxx being the commit id), but when you compile something locally, it will use 1-19-cur.

**Comment by mikrosk** [comment]
Huh. That's a really great and unexpected find. :-)

**Comment by mikrosk** [comment]
Ok, this can be closed I guess. I still find it quite odd but oh well, I'm sure there are scenarios when this can come in handy.
