### ISSUE TITLE
Submenus in ResourceMaster has an odd offset (both x and y wise) under XaAES

### ISSUE THREAD

**Issue by GokMasE** [freemint/freemint#357]
When running ResourceMaster under XaAES the submenus (tested with both RSM 3.11 and RSM 3.65) shows up in a position that looks to be offset quite some distance from the expected place next to the parent menu object. What makes it even more mysterious is the fact that the two different submenus in the example screenshot below seems to end up with different offsets.

![cur_rsm1](https://github.com/user-attachments/assets/4a7b9774-cf07-468a-b360-ae5d7cc40222)
![cur_rsm2](https://github.com/user-attachments/assets/2456511e-31e4-4aff-ba93-c92ed4e0aa38)

Under N.AES the submenus are however placed in the expected position, where the submenu appear immediately to the right of the "=>" indicator.

My guess would be that XaAES is somehow affected by submenu objects initial OB_X relative to its parent. It almost looks like XaAES is calculating the correct position for the submenu but instead of doing:
`
OB_X(tree%,submenu&) = calculated_x&`

 it seems to end up with something more like:
 
` OB_X(tree%,submenu&)=OB_X(tree%,submenu&)+calculated_x&`

My suspiciouns are added to by the fact that moving the submenu objects in Tree026 and Tree027 in RSC.RSM (for RSM 3.65) to x=0 and y=0 seemingly corrects the displacement. However, I can't seem to reproduce this scenario in my own code, there it seems it does not matter what x/y position the submenu object has before a menu_popup() call.

Note: This glitch is also present in xaaes-ozk #241

**Comment by th-otto** [comment]
Should be fixed by https://github.com/freemint/freemint/commit/9f24d6efcd3f9a66cd70c7d6fa710f1b3c55aced

**Comment by GokMasE** [comment]
Confirmed fixed, submenus do appear on the expected location now - thanks for looking into it.
I'd be OK with closing as resolved.

**Additional note:** This is one of the occasions when XaAES is suffering aesthetically from not buffering the area below submenus. Since typically (most scenarios) the area under the submenus in this case belongs to the calling application itself (RSM), it has no way of managing those redraws during the blocking menu_popup call. I'll submit a separate issue for this later, so it can at least be discussed.

**Comment by th-otto** [comment]
Yes, i noticed that redraw problem too. Only seems to happen with the context menus, but not with the main menu,
