### ISSUE TITLE
XaAES setting ctlalta_survivors is ignored

### ISSUE THREAD

**Issue by skaftetryne** [freemint/freemint#366]
From my xaaes.cnf:

`ctlalta_survivors = "_aes_shell_", "taskbar ", "toswin2 "`

However, when pressing Control+Alt+A or selecting "Quit all Apps" from the task manager, these applications are killed as well.

**Comment by mikrosk** [comment]
Isn't the meaning exactly the opposite? I.e. you list applications which do not like the term signal and have to be killed manually?

**Comment by mikrosk** [comment]
Oh, now I see, it's like you say. Never tried it.

**Comment by skaftetryne** [comment]
I've never used it until today when I was debugging https://www.atari-forum.com/viewtopic.php?p=467679#p467679 and had to kill 120 running applications.

**Comment by skaftetryne** [comment]
Correct, that was the problem! Btw. I see that the xaaes.cnf example on the wiki still has this typo (and is outdated in a couple of other areas as well).

**Comment by th-otto** [comment]
The typo in the wiki is fixed. For other things, the wiki should be compared again to current example.cnf

**Comment by mikrosk** [comment]
freemint.stg should be also fine. I wonder whether the wiki shouldn't just point to the hyp  on Thorsten's server in such areas, to avoid duplicity.

**Comment by th-otto** [comment]
The contents are (hopefully)  mostly identical, but a wiki just looks much better than a hyp file which is converted back to html. Also the xaaes.hyp on my server is not automatically  updated by new builds.

**Comment by mikrosk** [comment]
And on top of that, the wiki is searchable. Oh well.
