### ISSUE TITLE
Add TosWin2 to ARAnyM archive

### ISSUE THREAD

**Issue by vinriviere** [freemint/freemint#37]
It would be good to add TosWin2 binaries to the ARAnyM archive, so users can easily run textmode programs out of the box.

**Comment by mikrosk** [comment]
Not only it would be good, it would be also very useful and that's the reason why it's already there: aranym-1-19-ce5.zip\aranym-1-19-ce5\drive_c\mint\1-19-ce5\sysroot\GEM\toswin2 and configured to run .ttp/.tos programs and autostarted ;-)

**Comment by vinriviere** [comment]
Apologies, I confused with missing bash... which would be problematic to add without a full POSIX tree, of course.

**Comment by mikrosk** [comment]
@vinriviere: Anyway, you're right. I've been thinking about this too but I don't know what exactly is needed (to make it at least partially usable, i.e. with history, auto completion etc). Maybe just your builds of `bash` and `coreutils` would do the trick?

It wouldn't be good only for Aranym but I guess also for plain freemint builds but here we are facing the problem of short file names (but maybe not a problem as most of the coreutils tools are quite short -- ls, cp, mkdir, ...)
