### ISSUE TITLE
Question on XHDI partition type handling

### ISSUE THREAD

**Issue by uweseimet** [freemint/freemint#370]
As there is no "Discussions" area for this project I hope it's OK to create a ticket for asking a question.

How does MiNT handle the TOS partition types "F32" and "LNX" compared to the equivalent DOS partition types $0c and $0e (both FAT32) and $83 (ext2)?
My expectation is that "F32" is handled like $0c and $0e, and "LNX" is handled like $83.

As far as I know you can also use "RAW" for ext2 partitions. Or is "RAW" the only valid type for ext2 partitions and "LNX" and $83 are not supported?

**Comment by th-otto** [comment]
On Sonntag, 18. August 2024 09:58:35 CEST Uwe Seimet wrote:
> As far as I know you can also use "RAW" for ext2 partitions. Or is "RAW" the
> only valid type for ext2 partitions and "LNX" and $83 are not supported?

IIRC the ext2fs driver does not care at all about the partition id, and only 
checks the super block of the filesystem. But i would prefer to use 'LNX' 
instead of 'RAW', because the latter can just be anything, and eg. minix is 
still supported, too. For a partitioning tool, it would make clearer that 
there is a ext2 partition.

Only the fatfs drivers checks the partition id to be some kind of FAT (F32, 
GEM, BGM, or some DOS style id)

**Comment by uweseimet** [comment]
OK, this means that HDDRIVER may map DOS XHDI types to the corresponding TOS XHDI types or vice versa.

Regarding "LNX", this may not work as you would like it to with some hard disk drivers. HDDRIVER has an option to treat "LNX"/$83 and "MIX" like XHDI raw partitions, and this option is enabled by default. But other drivers might only accept "RAW" as XHDI raw partition.

**Comment by uweseimet** [comment]
Below is the mapping I will use, including the Linux and Minix types, which on the Atari are only usable with MiNT.
In case of a GPT, HDDRIVER will use the TOS types for XHDI where possible. The only GPT type that differs between TOS and DOS is the FAT16 type. Note that TOS and DOS/Windows types can coexist in a GPT.
With an MBR there is no change, i.e. DOS types are not replaced by TOS types.

<table>
  <tr>
    <th scope="col">GPT Type</th>
    <th scope="col">Designation</th>
    <th scope="col">DOS MBR Type</th>
    <th scope="col">TOS MBR Type</th>
    <th scope="col">XHDI Type</th>
  </tr>
  <tr>
    <td>EBD0A0A2-B9E5-4433-87C0-68B6B72699C7</td>
    <td>Microsoft basic data</td>
    <td>$0E (FAT16 LBA),<br />$0C (FAT32 LBA)</td>
    <td>-</td>
    <td>$0E,<br />"F32"</td>
 </tr>
  <tr>
    <td>0FC63DAF-8483-4772-8E79-3D69D8477DE4</td>
    <td>Linux filesystem</td>
    <td>$83</td>
    <td>"LNX"</td>
    <td>"LNX"</td>
  </tr>
  <tr>
    <td>734E5AFE-F61A-11E6-BC64-92361F002671</td>
    <td>Atari TOS basic data</td>
    <td>-</td>
    <td>"BGM" (FAT16),<br />"F32" (FAT32)</td>
    <td>"BGM",<br />"F32"</td>
 </tr>
  <tr>
    <td>35540011-B055-499F-842D-C69AECA357B7</td>
    <td>Atari TOS raw data (XHDI)</td>
    <td>-</td>
    <td>"RAW"</td>
    <td>"RAW"</td>
  </tr>
  <tr>
    <td>481B2A38-0561-420B-B72A-F1C4988EFC16</td>
    <td>Minix filesystem</td>
    <td>-</td>
    <td>"MIX"</td>
    <td>"MIX"</td>
  </tr>
</table>

The next release of fdisk (util-linux) will recognize the TOS and Minux GUIDs.
