### ISSUE TITLE
wind_get(WF_NAME) broken?

### ISSUE THREAD

**Issue by th-otto** [freemint/freemint#383]
It occurs to me that the implementation in XaAES is broken, or atleast incompatible to MagiC/WinX. The gemlib states:

```
 *  <tr><td> #WF_NAME <td> 2 <td>
 * 	         Gets the actual title of the window
 *           - copies the title in the buffer pointed by \a W1.
```

Same would apply to wind_get(WF_INFO)

It handles this special case by putting the address of W1 into the intin array, and XaAES implements it this way by copying the window name to this address:

https://github.com/freemint/freemint/blob/eef4c5db023554346d8b3c1c365be026e7b60acb/xaaes/src.km/xa_wind.c#L1277-L1278
and
https://github.com/freemint/freemint/blob/eef4c5db023554346d8b3c1c365be026e7b60acb/xaaes/src.km/c_window.c#L764-L770

However, MagiC behaves differently, and returns the address of the name in intout[1/2], without copying the actual string:
https://github.com/th-otto/MagicMac/blob/951522e6c949672cae888ebaa3695ef7ed0e4eaf/kernel/aes/aeswin.s#L2044-L2046
WinX is documented to do the same as MagiC (however in my tests i get an error).
N.AES seems to do the same as XaAES (copying the string). AES 4.1 reports an error code (0) on return.
There is also an A-MAN utility from Sven Kopacz that implements some of these functions, and that behaves the same as MagiC.

Attached is a small test program (must be compiled by Pure-C, because there is no way in gemlib to get the actual values from the intout array).

[windget.zip](https://github.com/user-attachments/files/17173884/windget.zip)

I don't know whether any program actually uses that feature. But we should atleast handle the case MagiC works in the gemlib binding.

**Comment by mikrosk** [comment]
You are right, it's not a very common feature. I could find only one application using it and not surprisingly it is a taskbar-like one: https://www.atariuptodate.de/en/1959/startmeup. It seems to follow the MagiC way:
```C
		short aa2,aa3,pxy[8];
		if(aes_avail.get_window_owner)
			{
			char *text=NULL;
			aa4 = mt_wind_get(i, WF_OWNER, &MyTask.actual_win_on_top, &aa2, &aa3, &aa3, (short*)&_GemParBlk.global[0]);
			mt_wind_get(i, WF_NAME, (short*)&pxy[0], (short*)&pxy[1], (short*)&pxy[2], (short*)&pxy[3], (short*)&_GemParBlk.global[0]);
			text = *(char **)&pxy[0];
```

**Comment by th-otto** [comment]
Hm, where did you take the source from? In the one from T.Muchs site (https://www.snailshell.de/SMU/archive/smu8src.lzh ) i don't see such a call.

Anyway, if there are really applications that depend on MagiCs behaviour, we have to change both gemlib and XaAES. Changing gemlib would be relative easy (you just have to preset the intout array, and check the return values). For changing XaAES i think we can check the number of intin parameters (gemlib already changes that to "4" for the call, but the Pure-C library uses "2" as for all other calls).

**Comment by mikrosk** [comment]
It's available here: https://github.com/ggnkua/Atari_ST_Sources/tree/master/C/Rafal%20Kawecki/MYTASK (under this odd name) but the same archive is also in Thomas Much's folder with the same readme.txt about not using the original name): https://github.com/ggnkua/Atari_ST_Sources/tree/master/C/Thomas%20Much/MYTASK

**Comment by th-otto** [comment]
Ah ok. Both versions seem to be based on SMU, but later changed by R.Kawecki

**Comment by mikrosk** [comment]
Cool. If you verified its behaviour against MagiC and N.AES, feel free to close this one.

**Comment by th-otto** [comment]
I used my test program from above. If you change one line to 
```
	_GemParBlk.acontrl[1] = 2; /* nintin */
```
XaAES behaves like MagiC now. That should make SMU/MYTASK work. The new gemlib binding also handles both cases  now.
