### ISSUE TITLE
Mailing list dead?

### ISSUE THREAD

**Issue by skaftetryne** [freemint/freemint#386]
Is the mailing list down? It has been quiet since Sep 17th, I sent a mail to it earlier this evening but have received nothing. It's nothing since Sep 17th on the archive page either: https://sourceforge.net/p/freemint/mailman/freemint-discuss/

**Comment by mikrosk** [comment]
If it is, it must be a global SF.net issue. Rarely they do suffer from downtimes but what is important: it is not our problem. :)

**Comment by skaftetryne** [comment]
Your test mail arrived, but the mail I sent earlier this evening has not (yet). It has not bounced either. I will try to subscribe (again) and see what happens.

**Comment by mikrosk** [comment]
Your has arrived as well.

**Comment by skaftetryne** [comment]
It took 40 minutes... My 2nd attempt arrived almost instantly. Looks like the mailing list just needed to be woken up :)
