### ISSUE TITLE
Daynaport driver (scsilink.xif) fails to compile

### ISSUE THREAD

**Issue by th-otto** [freemint/freemint#45]
When do a fresh clone of the repo, then
$ export M68K_ATARI_MINT_CROSS=yes
$ make

i get

make[4]: Entering directory `/home/sebilla/freemint/sys/sockets/xif/daynaport'
m68k-atari-mint-gcc -I../.. -I../../.. -D__KERNEL_XDD__ -Werror -mshort -g -O2 -fomit-frame-pointer -Wall -Wmissing-prototypes -Wshadow -Wpointer-arith -Waggregate-return -c scsilink.c -o scsilink.o
scsilink.c: In function 'driver_init':
scsilink.c:192:2: error: passing argument 3 of 's_system' makes integer from pointer without a cast [-Werror]
../../../libkern/kernel_xfs_xdd.h:671:13: note: expected 'ulong' but argument is of type 'void *'
cc1: all warnings being treated as errors

Strangely, the last automatic builds via travis do not seem to be affected by this. Also notice that there is no -m68xx switch in the compile command, although the Makefile specifies CPU = 020-60. As already mentioned on the ML, any CPU = statement in the Makefile(s) must be done *before* RULES is included.

**Comment by mikrosk** [comment]
I guess you're using gcc > 4.6.4.

However I can reproduce the lack of `-m68020-60`, any idea what has caused it?

**Comment by mikrosk** [comment]
> it's bad positionioning of the CPU= statement

Hmm, there must be something more to it. Look at `xdd/dsp56k`, it's nearly the same Makefile and it works properly.

**Comment by th-otto** [comment]
no, just normal one:

m68k-atari-mint-gcc --version
m68k-atari-mint-gcc (GCC) 4.6.4 (MiNT 20130415)

**Comment by mikrosk** [comment]
I'm using the same and can compile it fine.

**Comment by th-otto** [comment]
Hm, that must be the NULL argument. Maybe some header slips in that defines it as ((void *)0), which it should be rather than just 0. In any case, using NULL when the function expects ulong is simply wrong. OTOH, that arg2 of s_system should actually be a pointer to a long.

**Comment by th-otto** [comment]
> Hmm, there must be something more to it. Look at xdd/dsp56k, it's nearly the same Makefile and it works properly.

not for me:

$ cd sys/xdd/dsp56k
$ rm dsp56k.o
$ make dsp56k.o
m68k-atari-mint-gcc -I../.. -D__KERNEL_XDD__ -Werror -mshort -g -O2 -fomit-frame-pointer -Wall -Wmissing-prototypes -Wshadow -Wpointer-arith -Waggregate-return -c dsp56k.c -o dsp56k.o

There is no -m68020-60 either.

**Comment by mikrosk** [comment]
Damn, you're right again! :) I got fooled by that libkern build.

**Comment by mikrosk** [comment]
Fixed by #48
