### ISSUE TITLE
Figure out how to approach XaAES development

### ISSUE THREAD

**Issue by mikrosk** [freemint/freemint#5]
@zabruder has accidentally overwritten my post ;)

So Helmut's point of view here:

> There was enough time for anyone to report problems before 1.18 was released.
>  I actually don't care what people now say after 6+ years.
> 
> If people think the 1.16-XaAES is better, I would suggest to compile the 1.16-XaAES with the current interface/lib and use that.
> 
> I will probably update my stuff from time to time.
> 
> Mikro, I told you before that I want to update anything in my branch from trunk, and thought that when everything is successfully tested merge my branch into trunk 
> But that's only my idea,
> And no one tests anything anyway, that's why my motivation is at -3.
> Separating XaAES into modules is not anything I will to, but everyone is free to do so.
> No complaint is concrete enough for me to be able to satisfy it (what means "too big"? 490kB is small these days), and what is the actual problem it causes? Not being able to run XaAES on a 2MB-ST? Or is it just a matter of taste? 
> 
> I think If people find bugs, they should report them, and maybe they are already fixed in my branch, whose XaAES can be used with the trunk-kernel.
> 
> Of course I'm gone when XaAES gets reverted to 1.16-level.

This is a good discussion start point anyway. For the future, please use the comment button below. ;)

**Comment by skaftetryne** [comment]
My personal opinion: The XaAES kernel module is too big and contains stuff that would be more suitable in userspace. I'd like to see stuff removed, with clean hooks that allows us to move these features into userspace. File selector, task manager, system/log window, wallpaper generator... All nice and usable features, but not needed in the kernel itself.
Less code in the kernel means fewer bugs that can potentially crash the system. Moving features to user applications also means it's easier to create replacements/enhancements without changing a single byte in the kernel.

**Comment by mikrosk** [comment]
@skaftetryne how does the version shipped with 1.16.x holds against that "too big and too much stuff" statement? (of course, there isn't any modular stuff and hooks) I'm wondering  how hard would be to reset to 1.16.x, cherry pick fixes and the "good" features start from there.

Or, what are the most important differences between the old (1.16.x) XaAES and the current one? For me, XaAES was only, well, an AES, I didn't care for stuff like taking screenshots and multilingual help support.

Either way, we can safely assume that Helmut is not going to help out. ;)

**Comment by skaftetryne** [comment]
I can't remember how 1.16 was :) I'm using 1.19 myself.

Please note that I'm not saying that the features are bad or unnecessary. I'm saying that there's too much stuff in the kernel module that should be moved to user space instead. This is not necessarily limited to post 1.16 additions.

**Comment by mikrosk** [comment]
Well, that's what is this task about -- figure out what to keep, what to move away to userspace apps and what to throw away / revert. Going through all [xaaes commits](https://github.com/freemint/freemint/commits/master/xaaes) reveals that there hasn't been much development between 2017 - 2013.

**Comment by mikrosk** [comment]
@zabruder I think nobody is saying that everything you do / did should be thrown away, I guess the biggest problem has been communication -- I personally even don't know in what shape your branch is, whether it's for other users or only for you etc.

Now we have git and easy merges (and more importantly -- easy cherry picks and bisects when a regression is found) things should be easier.

What I would suggest (just my two cents) is to go through your [git log](https://github.com/freemint/freemint/commits/helmut-enhancements) over the years and think about all the changes you did -- you best know which are complex, which are easy. Then come up with a list of pull requests which could be discussed separately. If some PR depends on another, start with the first one and go from there.

I think the trouble with testing your branch was that a) some people (like me) didn't even know it's for testing b) there's too many changes so perhaps people would like feature A but not B, C and D so they stayed with trunk.

Me, @vinriviere, @mfro0 and others can help you with git stuff (that's what the mailing list is for) but of course, the hard stuff (deciding the feature / pull request list) is up to you, nobody knows your code better. ;)

Sounds reasonable?

**Comment by zabruder** [comment]
There are at least 2 people that use(d) my branch because it has fixes for hatari and pak/3 (68020-detection), and trunk does not work there.

And I remember me saying more than once: Try my branch, but got nearly no feedback.

For me the main work will be to pick/improve the stuff from trunk, that's missing. Then I would make a request for testing. Then I would put a diff here. Don't expect anything soon - more important tasks atm.

I'm not sure if my branch is in the right shape for everybody yet.
But of course I'd be happy to see reports.
I can't exactly say what's missing except that there are only max. 32 handles per process in my branch, that would be the next thing to do.

**Comment by jflemaire** [comment]
My input on the matter, for those interested:

-- Helmut's branch: I did try it once or twice but had one or more issues that I can't remember. The problem, from a testing point of view, is that when I fire up my FIrebee it is for developing my own projects, which means that I need a working system. I simply don't have to time test, suffer craches, report bugs, etc. But this doesn't mean in any way that I'm not interested in Helmut's work, on the contrary.

-- XaAES 1.16 versus current versions: I'm running kernel 1.19 myself and most (if not all) improvements in the AES were added by Helmut (configurable shortcuts, bubblegem, background pictures, multilingual support, etc). These are all important changes that make the system more modern and more open. I wouldn't dream of going back to 1.16.

-- Move features in userspace: a nice idea in theory, but remember that we finally got rid of BubbleGEM-induced crashes when Helmut implemented the bubblegem features inside the kernel. Badly-written userspace extensions can break the system too. On the other hand, if, say, the file manager was run as a separate program, it would probably be less daunting for modest GEM coders like myself to look at its code and suggest modifications. 

-- Lack of testing and reports: I think it's fair to say that publicity and ease of upgrade have never been FreeMiNT's forte :-) If we want some new experimental feature to be tested, we should first think about how easy it is for non-technical but willing testers to change the kernel/AES with easy means of going back to their working system. And we should publicise that we need testers. The mailing list is not enough.

**Comment by mikrosk** [comment]
> If we want some new experimental feature to be tested, we should first think about how easy it is for non-technical but willing testers to change the kernel/AES with easy means of going back to their working system. And we should publicise that we need testers. The mailing list is not enough.

This is so true. I have some plans in this matter because I also find this as one of the biggest obstacles to get proper testing from normal users.

**Comment by zabruder** [comment]
Now you might guess why I only commit to my branch :)

**Comment by zabruder** [comment]
As for removing my extensions from XaAES:

Many of them are compiler-conditional (see https://github.com/freemint/freemint/blob/master/xaaes/src.km/xa_defs.h). If someone wants to have them removed, maybe setting the values to 0 is an option. Likely it won't compile nor run but to fix that that would up to the person doing it.

**Comment by mikrosk** [comment]
@zabruder I even don't know what the features are. :-) Would it be possible to assemble a list of features/extensions/fixes/enhancements against the main version? In other words, how would you sell me your branch? ;)

**Comment by zabruder** [comment]
The xa_defs.h I cited is the one from trunk. It's all explained in the comments. If you don't understand them, just try them all.

I thought we're talking about the trunk-XaAES?

**Comment by mikrosk** [comment]
Ah, sorry, didn't read it properly. Anyway, that list would be still useful. ;-)

**Comment by zabruder** [comment]
Everything that bothers you ;)

**Comment by mikrosk** [comment]
Found a similar/related discussion here: https://mikro.naprvyraz.sk/mint/freemint-list/Week-of-Mon-20161031/000262.html

**Comment by mikrosk** [comment]
With Helmut's definitive departure, I think this can be closed. As for:

> If people think the 1.16-XaAES is better, I would suggest to compile the 1.16-XaAES with the current interface/lib and use that.

And I did, see #241. There are similar points raised as well.
