### ISSUE TITLE
Travis builds currently failing

### ISSUE THREAD

**Issue by th-otto** [freemint/freemint#54]
Since the switch to launchpad ppa, at least on my forked repo the builds are now failing. I see that the scripts have already been updated, but in the log i get lots of lines like:

W: Failed to fetch http://ppa.launchpad.net/george-edison55/cmake-3.x/ubuntu/dists/trusty/InRelease  

See [log](https://travis-ci.org/th-otto/freemint/jobs/241660824) for details.

**Comment by mikrosk** [comment]
That's because your `.travis.yml` still contains the old version: https://github.com/th-otto/freemint/blob/PR-5/.travis.yml ... remove the word `trusty` and you should be fine.

**Comment by th-otto** [comment]
Yup i noticed already, thx. Had to merge not only the master branch with current updates from upstream, but also all PR branches. And also the travis-script fork.
