### ISSUE TITLE
Questionable CPU interrupt mask handling in USB stack

### ISSUE THREAD

**Issue by czietz** [freemint/freemint#63]
While reviewing the code of FreeMiNT's USB stack I found some code that I believe is wrong. More precisely, the handling of the 68k's interrupt mask in the EtherNat driver. The pack_fifo() and unpack_fifo() functions increase the interrupt mask (to 6), in order not be interrupted during their work. That's OK, of course. 

However, they call set_old_int_lvl() (see https://github.com/freemint/freemint/blob/1d45d4f8216b5f780577d5f15fbe0e3651273438/sys/usb/src.km/ucd/ethernat/isp116x-hcd.c#L636 for an example) when they are finished. Other than one might suspect given the function name, set_old_int_lvl() does _not_ restore the previous interrupt mask. Instead it takes a word from the top of the stack and uses that as new mask, as can be seen here: https://github.com/freemint/freemint/blob/1d45d4f8216b5f780577d5f15fbe0e3651273438/sys/usb/src.km/ucd/ethernat/ethernat_int.S#L66. 

This only makes sense when used at the very beginning of an interrupt handler, where in fact the previous interrupt mask (or rather: the previous value of SR) is on the stack. In the EtherNat USB driver however, it will just set the interrupt mask to an arbitrary value, depending on what happens to be on the stack. I don't know if something in the MiNT kernel will reset the interrupt mask to the correct value, however, I think the current code is wrong.

**Comment by mikrosk** [comment]
I think you're right with the exception the value on the stack isn't random, it always be the PC before the jump. Not that it changes anything about it being wrong.

Even the interrupt handler usage is wrong here:
https://github.com/freemint/freemint/blob/1d45d4f8216b5f780577d5f15fbe0e3651273438/sys/usb/src.km/ucd/ethernat/isp116x-hcd.c#L1608
because the stack already contains the return address from 
https://github.com/freemint/freemint/blob/1d45d4f8216b5f780577d5f15fbe0e3651273438/sys/usb/src.km/ucd/ethernat/ethernat_int.S#L57

If you could provide a patch that would be great. :)

**Comment by mikrosk** [comment]
Added David Galvez to the loop, David please take a look at
https://github.com/freemint/freemint/issues/63 in case you didn't receive
the notification.

-- 
MiKRO / Mystic Bytes
http://mikro.atari.org

**Comment by czietz** [comment]
Attached is a proposed patch. With that set_int_lvl6() stores the value of SR in oldSR. The interrupt handler already wrote to oldSR, which was never read, however. With the patch set_old_int_lvl() then restores the previous interrupt mask -- either before set_int_lvl6 or before the interrupt occured.

Note that I do not have an EtherNat, so I could only test that the code compiles.

[ethernet_int_diff.patch.txt](https://github.com/freemint/freemint/files/1221633/ethernet_int_diff.patch.txt)

**Comment by mikrosk** [comment]
@czietz I've created a pull request with your patch so it can be easily reviewed & merged.

**Comment by atic-atac** [comment]
So what does the "andi.w #0x0f00,oldSR" in _set_old_int_lvl do now as it has no defined contents in oldSR.

The patch doesn't look right to me.

**Comment by atic-atac** [comment]
The ethernat_int() routine calls these in the reverse order to pack_fifo/unpack_fifo. Beware of this.

**Comment by czietz** [comment]
But oldSR has been set be either the interrupt handler or set_int_lvl6, as noted before. 

Hence, my patch will work either way: When set_old_int_lvl() is called near the beginning of the interrupt handler, it will restore the interrupt mask to the value saved in oldSR in
https://github.com/freemint/freemint/blob/1d45d4f8216b5f780577d5f15fbe0e3651273438/sys/usb/src.km/ucd/ethernat/ethernat_int.S#L55

When set_old_int_lvl() is called in the end of pack_fifo/unpack_fifo, it will restore the interrupt mask to the value saved in oldSR in set_int_lvl6(). Have a look at the NetUSBee driver, where it is implemented in exactly the same way!

**Comment by mikrosk** [comment]
@atic-atac are you sure? pack_fifo/unpack_fifo call `set_int_lvl6()` before that setting `oldSR` to correct value. And `ethernat_int()` is always called from the interrupt handler which sets the `oldSR` too. I think the patch is correct.

**Comment by atic-atac** [comment]
What happens if ethernat_int() is called when pack/unpack hasn't been called at all ?

What value is in oldSR ?

I'm not going to commit this until someone with an ethernat verifies the behaviour.

**Comment by czietz** [comment]
@atic-atac: 
> What happens if ethernat_int() is called when pack/unpack hasn't been called at all ?
> What value is in oldSR ?

The value written into oldSR by this line of existing code before calling ethernat_int():
https://github.com/freemint/freemint/blob/1d45d4f8216b5f780577d5f15fbe0e3651273438/sys/usb/src.km/ucd/ethernat/ethernat_int.S#L55

I feel I'm repeating myself over and over again.

> I'm not going to commit this until someone with an ethernat verifies the behaviour.

Well, it's certainly horrendously wrong as it is now...

**Comment by atic-atac** [comment]
Repeating yourself is good. It gets the point across.

As for being horrendously wrong, I'll wait for someone with an EtherNAT to verify, as I know the EtherNAT has worked before, and the NetUSBee has never worked.

**Comment by czietz** [comment]
Sure, I'm always for testing code. However, I hope we can all agree that taking the _address_ of the caller from the stack -- as mikrosk noted in https://github.com/freemint/freemint/issues/63#issuecomment-322070742 -- and using that as an _interrupt mask_ is definitively wrong. That's what set_old_int_lvl() currently does.

**Comment by DavidGZ** [comment]
Thanks czietz for spotting this bug, if I remember correctly I based the interrupt routine for the USB function of the card from the network driver, as Miro already noticed. Unfortunately I don't have the hardware now to test your fix, my CT60 is dead, somebody else should do it.
