### ISSUE TITLE
Wrong XHDI handler installation in USB storage driver

### ISSUE THREAD

**Issue by czietz** [freemint/freemint#67]
While investigating some weird crashes that happened as soon as the USB storage driver was loaded (_regardless_ of whether a USB mass storage device was actually present), I found an error in the installation of the XHDI handler by the USB storage driver.

This bug only shows up when another XHDI driver that supports the XHDINewCookie opcode is already present, such as e.g. HDDRIVER. (Note that FreeMiNT's own implementation of XHDI doesn't seem to support the XHDINewCookie opcode.)
Then...
https://github.com/freemint/freemint/blob/94d3b38f3ebd640d9a3d0b4a645d3f16dbb59f5e/sys/usb/src.km/udd/storage/xhdi.c#L1082
... will install the _xhdi_handler()_ function as new XHDI handler, whereas the actual XHDI handler needs to be...
https://github.com/freemint/freemint/blob/94d3b38f3ebd640d9a3d0b4a645d3f16dbb59f5e/sys/usb/src.km/udd/storage/xhdiasm.S#L5
... like it is installed for TOS.

_xhdi_handler_ expects a single parameter, a pointer to the stack area where all the actual parameters are. However, this pointer is only pushed by __usbxhdi_, hence it has to be called first.

Attached is a Hatari harddisk image and configuration file to reproduce the bug: [mint-usb-crash.zip](https://github.com/freemint/freemint/files/1261216/mint-usb-crash.zip) (Note that the bug is in no way related to Hatari, it will trigger on real hardware just the same.) Start Hatari with the provided config file, wait for the Desktop to load and double click for example on drive B: or drive D:. The Desktop will then crash with...
![grafik](https://user-images.githubusercontent.com/9830685/29836265-fa46172e-8cf4-11e7-8b43-d12710df4158.png)

If you follow the information given by Hatari for this crash (`Address Error at address $c0001, PC=$eb534 addr_e3=eb534 op_e3=c50`), you'll find that it crashes right at the beginning of _xhdi_handler()_. Changing the corresponding line to `return xhnewcookie(usbxhdi);` fixes the bug.

**Comment by atic-atac** [comment]
Thanks, and pushed the fix.

**Comment by mikrosk** [comment]
Just for the record, this fix should have been present along with 0ef684ab because until that commit it actually worked (perhaps unintentionally...) just because `xhdi_handler` expected a `short` and not a pointer.
