### ISSUE TITLE
XIF Driver no langer loaded ...

### ISSUE THREAD

**Issue by franklukas** [freemint/freemint#69]
In all MiNT 1-19 Versions the "lance.xif" are no longer loaded. With 1-18-1 it is fine, but not longer with 1-19. I try versions trunk and helmut from 2015 to 2017 and the 1-19-214. When you have not the Hardware it does not matter. There comes always a message "Loading interfaces: AM7990 driver for PAMs VME ..."

**Comment by franklukas** [comment]
czietz told me that it works fine under Hatari but on my Atari TT it doesn't work. I check it multiple times ...

**Comment by mikrosk** [comment]
I'm afraid that unless you prove this is happening on another TT as well I can't help you. :-( Works fine on my CT60 (!), correctly saying no hardware found.

**Comment by czietz** [comment]
I followed up with Frank in the German Atari-Home forum. The driver is in fact loaded correctly! However the load message was redirected to the boot log and was thus not visible on screen, which was the source of some confusion.

I leave it to either @franklukas or one of the maintainers to close this issue report.
