### ISSUE TITLE
PCI BIOS isn't working properly

### ISSUE THREAD

**Issue by mikrosk** [freemint/freemint#71]
Thanks to @Kroll2017, we managed to pinpoint this in an [AF thread](http://www.atari-forum.com/viewtopic.php?f=97&t=31641&start=25#p328219). When the last 1.19 kernel commit before adding PCI BIOS is used (310db4930311ac7b71047310be1f968379f539a3), his network card works. When I use a build from a commit slightly after adding PCI BIOS (6787b90c1aa8570c6117f800d3debeed764b6469 -- it is supposed to contain an important fix to the API), it doesn't work.

This also applies to another problem with USB keyboard/mouse, [as mentioned](http://www.atari-forum.com/viewtopic.php?f=97&t=30680&p=328503#p328503) in the same thread.

So it seems like the wrapper isn't 100% done (same behaviour can be observed on latest builds), @DavidGZ any insights?

**Comment by mikrosk** [comment]
Also, the driver in question: https://github.com/mikrosk/freemint/blob/rtl8139/sys/sockets/xif/rtl8139.c uses trap calls for PCI BIOS calling. Could that be a problem?

**Comment by DavidGZ** [comment]
As @Kroll2017 is using a CTPCI most probably the issue is related with what is explained in sys/pcibios.c:

`	/* Some PCI-BIOS functions in FireTOS and CTPCI PCI-BIOS get the
	 * cookie value every time they're called to calculate the place
	 * in memory where descriptors are stored, as the cookie value
	 * is replaced by MiNT the memory addresses calculated are wrong,
	 * so to avoid this we need to make this hack. Resource and status
	 * descriptors are store following the PCI-BIOS functions jump table.
	 */
	r = get_toscookie(COOKIE__CPU, &t); /* cf68klib in FireTOS emulates 68060 CPU */
	if (!r && t == 60)
		if (!get_toscookie(COOKIE__CF_, &dummy) ||	/* Test for FireTOS */
		     !get_toscookie(COOKIE_CT60, &dummy)) {	/* Test for CT60 (CTPCI) */
			/* Copy descriptors following the PCI-BIOS structure */
			memcpy(&(pcibios_MiNT.pci_rsc_desc), pcibios + 1, 
				PCI_MAX_HANDLE * PCI_MAX_FUNCTION * ((sizeof(PCI_RSC_DESC) *  PCI_MAX_RSC_DESC) + sizeof(PCI_STS_DESC)));
			r = set_toscookie (COOKIE__PCI, (long) &pcibios_MiNT);
}`

So until we figure out what's going on I would remove the -DPCI_BIOS flag for the 060 kernel.

**Comment by mikrosk** [comment]
@kroll2017, when you try [latest build](https://github.com/freemint/freemint.github.io/blob/master/builds/freemint/master/new/freemint-1-19-f51-020.zip) with David's commit included, does it solve your PCI USB / network card problems?

**Comment by DavidGZ** [comment]
I think I've found the problem. CT60TOS and FireTOS keeps some data just behind the PCI-BIOS functions jump table. I must have calculated the size of this area looking at CT60TOS version 1.04 sources, in the following version (2.00) this area size increased. I think the PCI code in the version 1.04 isn't functional so I'll assume only the size in version > 2.00 is the right one and nobody is using the CTPCI with version 1.04. @mikrosk do you know this?

I'll upload some a current kernel with the change in AF for people to test.

**Comment by mikrosk** [comment]
Yes, 1.04 is virtually unusable with the CTPCI. I think it boots but has many bugs. I don't think anybody is using it.

**Comment by DavidGZ** [comment]
The correction of the private-data's size being copied which is commented above didn't fix the problem, it's strange that the issue doesn't arise under FireTOS. Finally I've decided to implemented another solution as a workaround, I've just pushed the commit, it's everything explained there.

**Comment by mikrosk** [comment]
Thanks to heroic effort of @DavidGZ it has been fixed. Confirmed by @Kroll2017 on AF.
