### ISSUE TITLE
Missing xaaes.inf

### ISSUE THREAD

**Issue by ojaksch** [freemint/freemint#77]
At least with trunk-19112017.tar.bz2 I observed a message about missing xaaes.inf when XaAES starts.
I then created an empty xaaes.inf file and XaAES complains about an existing but empty file.
Helmut told me to simply press Ctrl-Alt-S within XaAES so it writes it's setting to xaaes.inf. This works but now XaAES spits out a message at starting that it could read and use the settings written there.

This behaviour is comprehensibly but ugly. So one should point out to xaaes.inf, include an empty one and read ahead silently, or include a xaaes.inf with some useful defaults IMHO.

**Comment by mikrosk** [comment]
If you want a working system straight out of the box, don't use the trunk-XXYYZZZZ.tar.bz2 archives but the 'prepackaged' ones: https://freemint.github.io/#snapshots
