### ISSUE TITLE
umouse.prg doesn't work well in FreeMiNT

### ISSUE THREAD

**Issue by infusixllc** [freemint/freemint#78]
Hello, recent Travis build 6b9 on falcon with ct60 and ethernat.  Umouse.prg works fine under tos but under mint the usb drivers aren't working quite correctly.  mousepoll process consumes 95% cpu and mouse is jerky.  This is a microsoft USB optical mouse.  Any ideas?

**Comment by mikrosk** [comment]
This has been reported already (I think even multiple times), see for instance: http://mikro.atari.org/mint/201509/msg00017.html but unfortunately, nothing hasn't changed AFAIK. @DavidGZ ?

**Comment by infusixllc** [comment]
Ah I see.  Makes sense thanks.

**Comment by DavidGZ** [comment]
The mouse driver was made by Alan, I can't help here.

**Comment by czietz** [comment]
From my work for the Lightning VME I can say that it's not necessarily the mouse driver itself. The underlying hardware driver (.ucd) should be checked not to have e.g. excessive delays in the USB handling code. After all, the mouse driver regularly calls the hardware driver.

**Comment by th-otto** [comment]
Bump. Does the problem still persist after all the recent changes to the usb drivers?

**Comment by DavidGZ** [comment]
I've just tested it with the same hardware that was reported by @infusixllc  (CT60 + EtherNAT) and the mouse is working fine here now.

**Comment by mikrosk** [comment]
Looks like fixed, @infusixllc feel free to reopen if not.
