### ISSUE TITLE
Potential address error crash in USB storage driver

### ISSUE THREAD

**Issue by czietz** [freemint/freemint#81]
Hello,

in _TOSONLY_ mode, the USB storage driver uses a potentially dangerous way to get the XHDI cookie: 
https://github.com/freemint/freemint/blob/1196c6f665b6eed314b419ce560f445ebaeae5a1/sys/usb/src.km/udd/storage/xhdi.c#L1036

The problem lies in the cast: `*((long *)"XHDI")` gets compiled into

```
xhdi_string:
dc.b "XHDI",0
[...]
move.l  xhdi_string,d1
```

..., i.e. the code actually reads the memory location `xhdi_string` instead of loading the immediate value #0x58484449 (=XHDI) into D1. However, the compiler does not care about the alignment of `xhdi_string` in memory. It is a char array, after all. But the 68000 can only read longwords from even addresses. (This was changed iirc in the 68020.) 

So, if by chance `xhdi_string` is at an odd memory location, the driver crashes with 3 bombs = address error. It is pure luck that the driver works. By introducing some unrelated changes I changed the location of `xhdi_string`, exposing this crash.

The code should be modified (in several places!) not to use the dangerous cast.

**Comment by th-otto** [comment]
Örks. Not only dangerous because of the address alignment, but also inefficient since it reads the value from memory, where it could just use the constant value. Especially, since that constant is already defined in sys/cookie.h.
