### ISSUE TITLE
Exclude USB.ACC from FreeMiNT binary distribution

### ISSUE THREAD

**Issue by czietz** [freemint/freemint#86]
As is well-known USB.ACC (_USB Accessory for TOS_) is only needed for TOS USB support. It doesn't even work properly under MiNT, just displaying _Initializing...._ Yet, it is included in the FreeMiNT snapshots at https://bintray.com/freemint/freemint/snapshots/ as mint\1-19-xxx\sysroot\GEM\usb\usb.acc, causing confusion with users who try to use it under MiNT and then report it as buggy.

Imho, USB.ACC should only be included in the usb4tos snapshots.

**Comment by mikrosk** [comment]
Hmm, good point. I guess its place is in `freemint-1-19-*-usb4tos.zip` archives. Will take a look when time permits.

**Comment by mikrosk** [comment]
Fixed by freemint/travis-scripts@fb2f9de4
