### ISSUE TITLE
Dubious busy loop

### ISSUE THREAD

**Issue by th-otto** [freemint/freemint#88]
The code at https://github.com/freemint/freemint/blob/11b5ada1e1b2a98687c974ec0522b2e377f7b2ed/sys/sockets/xif/svethlana/svethlana.c#L1125 looks rather dubious. Not only is the loop not calibrated in any way, the asm isn't declared as volatile, and has no side effects like inputs or outputs, so i would bet that the whole loop might be optimized away, or at least the "nop" moved outside of it.

**Comment by mikrosk** [comment]
Well, the purpose is obvious (although the implementation is very trivial) -- to insert a some kind of wait() call. Usually the CT60 + an expansion card dictates running at 66 MHz or less so I'd say that covers the calibration part. ;)

I own the hardware but need to setup a reliable test environment for this kind of refactoring.

**Comment by th-otto** [comment]
If i'm not mistaken, the produced by that loop is:

[0000072e] 42af 001a                 clr.l     26(a7)
[00000732] 202f 001a                 move.l    26(a7),d0
[00000736] 0c80 0000 03e7            cmpi.l    #$000003E7,d0
[0000073c] 6218                      bhi.s     .L73
.L84:
[0000073e] 4e71                      nop
[00000740] 202f 001a                 move.l    26(a7),d0
[00000744] 5280                      addq.l    #1,d0
[00000746] 2f40 001a                 move.l    d0,26(a7)
[0000074a] 202f 001a                 move.l    26(a7),d0
[0000074e] 0c80 0000 03e7            cmpi.l    #$000003E7,d0
[00000754] 63e8                      bls.s     .L84
.L73:

The reason for that rather ineffective looking code seems to be that the loop variable is declared as volatile. That also seems to prevent it from not being optimized away. So unless David thinks this might not work with higher frequencies, we can close this.

**Comment by DavidGZ** [comment]
http://www.atari-forum.com/viewtopic.php?f=100&t=31429&p=346883&hilit=supervidel+clock#p346883
There somebody says that is using the Svetlana at 75 MHz but it gets unstable at higher frequencies,  could be a hardware limitation but with that code it could be also the drivers fault.

I have a Svethlana card but not a rev 6 060 to test those higher frequencies. I'm going to ask the Nature brothers if they remember which frequencies they tested while developing the driver.

**Comment by mikrosk** [comment]
@DavidGZ my memory is terrible. I have been using CT60e+SV+Svethlana at 85 MHz without any problem. With FreeMiNT drivers, of course. So whatever that loops does, it's either still enough or not important at all.

**Comment by mfro0** [comment]
Frankly, I wouldn't touch that loop and would propose to close this unless somebody objects (and can prove it's really wrong here with a test on real hardware). The `volatile` declaration clearly indicates that somebody was thinking something when they introduced the loop.

Remember, on a 060 (as well as on the ColdFires), a NOP isn't just an empty instruction doing nothing as it was on the 68000. It flushes the pipeline(s) and is one of the most expensive instructions you can do on these machines (9 clocks on a 060 if I remember right).

**Comment by DavidGZ** [comment]
I got an answer from Nature:
>I use the CT60e (and CT60 before that) + Svethlana at 95 MHz since several years now, with no stability issues.

So I think we can leave the code as it is and close this issue.

**Comment by mfro0** [comment]
Fine. Thank you @DavidGZ !
