### ISSUE TITLE
Shift overflow warning

### ISSUE THREAD

**Issue by th-otto** [freemint/freemint#89]
That line gives https://github.com/freemint/freemint/blob/8f44ec0c51c4d803ce510573b3ff81fd4bac3675/tools/sysctl/sysctl.c#L88

sysctl.c:88:31: warning: result of '-2 << 31' requires 33 bits to represent, but 'int' only has 32 bits [-Wshift-overflow=]
 #define CTLTYPE_LIMIT ((~0x1) << 31)

Can someone enlighten me what was intended there? ;)

**Comment by mikrosk** [comment]
Really odd. Is that code even needed? Looks like a debugging helper anyway. I guess the idea was `(0x01<<31)` or something like that.

**Comment by th-otto** [comment]
You're right, seems it just can be any value that does not clash with one of the others. Fixed now.
