### ISSUE TITLE
Provide a minimal startup code for tools

### ISSUE THREAD

**Issue by mikrosk** [freemint/freemint#9]
xaloader, mintload, nohog2.acc and maybe more would benefit from a shared, small, GEM-friendly startup code with basic string / cookie / gem functions. Right now they either copy the same files over or use the bloated mintlib.

**Comment by mfro0** [comment]
libcmini provides this already ;)

**Comment by mikrosk** [comment]
Of course it does but how would you use it for this specific case? I mean, if you still want to have mintlib as the main library installed.

It's OK to require to have libcmini installed but then the archive should be compatible with mintlib. For instance using a suffix, like libc_mini.a and includes from `<prefix>/include/libcmini`.

**Comment by mfro0** [comment]
I've opened a pull request regarding this issue

**Comment by mikrosk** [comment]
Btw you can link it, so if you write something "Meant as a fix for #9", we'll see it here as well. :)

**Comment by mikrosk** [comment]
#11 (libcmini for nohog2.acc) has been merged so this opens the option to have it enabled for *all* freemint tools/executables which don't rely on specific mintlib features.

**Comment by mfro0** [comment]
hypview compiled with libcmini shrinks executable size from 252 KB to 147 KB.

Note that you need latest libcmini. I had to remove `getcookie()` as it collided with hypview's own implementation (and doesn't belong into a c-library anyway).

Some testing (with libcmini) could help (I have only a very limited set of HYPs).

Also looked into fsetter, but that has several mintlib dependencies (`statfs` and probably more). When I find time, I will have a look if that could be "downgraded" to use native MiNT calls instead.

**Comment by th-otto** [comment]
For HypView, it might be better to use a version that was compiled by Pure-C for the releases. libcmini makes executables small, but also very slow when using buffered streamio. Also note that for HypView i've made a new version some time ago, available at https://github.com/th-otto/hypview, which, amongst others, also contains a hcp compiler, viewers for win32 etc. Needs a bit cleanup though, some things might still depend on my private environment.

**Comment by mfro0** [comment]
>For HypView, it might be better to use a version that was compiled by Pure-C for the releases.
> libcmini makes executables small, but also very slow when using buffered streamio.

I would agree instantly if HypView would indeed do buffered I/O (which it doesn't, as far as I can tell). I only had a brief look, but it appears file I/O is done with plain GEMDOS functions only.

**Comment by mikrosk** [comment]
Hmm, I have (shamefully) realised that I haven't kept my promise in https://github.com/freemint/freemint/pull/11#issuecomment-279354996 and haven't enabled libcmini in Travis by default. @mfro0 what would you suggest - git clone or https://github.com/mfro0/libcmini/releases/latest ?

**Comment by mfro0** [comment]
If we want a stable release schema, MiNT releases should probably be limited to released libcmini versions. And this should be as well what people should test before release, i.e. what goes into automated trunk builds (currently, my hope is a new MiNT release isn't too far away anyway).

I think the other way round would be asking for trouble.

If developers want latest for testing (because of a missing feature, for example), they should be able to do so in a private fork. End users probably do not have this luxury.

**Comment by vinriviere** [comment]
With the luxury of automated build tools, we could have 2 branches for automated builds: stable and dev 😁

**Comment by mfro0** [comment]
> With the luxury of automated build tools, we could have 2 branches for automated builds: stable and dev grin

Main reason for bugs is - as experience tells - lack of testing. Two different builds to chose from would split the (already pretty scarce) resource "testers" into two distinct, even smaller groups and thus reduce quality (at least my opinion). Additionally, I'm a self-confessed fan of simple ("KISS") solutions ;)

**Comment by mikrosk** [comment]
> Hmm, I have (shamefully) realised that I haven't kept my promise in [#11 (comment)](https://github.com/freemint/freemint/pull/11#issuecomment-279354996) and haven't enabled libcmini in Travis by default.

A few months later but I have finally done it: https://github.com/freemint/freemint/commit/7e57b5792737dd8e6383254756a9760614f33a23 and https://github.com/freemint/travis-scripts/commit/efc50e13cad619cb1882c9671d3c293472af0f00.

For now, only HypView and nohog2.acc are benefiting from it but the 'framework' is there.
