### ISSUE TITLE
dhcp hangs when no ethernet connection

### ISSUE THREAD

**Issue by ps68060** [freemint/freemint#90]
I have noticed that if I have no network cable plugged in, during the boot process, dhcp will just wait forever preventing the boot from completing.

This is on a Milan with a pci ethernet card (RTL 8139).

**Comment by mfro0** [comment]
Which DHCP client do you use?

**Comment by ps68060** [comment]
Is there more than one ?

Mine says:

isc-dhclient-V3.1-ESV

**Comment by mfro0** [comment]
I dont't think this is a MiNT, but merely a configuration issue. There are configuration options you could try:

- try the `-nw` argument on dhclient startup. This should daemonise the client immediately (but might lead to problems with later startup scripts that expect configured interfaces).
- adjust the `timeout` value in dhclient.conf

**Comment by mfro0** [comment]
> I tried /sbin/dhclient -- help which hangs and then I tried /sbin/dhclient status and dhclient status both of 
> which hang indefinitely.

if `/sbin/dhclient --help` (you have a superflous space between `--` and `help` above - is this a typo?) hangs already, I would assume you have some other problem.

With the `--help` option, `dhclient` shouldn't even try to touch the network interface.

My first assumption would be that your `dhclient` executable is corrupted somehow.

**Comment by ps68060** [comment]
It was a typo. I have to post from a linux box because this page isn't accessible from an Atari.

dhclient starts fine at boot time.

I ran dhclient status and it displays several lines of message but no actual status. I tried to copy it onto this box but having run dhclient status it then wasn't able to start smbd. I had to reboot to get smbd to work:

bash-4.3# dhclient status
Internet Systems Consortium DHCP Client V3.1-ESV
Copyright 2004-2010 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/

status: cannot get FLAGS: No such file or directory
Can't bind to dhcp address: Address already in use
Please make sure there is no other dhcp server
running and that there's no entry for dhcp or
bootp in /etc/inetd.conf.   Also make sure you
are not running HP JetAdmin software, which
includes a bootp server.

If you did not get this software from ftp.isc.org, please
get the latest from ftp.isc.org and install that before
requesting help.

If you did get this software from ftp.isc.org and have not
yet read the README, please read it before requesting help.
If you intend to request help from the dhcp-server@isc.org
mailing list, please read the section on the README about
submitting bug reports and requests for help.

--

I am reminded of the issue with rsync which also hangs at the end of the process.

Maybe it's my config, I got dhclient working a long time ago and left it unchanged without playing with the settings.

**Comment by mfro0** [comment]
> dhclient starts fine at boot time.
>
> I ran dhclient status and it displays several lines of message but no actual status. I tried to copy it onto this box but having run dhclient status it then wasn't able to start smbd. I had to reboot to get smbd to work:

So your binary appears fine (which is a good thing).

Note that there is no `status` option for `dhclient`. Basically, you tried to start `dhclient` on a network interface named `status` which you (obviously) not have, **and** you tried to start it with another `dhclient` already running, thus the error.

Did you try my suggestions from yesterday?

**Comment by ps68060** [comment]
The -nw probably won't work because other things are started straight afterwards, like portmap, and they would probably fail if dhcp hasn't set things up.

I had a look at timeout, the docs don't say what the time unit is (seconds, years ?) also I don't have a dhclient.conf does it go in /etc or /etc/dhcp ?

**Comment by ps68060** [comment]
Running the script /etc/init.d/dhclient status actually does give a status :-)

Using the script to restart, it stopped dhclient but hung when doing the start.

**Comment by mikrosk** [comment]
@ps68060 I'm lazy to check but I think you're mixing two things together. `/etc/init.d/dhclient ` and `/sbin/dhclient` are not the same thing. The former is a script to run the latter. So I'd suggest to do what @mfro0 recommended, run the latter with `--help`.

**Comment by mfro0** [comment]
Closed because the original poster's issue appears to be a configuration problem with dhcpd.conf rather than a MiNT kernel issue.

@ps68060 : feel free to further discuss this on the MiNT mailing list
