### ISSUE TITLE
Dubious memset

### ISSUE THREAD

**Issue by th-otto** [freemint/freemint#93]
Just spotted a memset that takes the address of a pointer:

https://github.com/freemint/freemint/blob/9e501efa4238dc2e54f6a008de63e5055240b8d5/sys/usb/src.km/udd/eth/usb_ether.c#L254

**Comment by th-otto** [comment]
> Luckily, though, eth.prg is not needed for the USB-to-Ethernet STinG 

As far as i understand the code, it is the program that installs the EUSB cookie. Isn't that needed for the TOS-only USB drivers?

**Comment by czietz** [comment]
> As far as i understand the code, it is the program that installs the EUSB cookie. Isn't that needed for the TOS-only USB drivers?

No. They couldn't care less about the EUSB cookie.

**Comment by th-otto** [comment]
Ok, what is this program then good for? ;)

**Comment by czietz** [comment]
Nothing, imho. ;)

**Comment by atic-atac** [comment]
It is, just that there's uncommitted code right now.

**Comment by atic-atac** [comment]
I do find it unforunate that the USB-Ethernet STinG driver has ended up in it's own repository too.

It's using the same asix driver and USB code, so surely there's a way to get it into the FreeMiNT repo.
