### ISSUE TITLE
hyp_view.rsc changed?

### ISSUE THREAD

**Issue by th-otto** [freemint/freemint#95]
commit https://github.com/freemint/freemint/commit/85e4d6d8891813fa13fbfd07dbcb668497525eb9 also changed the resource file (why, if its only intend was to compile against libcmini?), but not the definition file hyp_view.rsm. The two now don't match, and RSM refuses to load it at all. Please revert the changes to the resource file.

**Comment by th-otto** [comment]
And while we are at it: the next version of ORCS will be able to load/save resource files as JSON. That will have the advantage that:

- such mismatches won't happen anymore, as both the data and the names are written to the same file.
- It is a text based format, so no more need for binary diffs.

Disadvantage (or maybe not ;): you won't be able to load such files with Interface and/or RSM.

**Comment by mikrosk** [comment]
Related comment: https://github.com/freemint/freemint/issues/9#issuecomment-406044441

**Comment by czietz** [comment]
Deja vu? https://github.com/freemint/freemint/issues/68

**Comment by mfro0** [comment]
> Related comment: #9 (comment)

Yes, that would be me. Hypview didn't run for me with the resource and I was assuming it corrupt (which it somehow is, I guess, as XaAES doesn't like it). Apologies.

**Comment by th-otto** [comment]
>Apologies.

No problem. Just didn't understand why it was changed with that commit, since that is a totally unrelated problem.

@czietz thanks for reminding, almost forgot that one. If that problem still persists, and the main file is corrupted, we should make a decision about that. Obviously, in its current state (even before that commit), the main resource file is unusable. Even if it was not corrupted, if you want to change it, you are forced to use RSM. which is a bit unpleasant at least, since RSM is not developed anymore, and the available versions are not really usable. If noone objects, we should get rid of that file altogether. Which also means, that you have to change 3 resource files, should the need arise.

In the long term, it might really be better to switch to the new version i made, but i would postpone that until after the next release (which hopefully will be soon).

**Comment by th-otto** [comment]
Fixed now by https://github.com/freemint/freemint/commit/80c12bb818d2f71149c59f260b2595cf59894edb. Let me know if there should any problems with it.
